#!/bin/bash
set -euo pipefail

ROM_NAME="s4"
MAIN_ASM="main.asm"
TOOLS="${TOOLS:-tools}"

export AS_MSGPATH="${TOOLS}"
export USEANSI="n"

# Parse flags
PRINT_ERRORS_ONLY=0
NO_LINT=0
for arg in "$@"; do
    case "$arg" in
        -pe) PRINT_ERRORS_ONLY=1 ;;
        -nl|--no-lint) NO_LINT=1 ;;
    esac
done

# Assembler flags
# -U: case-sensitive symbols — required since §5 RAM fields (Phys_accel)
# and physics constants (PHYS_ACCEL) differ only by case. Verified to
# produce byte-identical output on the pre-§5 codebase.
ASFLAGS="-cpu 68000 -xx -n -q -c -A -L -U"
ASFLAGS="${ASFLAGS} -OLIST ${ROM_NAME}.lst"
ASFLAGS="${ASFLAGS} -o ${ROM_NAME}.p"
ASFLAGS="${ASFLAGS} -shareout ${ROM_NAME}.h"
ASFLAGS="${ASFLAGS} -i ."

if [[ "${DEBUG:-0}" == "1" ]]; then
    ASFLAGS="${ASFLAGS} -D __DEBUG__"
fi

if [[ "${PRINT_ERRORS_ONLY}" == "0" ]]; then
    ASFLAGS="${ASFLAGS} -E ${ROM_NAME}.log"
fi

# Build the vendored salvador (ZX0 packer) once if missing
if [[ ! -x "${TOOLS}/bin/salvador" ]]; then
    echo "Building salvador (ZX0 packer)..."
    make -C "${TOOLS}/salvador" -s
    mkdir -p "${TOOLS}/bin"
    cp "${TOOLS}/salvador/salvador" "${TOOLS}/bin/salvador"
fi

echo "Generating baseline collision tables (heightmaps, heightmaps_rot, angles, solidity — strip-gen re-emits the authoritative set)..."
python3 "${TOOLS}/gen_collision_data.py" data/collision

echo "Generating OJZ section data..."
python3 "${TOOLS}/ojz_strip_gen.py" generate

# Editor-authored BG override (level editor art) — replaces the generated
# zone BG when data/editor_bg_override.json exists.
if [[ -f data/editor_bg_override.json ]]; then
    python3 "${TOOLS}/inject_editor_bg.py"
fi

# Per-section tile art → ZX0 (load-time tier). Each .zx0 carries the
# project's 4-byte wrapper [u16 BE uncompressed size][u8 flags=0][u8 version=2]
# ahead of the raw salvador (modern/V2) stream — the loader peeks the size
# for DMA and dispatches the decompressor on the version byte.
#
# Size guards: the wrapper's size field is u16 (max 65535), and the runtime
# decompresses into Decomp_Buffer — a 9,600-byte alias of Tile_Cache_Nametable
# (ram.asm:34; capacity = TILE_CACHE_NT_SIZE in constants.asm). Any blob
# exceeding either limit would corrupt RAM at load time — fail the build.
DECOMP_BUFFER_CAPACITY=9600     # = TILE_CACHE_NT_SIZE (80*60*2)
echo "Compressing OJZ per-section tile blobs with ZX0 (salvador)..."
rm -f data/generated/ojz/act1/sec*_tiles.zx0 data/generated/ojz/act1/sec*_tiles.zx0.tmp
for sec_bin in data/generated/ojz/act1/sec*_tiles.bin; do
    sec_zx0="${sec_bin%.bin}.zx0"
    if [[ -s "$sec_bin" ]]; then
        size=$(stat -c%s "$sec_bin")
        if (( size > 65535 )); then
            echo "ERROR: ${sec_bin} is ${size} bytes — exceeds the u16 wrapper size field (65535)."
            exit 1
        fi
        if (( size > DECOMP_BUFFER_CAPACITY )); then
            echo "ERROR: ${sec_bin} is ${size} bytes — exceeds Decomp_Buffer capacity (${DECOMP_BUFFER_CAPACITY})."
            exit 1
        fi
        "${TOOLS}/bin/salvador" "$sec_bin" "${sec_zx0}.tmp" > /dev/null
        printf '%b' "$(printf '\\x%02x\\x%02x\\x00\\x02' $((size >> 8)) $((size & 255)))" > "$sec_zx0"
        cat "${sec_zx0}.tmp" >> "$sec_zx0"
        rm -f "${sec_zx0}.tmp"
    else
        # Zero-length section — empty v3 stub (size 0, flags 0, version 1,
        # EOS word). Loaders skip on size 0 before reading the version byte.
        printf '\x00\x00\x00\x01\x00\x00' > "$sec_zx0"
    fi
done

# Content-dedup the tile blobs: sections in the same color class share one
# union blob (e.g. OJZ sec0/2/4/6/8 and sec1/3/5/7 are byte-identical), so
# identical .zx0 files collapse to a single BINCLUDE; duplicates become
# label aliases. The act descriptor includes this file instead of
# BINCLUDE-ing per-section blobs.
echo "Deduplicating tile blobs (content-hash aliasing)..."
TILE_BLOB_ASM="data/generated/ojz/act1/sec_tile_blobs.asm"
declare -A tile_blob_owner
{
    echo "; Per-section tile blob BINCLUDEs with content dedup — auto-generated by build.sh"
    echo "; Identical blobs are stored once; duplicate sections alias via equ."
    for sec_zx0 in data/generated/ojz/act1/sec*_tiles.zx0; do
        name=$(basename "$sec_zx0")
        sec="${name#sec}"; sec="${sec%_tiles.zx0}"
        hash=$(sha256sum "$sec_zx0" | cut -d' ' -f1)
        if [[ -n "${tile_blob_owner[$hash]:-}" ]]; then
            echo "OJZ_Sec${sec}_Tiles equ OJZ_Sec${tile_blob_owner[$hash]}_Tiles    ; identical to sec${tile_blob_owner[$hash]}"
        else
            tile_blob_owner[$hash]="$sec"
            echo "OJZ_Sec${sec}_Tiles:"
            echo "    BINCLUDE \"data/generated/ojz/act1/sec${sec}_tiles.zx0\""
            echo "    align 2"
        fi
    done
} > "$TILE_BLOB_ASM"

echo "Generating OJZ block data..."
python3 "${TOOLS}/ojz_block_gen.py" generate

echo "Generating compression self-test vectors..."
python3 "${TOOLS}/gen_compression_vectors.py"

if [[ "${NO_LINT:-0}" == "0" ]]; then
    echo "Linting..."
    if ! python3 "${TOOLS}/s4lint.py" "${MAIN_ASM}"; then
        echo "Lint errors found — fix before assembling."
        exit 1
    fi
fi

# Remove stale intermediates so a failed assembly can't silently
# leave a previous .p file for p2bin to convert.
rm -f "${ROM_NAME}.p" "${ROM_NAME}.h"

echo "Assembling ${MAIN_ASM}..."
"${TOOLS}/asl" ${ASFLAGS} "${MAIN_ASM}"

if [[ ! -f "${ROM_NAME}.p" ]]; then
    echo "ERROR: Assembly produced no output (${ROM_NAME}.p missing)."
    echo "       Check ${ROM_NAME}.log for errors."
    exit 1
fi

echo "Converting to binary..."
"${TOOLS}/p2bin" "${ROM_NAME}.p" "${ROM_NAME}.bin" "${ROM_NAME}.h"

# Symbol table for MD Debugger (if listing exists)
if [[ -f "${ROM_NAME}.lst" ]]; then
    "${TOOLS}/convsym" "${ROM_NAME}.lst" "${ROM_NAME}.bin" \
        -input as_lst -range 0 FFFFFF -exclude -filter "z[A-Z].+" -a 2>/dev/null || true
fi

echo "Fixing header checksum..."
"${TOOLS}/fixheader" "${ROM_NAME}.bin"

# Clean intermediates
rm -f "${ROM_NAME}.p" "${ROM_NAME}.h"

ROM_SIZE=$(stat -c%s "${ROM_NAME}.bin")
ROM_KB=$(awk "BEGIN {printf \"%.1f\", ${ROM_SIZE}/1024}")
ROM_PCT=$(awk "BEGIN {printf \"%.1f\", ${ROM_SIZE}/4194304*100}")
echo "Build complete: ${ROM_NAME}.bin — ${ROM_SIZE} bytes (${ROM_KB} KB, ${ROM_PCT}% of 4MB)"

# Budget summary
if [[ -f "${ROM_NAME}.lst" ]]; then
    python3 "${TOOLS}/s4budget.py" "${ROM_NAME}.lst" "${ROM_NAME}.bin" --summary || true
fi

# Update ctags symbol index
if command -v ctags &>/dev/null; then
    ctags -R .
fi
