#!/bin/bash
set -euo pipefail

GAME="${1:-sonic4}"
# sonic4 keeps the historical ROM name s4.bin (game content); other games use their own name.
if [[ "$GAME" == "sonic4" ]]; then ROM_NAME="s4"; else ROM_NAME="$GAME"; fi
MAIN_ASM="games/${GAME}/main.asm"
TOOLS="${TOOLS:-tools}"

export AS_MSGPATH="${TOOLS}"
export USEANSI="n"

# Parse flags
PRINT_ERRORS_ONLY=0
NO_LINT=0
for arg in "$@"; do
    case "$arg" in
        -pe) PRINT_ERRORS_ONLY=1 ;;
        -nl|--no-lint) NO_LINT=1 ;;
    esac
done

# Assembler flags
# -U: case-sensitive symbols — required since §5 RAM fields (Phys_accel)
# and physics constants (PHYS_ACCEL) differ only by case. Verified to
# produce byte-identical output on the pre-§5 codebase.
ASFLAGS="-cpu 68000 -xx -n -q -c -A -L -U"
ASFLAGS="${ASFLAGS} -OLIST ${ROM_NAME}.lst"
ASFLAGS="${ASFLAGS} -o ${ROM_NAME}.p"
ASFLAGS="${ASFLAGS} -shareout ${ROM_NAME}.h"
ASFLAGS="${ASFLAGS} -i ."

if [[ "${DEBUG:-0}" == "1" ]]; then
    ASFLAGS="${ASFLAGS} -D __DEBUG__"
fi

# Sound engine ON by default now (the driver is the active dev target). Disable
# explicitly with SOUND_DRIVER_ENABLED=0 ./build.sh for a smaller silent ROM.
if [[ "${SOUND_DRIVER_ENABLED:-1}" == "1" ]]; then
    ASFLAGS="${ASFLAGS} -D SOUND_DRIVER_ENABLED"
fi

# DEBUG-only: mirror Z80 driver state into 68k RAM each frame for MCP inspection.
# This stops the Z80 ~190us/frame for the copy -> an audible 60Hz tick, so it is
# OFF by default (clean audio in DEBUG builds). Enable only when inspecting Z80
# state via the Sound_Dbg_Mirror; expect the tick while it is on.
if [[ "${SOUND_DBG_MIRROR:-0}" == "1" ]]; then
    ASFLAGS="${ASFLAGS} -D SOUND_DBG_MIRROR"
fi

if [[ "${PRINT_ERRORS_ONLY}" == "0" ]]; then
    ASFLAGS="${ASFLAGS} -E ${ROM_NAME}.log"
fi

# Build the vendored salvador (ZX0 packer) once if missing
if [[ ! -x "${TOOLS}/bin/salvador" ]]; then
    echo "Building salvador (ZX0 packer)..."
    make -C "${TOOLS}/salvador" -s
    mkdir -p "${TOOLS}/bin"
    cp "${TOOLS}/salvador/salvador" "${TOOLS}/bin/salvador"
fi

echo "Importing Sonic & Knuckles collision shape set (fixed 252-shape vocabulary)..."
python3 "${TOOLS}/import_sk_collision.py"

echo "Generating OJZ section data..."
python3 "${TOOLS}/ojz_strip_gen.py" generate

# Editor-authored BG override (level editor art) — replaces the generated
# zone BG when data/editor_bg_override.json exists.
if [[ -f data/editor_bg_override.json ]]; then
    python3 "${TOOLS}/inject_editor_bg.py"
fi

# Act art pool pages → ZX0 (load-time tier). The generator emits the
# globally-deduped act art pool split into fixed-size pages of ART_POOL_PAGE_TILES
# (256) tiles = 8192 B each. Each .zx0 carries the project's 4-byte wrapper
# [u16 BE uncompressed size][u8 flags=0][u8 version=2] ahead of the raw salvador
# (modern/V2) stream — the loader peeks the size for DMA and dispatches the
# decompressor on the version byte.
#
# Size guard: a single page must not exceed one VRAM page worth of tiles
# (ART_POOL_PAGE_BYTES). The generator should never emit an oversized page; a
# page larger than this is a generator bug and would overrun the page's VRAM
# slot at load time — fail the build.
ART_POOL_PAGE_BYTES=8192      # ART_POOL_PAGE_TILES (256) * 32
echo "Compressing act art pool pages with ZX0 (salvador)..."
rm -f data/generated/ojz/act1/act_pool_page*.zx0 data/generated/ojz/act1/act_pool_page*.zx0.tmp
for page_bin in data/generated/ojz/act1/act_pool_page*.bin; do
    page_zx0="${page_bin%.bin}.zx0"
    size=$(stat -c%s "$page_bin")
    if (( size > ART_POOL_PAGE_BYTES )); then
        echo "ERROR: ${page_bin} is ${size} B — exceeds one page (${ART_POOL_PAGE_BYTES})."; exit 1
    fi
    "${TOOLS}/bin/salvador" "$page_bin" "${page_zx0}.tmp" > /dev/null
    printf '%b' "$(printf '\\x%02x\\x%02x\\x00\\x02' $((size >> 8)) $((size & 255)))" > "$page_zx0"
    cat "${page_zx0}.tmp" >> "$page_zx0"; rm -f "${page_zx0}.tmp"
done

# Emit the act art pool include: page BINCLUDEs followed by a long-word
# address table the loader indexes by page number. The act descriptor includes
# this file instead of BINCLUDE-ing per-section blobs.
echo "Emitting act art pool include..."
POOL_ASM="data/generated/ojz/act1/ojz_act_pool.asm"
{
  echo "; Auto-generated by build.sh — act art pool page BINCLUDEs + address table"
  i=0
  for page_zx0 in data/generated/ojz/act1/act_pool_page*.zx0; do
    echo "OJZ_Act_Pool_Page${i}:"
    echo "        BINCLUDE \"${page_zx0}\""
    echo "        align 2"
    i=$((i+1))
  done
  echo "OJZ_Act_Pool_PageTable:"
  j=0
  while (( j < i )); do echo "        dc.l    OJZ_Act_Pool_Page${j}"; j=$((j+1)); done
} > "$POOL_ASM"

echo "Generating OJZ block data..."
python3 "${TOOLS}/ojz_block_gen.py" generate

echo "Generating compression self-test vectors..."
python3 "${TOOLS}/gen_compression_vectors.py"

echo "Transcoding core SFX set (S3K -> SFX blobs)..."
python3 "${TOOLS}/sfx_transcode.py" generate

if [[ "${NO_LINT:-0}" == "0" ]]; then
    echo "Linting..."
    if ! python3 "${TOOLS}/s4lint.py" "${MAIN_ASM}"; then
        echo "Lint errors found — fix before assembling."
        exit 1
    fi
fi

# Remove stale intermediates so a failed assembly can't silently
# leave a previous .p file for p2bin to convert.
rm -f "${ROM_NAME}.p" "${ROM_NAME}.h"

echo "Assembling ${MAIN_ASM}..."
"${TOOLS}/asl" ${ASFLAGS} "${MAIN_ASM}"

if [[ ! -f "${ROM_NAME}.p" ]]; then
    echo "ERROR: Assembly produced no output (${ROM_NAME}.p missing)."
    echo "       Check ${ROM_NAME}.log for errors."
    exit 1
fi

echo "Converting to binary..."
"${TOOLS}/p2bin" "${ROM_NAME}.p" "${ROM_NAME}.bin" "${ROM_NAME}.h"

# Symbol table for MD Debugger (if listing exists)
if [[ -f "${ROM_NAME}.lst" ]]; then
    "${TOOLS}/convsym" "${ROM_NAME}.lst" "${ROM_NAME}.bin" \
        -input as_lst -range 0 FFFFFF -exclude -filter "z[A-Z].+" -a 2>/dev/null || true
fi

echo "Fixing header checksum..."
"${TOOLS}/fixheader" "${ROM_NAME}.bin"

# Clean intermediates
rm -f "${ROM_NAME}.p" "${ROM_NAME}.h"

ROM_SIZE=$(stat -c%s "${ROM_NAME}.bin")
ROM_KB=$(awk "BEGIN {printf \"%.1f\", ${ROM_SIZE}/1024}")
ROM_PCT=$(awk "BEGIN {printf \"%.1f\", ${ROM_SIZE}/4194304*100}")
echo "Build complete: ${ROM_NAME}.bin — ${ROM_SIZE} bytes (${ROM_KB} KB, ${ROM_PCT}% of 4MB)"

# Budget summary
if [[ -f "${ROM_NAME}.lst" ]]; then
    python3 "${TOOLS}/s4budget.py" "${ROM_NAME}.lst" "${ROM_NAME}.bin" --summary || true
fi

# Update ctags symbol index
if command -v ctags &>/dev/null; then
    ctags -R .
fi
