#!/bin/bash
set -euo pipefail

TOOLS="${TOOLS:-tools}"
PASSED=0
FAILED=0
TOTAL=0

pass_test() {
    echo "  PASS: $1"
    PASSED=$((PASSED + 1))
    TOTAL=$((TOTAL + 1))
}

fail_test() {
    echo "  FAIL: $1"
    FAILED=$((FAILED + 1))
    TOTAL=$((TOTAL + 1))
}

section() {
    echo ""
    echo "========================================"
    echo "$1"
    echo "========================================"
}

# -----------------------------------------------
section "1. S4LZ Compression Self-Tests"
# -----------------------------------------------
if python3 "${TOOLS}/s4lz.py" test; then
    pass_test "S4LZ self-tests"
else
    fail_test "S4LZ self-tests"
fi

# -----------------------------------------------
section "2. S4LZ Real-Data Round-Trip"
# -----------------------------------------------
if [ -f "games/sonic4/test/title_art.bin" ]; then
    if python3 "${TOOLS}/s4lz.py" verify games/sonic4/test/title_art.bin; then
        pass_test "S4LZ round-trip: title_art.bin"
    else
        fail_test "S4LZ round-trip: title_art.bin"
    fi

    if python3 "${TOOLS}/s4lz.py" verify --tile-delta games/sonic4/test/title_art.bin; then
        pass_test "S4LZ round-trip: title_art.bin (tile-delta)"
    else
        fail_test "S4LZ round-trip: title_art.bin (tile-delta)"
    fi
else
    fail_test "games/sonic4/test/title_art.bin not found"
fi

# -----------------------------------------------
section "3. DPLC Layout Tool Self-Tests"
# -----------------------------------------------
if python3 "${TOOLS}/dplc_layout.py" test; then
    pass_test "DPLC layout self-tests"
else
    fail_test "DPLC layout self-tests"
fi

# -----------------------------------------------
section "4. Sprite & DPLC Verification"
# -----------------------------------------------
if python3 "${TOOLS}/verify_sprites.py"; then
    pass_test "Sprite & DPLC verification"
else
    fail_test "Sprite & DPLC verification"
fi

# -----------------------------------------------
section "5. DPLC Optimized Art Integrity"
# -----------------------------------------------
# Verify optimized art+DPLC was produced correctly from originals
DPLC_OK=true

# The DPLC tables live under games/sonic4/data/dplc since the engine/game
# restructure. This loop kept the pre-restructure `data/dplc` paths, so every
# iteration took the else branch — which called neither pass_test nor fail_test,
# so the section contributed nothing to the totals and could not go red. It read
# as a passing gate while running zero comparisons.
#
# PROVENANCE UNRESOLVED (2026-08-13, character lens sweep). Fixing the paths made
# the comparison run for the first time, and it does not reproduce the committed
# artifacts — not by a near-miss:
#
#   sonic art:  regenerated 122,272 B (3821 tiles) vs committed 97,472 B (3046)
#   sonic dplc: regenerated   1,588 B             vs committed  2,368 B
#
# The committed art is SMALLER than its 3425-tile source (deduplicated); this
# tool's output is LARGER (per-frame linearization). They are different
# algorithms, so dplc_layout.py is not what produced the shipped blobs and this
# comparison can never pass as written. That is an owner question — which tool
# IS the producer, and should the committed artifacts be regenerated by it — not
# something to answer by leaving the tree permanently red.
#
# So the byte-compare is parked behind DPLC_REPRO=1 and the gap is PRINTED on
# every run rather than skipped in silence. What is verifiable today runs
# unconditionally in section 4 (verify_sprites.py), which checks every shipped
# DPLC's tile indices against its real art blob — the check this section's
# silence was hiding.
if [ "${DPLC_REPRO:-0}" != "1" ]; then
    echo "  KNOWN GAP: optimized-art reproduction is unverified — dplc_layout.py is not"
    echo "             the producer of the committed blobs (see the note above)."
    echo "             Run DPLC_REPRO=1 ./test.sh to execute the comparison anyway."
fi

for char in sonic tails tails_tail; do
    if [ "${DPLC_REPRO:-0}" != "1" ]; then break; fi
    ART_ORIG="art/uncompressed/characters/${char}.bin"
    ART_OPT="art/optimized/characters/${char}.bin"
    DPLC_ORIG="games/sonic4/data/dplc/${char}.bin"
    DPLC_OPT="games/sonic4/data/dplc/optimized/${char}.bin"

    if [ -f "$ART_ORIG" ] && [ -f "$ART_OPT" ] && [ -f "$DPLC_ORIG" ] && [ -f "$DPLC_OPT" ]; then
        # Re-run the layout tool to a temp file and compare
        TMPDIR=$(mktemp -d)
        python3 "${TOOLS}/dplc_layout.py" "$ART_ORIG" "$DPLC_ORIG" \
            --out-art "${TMPDIR}/art.bin" --out-dplc "${TMPDIR}/dplc.bin" 2>/dev/null

        if cmp -s "${TMPDIR}/art.bin" "$ART_OPT"; then
            pass_test "Optimized art matches: ${char}"
        else
            fail_test "Optimized art mismatch: ${char}"
            DPLC_OK=false
        fi

        if cmp -s "${TMPDIR}/dplc.bin" "$DPLC_OPT"; then
            pass_test "Optimized DPLC matches: ${char}"
        else
            fail_test "Optimized DPLC mismatch: ${char}"
            DPLC_OK=false
        fi

        rm -rf "$TMPDIR"
    else
        # A named gate whose inputs are absent is a RED gate, not a silent one.
        fail_test "Optimized art/DPLC inputs missing: ${char}"
        for f in "$ART_ORIG" "$ART_OPT" "$DPLC_ORIG" "$DPLC_OPT"; do
            [ -f "$f" ] || echo "         missing: $f"
        done
        DPLC_OK=false
    fi
done

# Knuckles deliberately ships a RAW dplc (games/sonic4/data/dplc/knuckles.bin is
# what knuckles_data.emp embeds), so he has no optimized twin to diff and cannot
# join the loop above. Assert the asymmetry rather than omitting him: if an
# optimization pass ever produces the optimized table, this fires and whoever
# added it must decide whether the ROM should embed it and add him to the loop.
if [ -f "games/sonic4/data/dplc/optimized/knuckles.bin" ]; then
    fail_test "knuckles now has an optimized DPLC — embed it and add him to the integrity loop"
    DPLC_OK=false
else
    pass_test "knuckles DPLC is raw-form by design (no optimized twin to verify)"
fi

# -----------------------------------------------
section "6. OJZ Strip Generator Self-Tests"
# -----------------------------------------------
if python3 "${TOOLS}/ojz_strip_gen.py" test; then
    pass_test "OJZ strip generator self-tests"
else
    fail_test "OJZ strip generator self-tests"
fi

# -----------------------------------------------
section "6b. Collision Pipeline Self-Tests"
# -----------------------------------------------
if python3 "${TOOLS}/collision_pipeline.py" test; then
    pass_test "Collision pipeline self-tests"
else
    fail_test "Collision pipeline self-tests"
fi

# -----------------------------------------------
section "7. ROM Build"
# -----------------------------------------------
# build.sh's first POSITIONAL is the GAME (engine/game split), so a bare
# `./build.sh -pe` resolved GAME="-pe" and died in the lint on
# games/-pe/game_root.asm — this gate had been RED-but-unbuilt, and the ROM
# assertions below were silently grading a STALE s4.bin from whenever someone
# last built by hand. Name the game explicitly; -pe stays as the (no-op) flag.
# REMOVE THE PRIOR ROM FIRST. The sanity checks below used to be gated on
# `[ -f "s4.bin" ]` alone, so when the build failed they graded whatever s4.bin a
# previous manual build had left on disk — six confident PASS lines about a ROM
# this run did not produce (tools lens sweep D4). Deleting it first makes that
# impossible rather than merely unlikely: no build, no file, no checks.
rm -f s4.bin

if ./build.sh sonic4 -pe 2>&1; then
    pass_test "ROM build"
    ROM_BUILT=1
else
    fail_test "ROM build"
    ROM_BUILT=0
fi

# ROM sanity checks — only meaningful if THIS run built the ROM. Both conditions
# are kept: ROM_BUILT is the honest gate, and -f survives someone reordering this.
if [ "$ROM_BUILT" = "1" ] && [ -f "s4.bin" ]; then
    ROM_SIZE=$(stat -c%s "s4.bin")

    # Check ROM is not empty
    if [ "$ROM_SIZE" -gt 512 ]; then
        pass_test "ROM size > 512 bytes (${ROM_SIZE} bytes)"
    else
        fail_test "ROM too small: ${ROM_SIZE} bytes"
    fi

    # Check ROM fits in 4MB
    if [ "$ROM_SIZE" -le 4194304 ]; then
        pass_test "ROM fits in 4MB"
    else
        fail_test "ROM exceeds 4MB: ${ROM_SIZE} bytes"
    fi

    # Check ROM is even-sized (convsym symbol appendix may add odd bytes — warn only)
    if [ $((ROM_SIZE % 2)) -eq 0 ]; then
        pass_test "ROM size is even"
    else
        echo "  WARN: ROM file size is odd (${ROM_SIZE} bytes) — likely debug symbol appendix"
    fi

    # Check header magic at $100
    HEADER=$(xxd -s 256 -l 16 -p "s4.bin")
    if [[ "$HEADER" == "5345474120474"* ]]; then
        pass_test "ROM header: SEGA GENESIS"
    else
        fail_test "ROM header missing SEGA magic: ${HEADER}"
    fi

    # Check vector table: SSP at $0, Reset PC at $4
    SSP=$(xxd -s 0 -l 4 -p "s4.bin")
    RESET=$(xxd -s 4 -l 4 -p "s4.bin")
    if [[ "$SSP" != "00000000" ]]; then
        pass_test "Vector table: SSP set (0x${SSP})"
    else
        fail_test "Vector table: SSP is zero"
    fi
    if [[ "$RESET" != "00000000" ]]; then
        pass_test "Vector table: Reset PC set (0x${RESET})"
    else
        fail_test "Vector table: Reset PC is zero"
    fi
else
    # Reached when THIS run did not produce a ROM. Previously unreachable in the
    # case that mattered: a stale s4.bin from an earlier manual build satisfied
    # `-f` and the six checks above graded it (tools lens sweep D4).
    fail_test "s4.bin not produced by this run — ROM sanity checks SKIPPED (not passed)"
fi

# -----------------------------------------------
section "8. Replay Net (headless oracle)"
# -----------------------------------------------
# The embedded input-replay regression net (engine/system/replay.emp + the two
# committed fixtures) had NO automated runner — it was invisible to every gate we
# own, and only a manual oracle procedure could detect a desync. That is how
# master stayed red from the Knuckles C4 merge until 2026-08-13 with nothing
# reporting it (docs/DEFERRED_WORK.md). The runner now exists in the sibling
# oracle-next repo; this section is candidate fix (a), wired up.
#
# tools/test_replay_fixture.py still does its own separate job (fixture STRUCTURE:
# length, tick count, checkpoint ring alignment). This gate is the other half —
# it actually replays the stream on an emulator and compares the checkpoints.
ORACLE_NEXT="${ORACLE_NEXT:-/home/volence/sonic_hacks/oracle-next}"
REPLAY_RUNNER="${ORACLE_NEXT}/target/release/replay_runner"
REPLAY_ROM="s4.debug.bin"
REPLAY_LST="s4.debug.lst"
REPLAY_READY=true

# The DEBUG shape is REQUIRED, and it is built here rather than assumed.
# `replay.emp` gates the checkpoint compare on `if DEBUG == 1` — the release
# shape steps over the payload without comparing, so it replays to completion
# having verified NOTHING (the runner refuses one for exactly that reason).
# Symbols also bind per-shape, so the .lst must be this ROM's own.
# Building it costs ~1.4 s (measured: sigil native build 1.0 s + ctags 0.4 s),
# which is far cheaper than the false green of grading a stale s4.debug.bin.
echo "  Building the DEBUG shape for the replay net..."
if DEBUG=1 ./build.sh sonic4 -pe 2>&1; then
    pass_test "DEBUG ROM build (replay net shape)"
else
    fail_test "DEBUG ROM build (replay net shape)"
    REPLAY_READY=false
fi

# A named gate whose inputs are absent is a RED gate, not a silent one
# (the lesson section 5 above paid for). No skips here.
if [ ! -x "$REPLAY_RUNNER" ]; then
    fail_test "replay runner missing or not executable: ${REPLAY_RUNNER}"
    echo "         build it: cd ${ORACLE_NEXT} && cargo build --release -p oracle-replay"
    echo "         (override the repo location with ORACLE_NEXT=/path/to/oracle-next)"
    REPLAY_READY=false
fi
for f in "$REPLAY_ROM" "$REPLAY_LST"; do
    if [ ! -f "$f" ]; then
        fail_test "replay net input missing: $f"
        REPLAY_READY=false
    fi
done

if [ "$REPLAY_READY" = true ]; then
    # Both committed fixtures. Exit 0 = PASS; 2 = DESYNC, 3 = FAULT, 4 = TIMEOUT,
    # 1 = refusal (release ROM / mismatched .lst / unresolved symbol).
    if "$REPLAY_RUNNER" --rom "$REPLAY_ROM" --lst "$REPLAY_LST" --fixture ojz_fixture; then
        pass_test "Replay net: ojz_fixture"
    else
        fail_test "Replay net: ojz_fixture"
    fi

    if "$REPLAY_RUNNER" --rom "$REPLAY_ROM" --lst "$REPLAY_LST" --fixture ojz_slide_fixture; then
        pass_test "Replay net: ojz_slide_fixture"
    else
        fail_test "Replay net: ojz_slide_fixture"
    fi

    # The negative control is NOT optional: a gate you have never seen fail is
    # not a gate. It plants $DEADBEEF over the first checkpoint and REQUIRES the
    # desync trap to fire — exit 5 means the compare is inverted/dead and the two
    # passes above prove nothing.
    if "$REPLAY_RUNNER" --rom "$REPLAY_ROM" --lst "$REPLAY_LST" --negative-control; then
        pass_test "Replay net: negative control (desync trap fires)"
    else
        fail_test "Replay net: negative control did NOT trip — the gate is inverted"
    fi
else
    fail_test "Replay net: ojz_fixture — NOT RUN (inputs above are missing)"
    fail_test "Replay net: ojz_slide_fixture — NOT RUN (inputs above are missing)"
    fail_test "Replay net: negative control — NOT RUN (inputs above are missing)"
fi

# -----------------------------------------------
section "RESULTS"
# -----------------------------------------------
echo ""
echo "${PASSED}/${TOTAL} passed, ${FAILED} failed"
if [ "$FAILED" -gt 0 ]; then
    echo "SOME TESTS FAILED"
    exit 1
else
    echo "ALL TESTS PASSED"
fi
