; ======================================================================
; engine/sound_tables_z80.asm — GENERATED by tools/gen_sound_tables.py
; DO NOT EDIT BY HAND. Regenerate: python3 tools/gen_sound_tables.py
;
; Z80-SYNTAX INLINE copies of the FM tables, included INSIDE the phase-0
; Z80 blob so the FM voice writer (engine/sound_fm.asm) reads them with
; direct Z80 addressing (no $8000-window banking). Identical VALUES to the
; 68k ROM tables in data/sound/sound_tables.asm.
; ======================================================================

FmPitchTableZ:
        dw      0284h, 02AAh, 02D3h, 02FEh, 032Bh, 035Bh, 038Eh, 03C5h
        dw      03FEh, 043Bh, 047Bh, 04BFh, 0508h, 0554h, 05A5h, 05FBh
        dw      0656h, 06B7h, 071Dh, 0789h, 07FCh, 0C3Bh, 0C7Bh, 0CBFh
        dw      0D08h, 0D54h, 0DA5h, 0DFBh, 0E56h, 0EB7h, 0F1Dh, 0F89h
        dw      0FFCh, 143Bh, 147Bh, 14BFh, 1508h, 1554h, 15A5h, 15FBh
        dw      1656h, 16B7h, 171Dh, 1789h, 17FCh, 1C3Bh, 1C7Bh, 1CBFh
        dw      1D08h, 1D54h, 1DA5h, 1DFBh, 1E56h, 1EB7h, 1F1Dh, 1F89h
        dw      1FFCh, 243Bh, 247Bh, 24BFh, 2508h, 2554h, 25A5h, 25FBh
        dw      2656h, 26B7h, 271Dh, 2789h, 27FCh, 2C3Bh, 2C7Bh, 2CBFh
        dw      2D08h, 2D54h, 2DA5h, 2DFBh, 2E56h, 2EB7h, 2F1Dh, 2F89h
        dw      2FFCh, 343Bh, 347Bh, 34BFh, 3508h, 3554h, 35A5h, 35FBh
        dw      3656h, 36B7h, 371Dh, 3789h, 37FCh, 3C3Bh, 3C7Bh
FmPitchTableZ_End:

PsgDivisorTableZ:
        dw      03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh
        dw      03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh
        dw      03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh
        dw      03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh
        dw      03FFh, 03F9h, 03C0h, 038Ah, 0357h, 0327h, 02FAh, 02CFh
        dw      02A7h, 0281h, 025Dh, 023Bh, 021Bh, 01FCh, 01E0h, 01C5h
        dw      01ACh, 0194h, 017Dh, 0168h, 0153h, 0140h, 012Eh, 011Dh
        dw      010Dh, 00FEh, 00F0h, 00E2h, 00D6h, 00CAh, 00BEh, 00B4h
        dw      00AAh, 00A0h, 0097h, 008Fh, 0087h, 007Fh, 0078h, 0071h
        dw      006Bh, 0065h, 005Fh, 005Ah, 0055h, 0050h, 004Ch, 0047h
        dw      0043h, 0040h, 003Ch, 0039h, 0035h, 0032h, 0030h, 002Dh
        dw      002Ah, 0028h, 0026h, 0024h, 0022h, 0020h, 001Eh
PsgDivisorTableZ_End:

LogVolumeLutZ:
        db      7Fh, 7Fh, 6Dh, 62h, 5Bh, 55h, 50h, 4Ch, 48h, 45h, 43h, 40h, 3Eh, 3Ch, 3Ah, 38h
        db      36h, 35h, 33h, 32h, 30h, 2Fh, 2Eh, 2Dh, 2Ch, 2Bh, 2Ah, 29h, 28h, 27h, 26h, 25h
        db      24h, 23h, 23h, 22h, 21h, 20h, 20h, 1Fh, 1Eh, 1Eh, 1Dh, 1Ch, 1Ch, 1Bh, 1Bh, 1Ah
        db      1Ah, 19h, 18h, 18h, 17h, 17h, 16h, 16h, 15h, 15h, 15h, 14h, 14h, 13h, 13h, 12h
        db      12h, 12h, 11h, 11h, 10h, 10h, 10h, 0Fh, 0Fh, 0Fh, 0Eh, 0Eh, 0Dh, 0Dh, 0Dh, 0Ch
        db      0Ch, 0Ch, 0Bh, 0Bh, 0Bh, 0Bh, 0Ah, 0Ah, 0Ah, 09h, 09h, 09h, 08h, 08h, 08h, 08h
        db      07h, 07h, 07h, 07h, 06h, 06h, 06h, 05h, 05h, 05h, 05h, 04h, 04h, 04h, 04h, 04h
        db      03h, 03h, 03h, 03h, 02h, 02h, 02h, 02h, 01h, 01h, 01h, 01h, 01h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
LogVolumeLutZ_End:

CarrierMaskTableZ:
        db      08h, 08h, 08h, 08h, 0Ch, 0Eh, 0Eh, 0Fh
CarrierMaskTableZ_End:

; --- PSG volume-envelope table (SFX Expressive Fidelity, spec section 4) ------
; S3K-EXACT VolEnv byte format: per-frame ATTENUATION deltas (added to the track
; atten; higher = quieter) + control bytes: 80h = loop cursor to 0; 81h = sustain-
; hold (hold last delta, do NOT silence); 83h = full rest (silence the channel).
; Engine env id is 1-based (matches smpsPSGvoice's sTone_XX); id N -> body N-1.
; (S3K's buggy 'relative-jump' path for other high-bit bytes is NOT replicated.)
PsgVolEnvCtl_Loop    = 80h
PsgVolEnvCtl_Sustain = 81h
PsgVolEnvCtl_Rest    = 83h

PsgVolEnv_Ids:    db 03h, 0Dh, 0Eh, 0Fh, 11h, 1Dh
PsgVolEnv_Ids_End:
; The bodies now live in the bank-aligned SoundTableBank block (main.asm), emitted
; under `phase 08000h` so every label here EQUALS its Z80 $8000-window pointer. Each
; dw therefore stores a window ptr, so the PsgVolEnv_Resolve dereference
; (ld e,(hl)/inc/ld d,(hl)) reads the body through the window.
PsgVolEnv_Ptrs:   dw PsgVolEnv_03, PsgVolEnv_0D, PsgVolEnv_0E, PsgVolEnv_0F, PsgVolEnv_11, PsgVolEnv_1D
PsgVolEnv_Ptrs_End:

PSGVOLENV_COUNT = PsgVolEnv_Ids_End - PsgVolEnv_Ids
        if (PsgVolEnv_Ptrs_End - PsgVolEnv_Ptrs) <> PSGVOLENV_COUNT*2
          error "PsgVolEnv_Ptrs entry count mismatch vs PsgVolEnv_Ids"
        endif

PsgVolEnv_03:   db 02h, 01h, 00h, 00h, 01h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 03h, 03h, 03h, 04h, 04h, 04h, 05h, PsgVolEnvCtl_Sustain   ; sTone_03 (S3K VolEnv_02)
PsgVolEnv_0D:   db 00h, PsgVolEnvCtl_Sustain   ; sTone_0D (S3K VolEnv_0C)
PsgVolEnv_0E:   db 02h, PsgVolEnvCtl_Rest   ; sTone_0E (S3K VolEnv_0D)
PsgVolEnv_0F:   db 00h, 02h, 04h, 06h, 08h, 10h, PsgVolEnvCtl_Rest   ; sTone_0F (S3K VolEnv_0E)
PsgVolEnv_11:   db 01h, 01h, 01h, 00h, 00h, 00h, PsgVolEnvCtl_Sustain   ; sTone_11 (S3K VolEnv_10)
PsgVolEnv_1D:   db 00h, 00h, 00h, 00h, 01h, 01h, 01h, 01h, 02h, 02h, 02h, 02h, 03h, 03h, 03h, 03h, 04h, 04h, 04h, 04h, 05h, 05h, 05h, 05h, 06h, 06h, 06h, 06h, 07h, 07h, 07h, 07h, 08h, 08h, 08h, 08h, 09h, 09h, 09h, 09h, 0Ah, 0Ah, 0Ah, 0Ah, PsgVolEnvCtl_Sustain   ; sTone_1D (S3K VolEnv_1C)
