; ======================================================================
; engine/sound_tables_z80.asm — GENERATED by tools/gen_sound_tables.py
; DO NOT EDIT BY HAND. Regenerate: python3 tools/gen_sound_tables.py
;
; Z80-SYNTAX INLINE copies of the FM tables, included INSIDE the phase-0
; Z80 blob so the FM voice writer (engine/sound_fm.asm) reads them with
; direct Z80 addressing (no $8000-window banking). Identical VALUES to the
; 68k ROM tables in data/sound/sound_tables.asm.
; ======================================================================

FmPitchTableZ:
        dw      0284h, 02AAh, 02D3h, 02FEh, 032Bh, 035Bh, 038Eh, 03C5h
        dw      03FEh, 043Bh, 047Bh, 04BFh, 0508h, 0554h, 05A5h, 05FBh
        dw      0656h, 06B7h, 071Dh, 0789h, 07FCh, 0C3Bh, 0C7Bh, 0CBFh
        dw      0D08h, 0D54h, 0DA5h, 0DFBh, 0E56h, 0EB7h, 0F1Dh, 0F89h
        dw      0FFCh, 143Bh, 147Bh, 14BFh, 1508h, 1554h, 15A5h, 15FBh
        dw      1656h, 16B7h, 171Dh, 1789h, 17FCh, 1C3Bh, 1C7Bh, 1CBFh
        dw      1D08h, 1D54h, 1DA5h, 1DFBh, 1E56h, 1EB7h, 1F1Dh, 1F89h
        dw      1FFCh, 243Bh, 247Bh, 24BFh, 2508h, 2554h, 25A5h, 25FBh
        dw      2656h, 26B7h, 271Dh, 2789h, 27FCh, 2C3Bh, 2C7Bh, 2CBFh
        dw      2D08h, 2D54h, 2DA5h, 2DFBh, 2E56h, 2EB7h, 2F1Dh, 2F89h
        dw      2FFCh, 343Bh, 347Bh, 34BFh, 3508h, 3554h, 35A5h, 35FBh
        dw      3656h, 36B7h, 371Dh, 3789h, 37FCh, 3C3Bh, 3C7Bh
FmPitchTableZ_End:

LogVolumeLutZ:
        db      7Fh, 7Fh, 6Dh, 62h, 5Bh, 55h, 50h, 4Ch, 48h, 45h, 43h, 40h, 3Eh, 3Ch, 3Ah, 38h
        db      36h, 35h, 33h, 32h, 30h, 2Fh, 2Eh, 2Dh, 2Ch, 2Bh, 2Ah, 29h, 28h, 27h, 26h, 25h
        db      24h, 23h, 23h, 22h, 21h, 20h, 20h, 1Fh, 1Eh, 1Eh, 1Dh, 1Ch, 1Ch, 1Bh, 1Bh, 1Ah
        db      1Ah, 19h, 18h, 18h, 17h, 17h, 16h, 16h, 15h, 15h, 15h, 14h, 14h, 13h, 13h, 12h
        db      12h, 12h, 11h, 11h, 10h, 10h, 10h, 0Fh, 0Fh, 0Fh, 0Eh, 0Eh, 0Dh, 0Dh, 0Dh, 0Ch
        db      0Ch, 0Ch, 0Bh, 0Bh, 0Bh, 0Bh, 0Ah, 0Ah, 0Ah, 09h, 09h, 09h, 08h, 08h, 08h, 08h
        db      07h, 07h, 07h, 07h, 06h, 06h, 06h, 05h, 05h, 05h, 05h, 04h, 04h, 04h, 04h, 04h
        db      03h, 03h, 03h, 03h, 02h, 02h, 02h, 02h, 01h, 01h, 01h, 01h, 01h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
LogVolumeLutZ_End:

CarrierMaskTableZ:
        db      08h, 08h, 08h, 08h, 0Ch, 0Eh, 0Eh, 0Fh
CarrierMaskTableZ_End:
