; ======================================================================
; engine/sound/sound_tables_z80.asm — GENERATED by tools/gen_sound_tables.py
; DO NOT EDIT BY HAND. Regenerate: python3 tools/gen_sound_tables.py
;
; Z80-SYNTAX INLINE copies of the FM tables, included INSIDE the phase-0
; Z80 blob so the FM voice writer (engine/sound/sound_fm.asm) reads them with
; direct Z80 addressing (no $8000-window banking). (The old 68k-side table
; emission was removed 2026-07-01; emit_asm() retains the values unemitted.)
; ======================================================================

FmPitchTableZ:
        dw      0284h, 02AAh, 02D3h, 02FEh, 032Bh, 035Bh, 038Eh, 03C5h
        dw      03FEh, 043Bh, 047Bh, 04BFh, 0A84h, 0AAAh, 0AD3h, 0AFEh
        dw      0B2Bh, 0B5Bh, 0B8Eh, 0BC5h, 0BFEh, 0C3Bh, 0C7Bh, 0CBFh
        dw      1284h, 12AAh, 12D3h, 12FEh, 132Bh, 135Bh, 138Eh, 13C5h
        dw      13FEh, 143Bh, 147Bh, 14BFh, 1A84h, 1AAAh, 1AD3h, 1AFEh
        dw      1B2Bh, 1B5Bh, 1B8Eh, 1BC5h, 1BFEh, 1C3Bh, 1C7Bh, 1CBFh
        dw      2284h, 22AAh, 22D3h, 22FEh, 232Bh, 235Bh, 238Eh, 23C5h
        dw      23FEh, 243Bh, 247Bh, 24BFh, 2A84h, 2AAAh, 2AD3h, 2AFEh
        dw      2B2Bh, 2B5Bh, 2B8Eh, 2BC5h, 2BFEh, 2C3Bh, 2C7Bh, 2CBFh
        dw      3284h, 32AAh, 32D3h, 32FEh, 332Bh, 335Bh, 338Eh, 33C5h
        dw      33FEh, 343Bh, 347Bh, 34BFh, 3A84h, 3AAAh, 3AD3h, 3AFEh
        dw      3B2Bh, 3B5Bh, 3B8Eh, 3BC5h, 3BFEh, 3C3Bh, 3C7Bh
FmPitchTableZ_End:

PsgDivisorTableZ:
        dw      03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh, 03FFh
        dw      03FFh, 03F7h, 03BEh, 0388h, 0356h, 0326h, 02F9h, 02CEh
        dw      02A5h, 0280h, 025Ch, 023Ah, 021Ah, 01FBh, 01DFh, 01C4h
        dw      01ABh, 0193h, 017Dh, 0167h, 0153h, 0140h, 012Eh, 011Dh
        dw      010Dh, 00FEh, 00EFh, 00E2h, 00D6h, 00C9h, 00BEh, 00B4h
        dw      00A9h, 00A0h, 0097h, 008Fh, 0087h, 007Fh, 0078h, 0071h
        dw      006Bh, 0065h, 005Fh, 005Ah, 0055h, 0050h, 004Bh, 0047h
        dw      0043h, 0040h, 003Ch, 0039h, 0036h, 0033h, 0030h, 002Dh
        dw      002Bh, 0028h, 0026h, 0024h, 0022h, 0020h, 001Fh, 001Dh
        dw      001Bh, 001Ah, 0018h, 0017h, 0016h, 0015h, 0013h, 0012h
        dw      0011h, 0010h, 0001h, 0001h, 0001h, 0001h, 0001h, 0001h
        dw      0001h, 0001h, 0001h, 0001h, 0001h, 0001h, 0001h
PsgDivisorTableZ_End:

LogVolumeLutZ:
        db      7Fh, 7Fh, 6Dh, 62h, 5Bh, 55h, 50h, 4Ch, 48h, 45h, 43h, 40h, 3Eh, 3Ch, 3Ah, 38h
        db      36h, 35h, 33h, 32h, 30h, 2Fh, 2Eh, 2Dh, 2Ch, 2Bh, 2Ah, 29h, 28h, 27h, 26h, 25h
        db      24h, 23h, 23h, 22h, 21h, 20h, 20h, 1Fh, 1Eh, 1Eh, 1Dh, 1Ch, 1Ch, 1Bh, 1Bh, 1Ah
        db      1Ah, 19h, 18h, 18h, 17h, 17h, 16h, 16h, 15h, 15h, 15h, 14h, 14h, 13h, 13h, 12h
        db      12h, 12h, 11h, 11h, 10h, 10h, 10h, 0Fh, 0Fh, 0Fh, 0Eh, 0Eh, 0Dh, 0Dh, 0Dh, 0Ch
        db      0Ch, 0Ch, 0Bh, 0Bh, 0Bh, 0Bh, 0Ah, 0Ah, 0Ah, 09h, 09h, 09h, 08h, 08h, 08h, 08h
        db      07h, 07h, 07h, 07h, 06h, 06h, 06h, 05h, 05h, 05h, 05h, 04h, 04h, 04h, 04h, 04h
        db      03h, 03h, 03h, 03h, 02h, 02h, 02h, 02h, 01h, 01h, 01h, 01h, 01h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db      00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
LogVolumeLutZ_End:

CarrierMaskTableZ:
        db      08h, 08h, 08h, 08h, 0Ch, 0Eh, 0Eh, 0Fh
CarrierMaskTableZ_End:

; --- PSG volume-envelope table (SFX Expressive Fidelity, spec section 4) ------
; S3K-EXACT VolEnv byte format: per-frame ATTENUATION deltas (added to the track
; atten; higher = quieter) + control bytes: 80h = loop cursor to 0; 81h = sustain-
; hold (hold last delta, do NOT silence); 83h = full rest (silence the channel).
; Engine env id is 1-based (matches smpsPSGvoice's sTone_XX); id N -> body N-1.
; (S3K's buggy 'relative-jump' path for other high-bit bytes is NOT replicated.)
PsgVolEnvCtl_Loop    = 80h
PsgVolEnvCtl_Sustain = 81h
PsgVolEnvCtl_Rest    = 83h

PsgVolEnv_Ids:    db 01h, 02h, 03h, 08h, 0Ah, 0Ch, 0Dh, 0Eh, 0Fh, 11h, 1Dh
PsgVolEnv_Ids_End:
PsgVolEnv_Ptrs:   dw PsgVolEnv_01, PsgVolEnv_02, PsgVolEnv_03, PsgVolEnv_08, PsgVolEnv_0A, PsgVolEnv_0C, PsgVolEnv_0D, PsgVolEnv_0E, PsgVolEnv_0F, PsgVolEnv_11, PsgVolEnv_1D
PsgVolEnv_Ptrs_End:

PSGVOLENV_COUNT = PsgVolEnv_Ids_End - PsgVolEnv_Ids
        if (PsgVolEnv_Ptrs_End - PsgVolEnv_Ptrs) <> PSGVOLENV_COUNT*2
          error "PsgVolEnv_Ptrs entry count mismatch vs PsgVolEnv_Ids"
        endif

PsgVolEnv_01:   db 02h, PsgVolEnvCtl_Rest   ; sTone_01 (S3K VolEnv_00)
PsgVolEnv_02:   db 00h, 02h, 04h, 06h, 08h, 10h, PsgVolEnvCtl_Rest   ; sTone_02 (S3K VolEnv_01)
PsgVolEnv_03:   db 02h, 01h, 00h, 00h, 01h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 02h, 03h, 03h, 03h, 04h, 04h, 04h, 05h, PsgVolEnvCtl_Sustain   ; sTone_03 (S3K VolEnv_02)
PsgVolEnv_08:   db 00h, 00h, 00h, 02h, 03h, 03h, 04h, 05h, 06h, 07h, 08h, 09h, 0Ah, 0Bh, 0Eh, 0Fh, PsgVolEnvCtl_Rest   ; sTone_08 (S3K VolEnv_07)
PsgVolEnv_0A:   db 01h, 00h, 00h, 00h, 00h, 01h, 01h, 01h, 02h, 02h, 02h, 03h, 03h, 03h, 03h, 04h, 04h, 04h, 05h, 05h, PsgVolEnvCtl_Sustain   ; sTone_0A (S3K VolEnv_09)
PsgVolEnv_0C:   db 00h, 00h, 01h, 01h, 03h, 03h, 04h, 05h, PsgVolEnvCtl_Rest   ; sTone_0C (S3K VolEnv_0B)
PsgVolEnv_0D:   db 00h, PsgVolEnvCtl_Sustain   ; sTone_0D (S3K VolEnv_0C)
PsgVolEnv_0E:   db 02h, PsgVolEnvCtl_Rest   ; sTone_0E (S3K VolEnv_0D)
PsgVolEnv_0F:   db 00h, 02h, 04h, 06h, 08h, 10h, PsgVolEnvCtl_Rest   ; sTone_0F (S3K VolEnv_0E)
PsgVolEnv_11:   db 01h, 01h, 01h, 00h, 00h, 00h, PsgVolEnvCtl_Sustain   ; sTone_11 (S3K VolEnv_10)
PsgVolEnv_1D:   db 00h, 00h, 00h, 00h, 01h, 01h, 01h, 01h, 02h, 02h, 02h, 02h, 03h, 03h, 03h, 03h, 04h, 04h, 04h, 04h, 05h, 05h, 05h, 05h, 06h, 06h, 06h, 06h, 07h, 07h, 07h, 07h, 08h, 08h, 08h, 08h, 09h, 09h, 09h, 09h, 0Ah, 0Ah, 0Ah, 0Ah, PsgVolEnvCtl_Sustain   ; sTone_1D (S3K VolEnv_1C)

; --- FM TL volume-envelope table (spec section 4 flagship) -------------------
; Same format as the PSG vol-env (atten deltas + 80h/81h/83h ctl), but the
; renderer (FmEnvUpdate) folds the delta into the CARRIER TLs (Fm_SetVolume).
; FM rest (83h) = TL-silence (the YM EG release continues), not a key-off.
FmVolEnvCtl_Loop    = 80h
FmVolEnvCtl_Sustain = 81h
FmVolEnvCtl_Rest    = 83h

FmVolEnv_Ids:    db 01h, 02h, 03h
FmVolEnv_Ids_End:
FmVolEnv_Ptrs:   dw FmVolEnv_01, FmVolEnv_02, FmVolEnv_03
FmVolEnv_Ptrs_End:

FMVOLENV_COUNT = FmVolEnv_Ids_End - FmVolEnv_Ids
        if (FmVolEnv_Ptrs_End - FmVolEnv_Ptrs) <> FMVOLENV_COUNT*2
          error "FmVolEnv_Ptrs entry count mismatch vs FmVolEnv_Ids"
        endif

FmVolEnv_01:   db 20h, 18h, 12h, 0Ch, 08h, 05h, 02h, 00h, FmVolEnvCtl_Sustain   ; fmEnv_swell
FmVolEnv_02:   db 00h, 02h, 04h, 06h, 08h, 0Ch, 10h, 18h, FmVolEnvCtl_Sustain   ; fmEnv_decay
FmVolEnv_03:   db 00h, 02h, 04h, 06h, 04h, 02h, FmVolEnvCtl_Loop   ; fmEnv_trem
