; OJZ Act 1 level descriptor and section tables (§4 Phase 1, §2 A.3)
; Act/Sec structs + the descriptor literal are authored in act_descriptor.emp
; (engine.structs twins). Generated data in data/generated/ojz/act1/ (gitignored).

; Act-wide paged art pool (auto-generated by tools/ojz_strip_gen.py + build.sh)
; Pool: OJZ_Act_Pool_Page0..N + OJZ_Act_Pool_PageTable (dc.l page addresses).
; The manifest (OJZ_ACT_POOL_PAGES/TILES + per-page SLOT/TILES) and the per-section
; block-dict lengths (OJZ_SEC*_BLOCK_DICT_LEN) are generated `.emp` const modules
; (ojz_act_pool_manifest.emp / sec_block_dicts.emp) consumed at comptime by
; act_descriptor.emp; the pool-tile ceiling guard is a comptime `ensure` there now
; (Parcel K3).
    include "games/sonic4/data/generated/ojz/act1/ojz_act_pool.asm"
; -----------------------------------------------
; OJZ Act 1 — descriptor and section table
; -----------------------------------------------
; OJZ_Act1_Descriptor + OJZ_Act1_Sections are authored in act_descriptor.emp
; (same dir): the typed `Act` / `[Sec; 9]` literal, with the grid-capacity and
; signed-word axis-clamp guards as comptime `ensure`s. sigil pins the block by
; the map at the per-shape reference address.
;
; Parcel K3 run B: the block blobs, the palette/BG BINCLUDEs, and the bg_anim
; stub that used to follow the descriptor here are now natively-placed `.emp`
; sections — sec_block_blobs.emp (games.sonic4.ojz_sec_block_blobs_act1),
; act_assets.emp (games.sonic4.ojz_act_assets_act1: OJZ_Palette / BGND_Palette /
; OJZ_Act1_BG_Layout / OJZ_Act1_BG_Tiles), and bg_anim.emp
; (games.sonic4.ojz_bg_anim_act1). The descriptor's org-resume died with them.
;
; What remains AS-side is the art-pool include above (#30, run A) — it dissolves
; in K3 run A (with entity_data.asm), which also deletes this wrapper.
