; OJZ Act 1 level descriptor and section tables (§4 Phase 1, §2 A.3)
; Act/Sec structs + the descriptor literal are authored in act_descriptor.emp
; (engine.structs twins). Generated data in data/generated/ojz/act1/ (gitignored).

; Act-wide paged art pool (auto-generated by tools/ojz_strip_gen.py + build.sh)
; Manifest: OJZ_ACT_POOL_PAGES / OJZ_ACT_POOL_TILES + per-page SLOT/TILES equates.
; Pool: OJZ_Act_Pool_Page0..N + OJZ_Act_Pool_PageTable (dc.l page addresses).
    include "games/sonic4/data/generated/ojz/act1/ojz_act_pool_manifest.asm"
    include "games/sonic4/data/generated/ojz/act1/ojz_act_pool.asm"
; Build assert: the page loader DMAs the pool to VRAM tiles 0..N-1 with no
; runtime bounds check — a pool past POOL_TILE_CEILING (960) would overwrite
; the character DPLC region (mirrors the ojz_strip_gen.py generate-time guard).
    if OJZ_ACT_POOL_TILES > POOL_TILE_CEILING
      error "OJZ act 1 art pool exceeds POOL_TILE_CEILING — would DMA over the character region at tile 960"
    endif

; Per-section block dictionary lengths (auto-generated by tools/ojz_block_gen.py)
; Dict region = K raw 768-byte blocks at SecN_Blocks + BLOCK_INDEX_SIZE.
    include "games/sonic4/data/generated/ojz/act1/sec_block_dicts.asm"

; -----------------------------------------------
; OJZ Act 1 — descriptor and section table
; -----------------------------------------------
; OJZ_Act1_Descriptor + OJZ_Act1_Sections are authored in act_descriptor.emp
; (same dir): the typed `Act` / `[Sec; 9]` literal, with the grid-capacity and
; signed-word axis-clamp guards as comptime `ensure`s. sigil pins the block by
; the map at the per-shape reference address; the org below resumes placement
; for the generated block data / palettes / BG that follow (sonic4-shape
; addresses — the generated includes above and the data below stay AS-side).
  ifdef __DEBUG__
    org     $14E06
  else
    org     $14D9E
  endif
; -----------------------------------------------
; Generated block data — 16×16 blocks, S4LZ compressed (§4.7 2D)
; OJZ_Sec{N}_Blocks labels live in the generated include: identical blobs
; are stored once and duplicate sections alias via equ (content dedup).
; -----------------------------------------------
    include "games/sonic4/data/generated/ojz/act1/sec_block_blobs.asm"

OJZ_Palette: BINCLUDE "games/sonic4/data/generated/ojz/act1/ojz_palette.bin"
    align 2

; Shared/HUD palette (CRAM line 0) — sonic_hack convention for level rendering.
BGND_Palette: BINCLUDE "art/palettes/SonicAndTails.bin"
    align 2

; Zone-wide BG layout + shared BG tile blob (§2 A.5 T1)
OJZ_Act1_BG_Layout: BINCLUDE "games/sonic4/data/generated/ojz/act1/zone_bg.bin"
    align 2
OJZ_Act1_BG_Tiles:  BINCLUDE "games/sonic4/data/generated/ojz/act1/bg_tiles.bin"
    align 2

; Camera-driven BG tile animation banks (generated; TileCount=0 stub when none)
    include "games/sonic4/data/generated/ojz/act1/bg_anim.asm"
    align 2

; Per-section tile blobs removed: the act-wide
; paged art pool (OJZ_Act_Pool_Page* / OJZ_Act_Pool_PageTable) is now included
; at the top of this file via ojz_act_pool.asm.
