; ======================================================================
; data/sound/sfx/sfx_33.asm — GENERATED by tools/sfx_transcode.py
; SFX id $33 (Sfx_33)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_33:
    dc.b   $20, $00, $01, $00, $03, $01, $00, $0A, $00, $16, $E4, $40, $E3, $40, $05, $E3
    dc.b   $43, $05, $E3, $48, $1B, $FF, $04, $C0, $37, $77, $72, $49, $23, $23, $05, $05
    dc.b   $1F, $1F, $1F, $1F, $07, $07, $0A, $0D, $00, $00, $0B, $0B, $1F, $1F, $0F, $0F
    dc.b   $00, $00, $00, $00, $00, $00
Sfx_33_End:

    align 2
