; ======================================================================
; data/sound/sfx/sfx_62.asm — GENERATED by tools/sfx_transcode.py
; SFX id $62 (Sfx_62)
; Layout: SfxHeader(8) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_62:
    dc.b   $40, $00, $01, $00, $00, $01, $00, $00, $06, $02, $00, $0E, $00, $00, $E0, $50
    dc.b   $EB, $0D, $E3, $1D, $05, $EC, $02, $01, $F8, $65, $E3, $22, $15, $FF
Sfx_62_End:

    align 2
