; ======================================================================
; data/sound/sfx/sfx_36.asm — GENERATED by tools/sfx_transcode.py
; SFX id $36 (Sfx_36)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_36:
    dc.b   $60, $04, $02, $00, $00, $01, $00, $00, $07, $02, $00, $14, $00, $00, $06, $02
    dc.b   $00, $29, $00, $00, $E0, $50, $EB, $0D, $E3, $2E, $01, $01, $80, $AF, $03, $80
    dc.b   $E5, $E3, $2E, $01, $01, $80, $E6, $0B, $FF, $E0, $50, $01, $80, $FF
Sfx_36_End:

    align 2
