; ======================================================================
; data/sound/sfx/sfx_62_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $62: no FM voices (PSG-only SFX)
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_62_Patches:
Sfx_62_Patches_End:

    align 2
