; ======================================================================
; data/sound/sfx/sfx_b6.asm — GENERATED by tools/sfx_transcode.py
; SFX id $B6 (Sfx_B6)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_B6:
    dc.b   $80, $00, $02, $00, $04, $01, $00, $10, $00, $23, $09, $03, $00, $19, $00, $00
    dc.b   $EC, $01, $01, $C5, $1A, $E3, $4C, $0F, $FF, $E0, $50, $EB, $1D, $06, $80, $E3
    dc.b   $06, $4F, $FF, $3D, $C0, $09, $00, $03, $00, $09, $18, $0A, $14, $1F, $1F, $1F
    dc.b   $1F, $10, $0C, $0C, $0C, $0B, $10, $1F, $05, $1F, $4F, $2F, $2F, $00, $00, $00
    dc.b   $00, $00, $00
Sfx_B6_End:

    align 2
