; ======================================================================
; data/sound/hcz2_patches.asm — GENERATED by tools/smps_import.py — DO NOT EDIT.
;
; HCZ2 FmPatch table: the 4 S3K Universal Voice Bank voices HCZ2 plays
; (in-body smpsSetvoice ids $03, $06, $0E, $15), translated to our 26-byte FmPatch via the
; verified SFX voice converter (smps_voice_to_fmpatch). The song's Patch
; events were remapped to dense 0-based indices via patch_remap.
;
; Record: fp_alg_fb=$B0, fp_lr_ams_fms=$B4, then 6 four-byte per-op arrays
; for regs $30/$40/$50/$60/$70/$80, array index 0..3 = PHYSICAL operators
; S1,S3,S2,S4 (S3K binary order reordered via _s3k_op_reorder).
; ======================================================================

HCZ2_Patches:
        dc.b    $34, $C0, $70, $31, $72, $31, $10, $18, $03, $03, $1F, $1F, $1F, $1F, $10, $06, $06, $06, $01, $06, $06, $06, $35, $15, $1A, $1A  ; [0] S3K voice $03
        dc.b    $3A, $C0, $01, $31, $07, $71, $18, $27, $28, $00, $8E, $8D, $8E, $53, $0E, $0E, $0E, $03, $00, $00, $00, $07, $1F, $1F, $FF, $0F  ; [1] S3K voice $06
        dc.b    $3A, $C0, $31, $73, $25, $41, $29, $1F, $27, $00, $5F, $1F, $1F, $9C, $08, $04, $05, $05, $03, $02, $04, $02, $2F, $1F, $2F, $2F  ; [2] S3K voice $0E
        dc.b    $28, $C0, $71, $30, $00, $01, $0E, $1E, $14, $00, $1F, $1D, $1F, $1F, $13, $06, $13, $05, $03, $02, $03, $05, $4F, $2F, $4F, $3F  ; [3] S3K voice $15
HCZ2_Patches_End:

        if (HCZ2_Patches_End-HCZ2_Patches) <> 4*FmPatch_len
          error "HCZ2_Patches size mismatch (expected 4 voices * 26 bytes)"
        endif

