; ======================================================================
; data/sound/movingtrucks_patches.asm — GENERATED by tools/zyrinx_port.py — DO NOT EDIT.
;
; Per-song FmPatch bank for "Moving Trucks" (Zyrinx Bank2 voices @
; ROM $1F49A8, translated to our 26-byte FmPatch by translate_voice()).
; The song's
; VOICE events were remapped to DENSE local indices 0..24; the FM writer
; reads a record via Fm_PatchLoad at SND_SEQ_PATCHTAB + local_idx*26.
;
; SINGLE SOURCE / DUAL-INCLUDABLE: emitted through the `pbyte` macro (picks
; dc.b for 68k ROM vs db for the Z80 phase-0 blob), so this one file can be
; included in the ROM data area OR inline in the Z80 blob with no drift.
; The recommended placement (T5) is INLINE in the Z80 blob: the bank is
; 25 records * 26 bytes = 650 bytes, always Z80-addressable (no $8000 banking).
;
; Record: fp_alg_fb=$B0, fp_lr_ams_fms=$B4, then 6 four-byte per-op arrays
; for regs $30/$40/$50/$60/$70/$80, array index 0..3 = PHYSICAL operators
; S1,S3,S2,S4 (Zyrinx natural op order reordered via OP_REORDER=[0,2,1,3]).
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

PATCH_COUNT_MT = 25

MovingTrucks_Patches:
; --- local 0 (Zyrinx voice 206) ---
        pbyte   55                      ; fp_alg_fb     $37
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte    36,  36,  20, 104   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     4,   1,   3,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    13,  11,  13,  11   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  31,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 1 (Zyrinx voice 198) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   224                     ; fp_lr_ams_fms $E0
        pbyte     0,   2,   2,   6   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   7,   0,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    95,  95,  95,  95   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    25,   0,  29,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  24,   8,   8   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 2 (Zyrinx voice 151) ---
        pbyte   45                      ; fp_alg_fb     $2D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     8,  12,   8,  12   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    12,  12,   9,  27   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    29,  31,  24,  27   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     8,   0,   1,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    19,  20,  19,  26   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56,  79,  73,  63   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 3 (Zyrinx voice 199) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   224                     ; fp_lr_ams_fms $E0
        pbyte     2,   2,   2,   6   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   8,   0,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    95,  95,  95,  95   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    25,   0,  29,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  24,   8,   8   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 4 (Zyrinx voice 200) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   224                     ; fp_lr_ams_fms $E0
        pbyte     2,   2,   2,   6   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  10,   0,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    95,  95,  95,  95   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    25,   0,  29,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  24,   8,   8   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 5 (Zyrinx voice 201) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   224                     ; fp_lr_ams_fms $E0
        pbyte     2,   2,   2,   6   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  11,   0,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    95,  95,  95,  95   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    25,   0,  29,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  24,   8,   8   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 6 (Zyrinx voice 202) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   224                     ; fp_lr_ams_fms $E0
        pbyte     2,   2,   2,   6   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  13,   0,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    95,  95,  95,  95   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    25,   0,  29,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  24,   8,   8   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 7 (Zyrinx voice 203) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   224                     ; fp_lr_ams_fms $E0
        pbyte     2,   2,   2,   6   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  17,   0,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    95,  95,  95,  95   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    26,   0,  29,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  24,   8,   8   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 8 (Zyrinx voice 194) ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   226                     ; fp_lr_ams_fms $E2
        pbyte     8,   6,   8,  38   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    27,  17,   3,  11   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    21,   2,  17,   4   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     9,   5,   3,   8   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     2,  83,  67,   3   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 9 (Zyrinx voice 207) ---
        pbyte   53                      ; fp_alg_fb     $35
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     2,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15, 191,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 10 (Zyrinx voice 208) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     2,   0,   0,   1   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15, 191,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 11 (Zyrinx voice 209) ---
        pbyte   53                      ; fp_alg_fb     $35
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     2,   0,   0,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15, 191,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 12 (Zyrinx voice 211) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   240                     ; fp_lr_ams_fms $F0
        pbyte     0,   0,   0,   4   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     1,   5,  16,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15, 207,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 13 (Zyrinx voice 212) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   5   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15, 191,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 14 (Zyrinx voice 210) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   3   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15, 191,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 15 (Zyrinx voice 142) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   193                     ; fp_lr_ams_fms $C1
        pbyte     7,   7,   8,   4   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    13,  97,   7,  17   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    27,  31,  24,  27   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     9,  14,  11,   5   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    21,  20,  20,  21   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   105,  25,  73,  73   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 16 (Zyrinx voice 197) ---
        pbyte   60                      ; fp_alg_fb     $3C
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     3,   1,   7,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     3,   5,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    20,  16,  14,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    11,   5,   6,   9   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    95, 175, 159,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 17 (Zyrinx voice 205) ---
        pbyte   40                      ; fp_alg_fb     $28
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     8,   0,   4,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     3,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 18 (Zyrinx voice 108) ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127, 127, 127, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 19 (Zyrinx voice 10) ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     5,   0,   2,   1   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     9,   7,  22,   3   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    20,  16,  14,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    11,   5,   5,  10   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    95, 207, 143,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 20 (Zyrinx voice 122) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   229                     ; fp_lr_ams_fms $E5
        pbyte    50,  38,  68,  68   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127,   6, 127,  17   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   6,  14,   6   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     6,  38,   6,   6   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 21 (Zyrinx voice 120) ---
        pbyte   3                       ; fp_alg_fb     $03
        pbyte   199                     ; fp_lr_ams_fms $C7
        pbyte    40,   0,   4,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    55,  27,  27,   7   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   159,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    14,   9,  13,   9   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   208, 216, 208, 215   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 22 (Zyrinx voice 188) ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   212                     ; fp_lr_ams_fms $D4
        pbyte     8,   4,   8,  36   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    27,  26,  12,  17   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   149,   2,  17,   4   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     9,   5,   3,   8   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     2,  83,  67,   3   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 23 (Zyrinx voice 123) ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   246                     ; fp_lr_ams_fms $F6
        pbyte     8,   4,   8,  36   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    32,  25,  35,  17   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   149,   2,  17,   4   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     9,   5,   3,   8   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     2,  83,  67,   3   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 24 (Zyrinx voice 82) ---
        pbyte   54                      ; fp_alg_fb     $36
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     4,   4,  51,  69   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    12,  13,  23,  39   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     3,   3,   3,   3   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  13   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
MovingTrucks_Patches_End:

        if (MovingTrucks_Patches_End-MovingTrucks_Patches)/FmPatch_len <> PATCH_COUNT_MT
          error "Moving Trucks patch bank count mismatch"
        endif
        if (MovingTrucks_Patches_End-MovingTrucks_Patches) <> PATCH_COUNT_MT*FmPatch_len
          error "Moving Trucks patch bank size mismatch"
        endif

