; ======================================================================
; data/sound/movingtrucks_patches.asm — GENERATED by tools/vgm_to_song.py — DO NOT EDIT.
;
; Per-song FmPatch bank for "Moving Trucks", snapshotted directly from
; the original game's chip-register stream (the reference VGM) at each
; key-on and deduplicated. Each record is the EXACT YM2612 voice the
; original used. Operators are already in PHYSICAL register order
; S1,S3,S2,S4 (the VGM holds them that way), so no reorder is applied.
;
; Record: fp_alg_fb=$B0, fp_lr_ams_fms=$B4, then 6 four-byte per-op arrays
; for regs $30/$40/$50/$60/$70/$80. The FM writer reads a record via
; Fm_PatchLoad at SND_SEQ_PATCHTAB + local_idx*26.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

PATCH_COUNT_MT = 106

MovingTrucks_Patches:
; --- patch 0 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    43,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 1 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    42,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 2 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    41,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 3 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    40,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 4 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    39,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 5 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    38,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 6 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    37,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 7 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    36,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 8 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    35,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 9 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    34,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 10 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    33,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 11 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    32,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 12 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    31,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 13 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    30,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 14 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    31,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 15 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    32,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 16 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    33,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 17 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    34,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 18 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    35,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 19 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    36,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 20 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    37,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 21 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    39,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 22 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    40,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 23 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    41,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 24 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    42,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 25 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    43,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 26 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    44,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 27 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    45,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 28 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    46,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 29 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    45,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 30 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    44,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 31 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     4,  18,   8,   7   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 32 ---
        pbyte   55                      ; fp_alg_fb     $37
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte    40,  32,  20, 100   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     4,  18,   8,   7   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136,   8, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 33 ---
        pbyte   55                      ; fp_alg_fb     $37
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte    40,  36,  24, 108   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     4,  18,   8,   7   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136,   8, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 34 ---
        pbyte   46                      ; fp_alg_fb     $2E
        pbyte   64                      ; fp_lr_ams_fms $40
        pbyte    25,   0,   0,   5   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   1, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  17,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  26,  22,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  12,  18,  11   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    31, 107,   7,   7   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 35 ---
        pbyte   46                      ; fp_alg_fb     $2E
        pbyte   128                     ; fp_lr_ams_fms $80
        pbyte    25,   0,   0,   5   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   1, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  17,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  26,  22,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  12,  18,  11   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    31, 107,   7,   7   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 36 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    30,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 37 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    31,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 38 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    32,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 39 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    33,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 40 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    34,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 41 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    35,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 42 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    36,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 43 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    37,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 44 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    38,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 45 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    39,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 46 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    40,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 47 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    41,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 48 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    42,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 49 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    43,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 50 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    44,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 51 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    45,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 52 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    46,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 53 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    45,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 54 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    44,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 55 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    43,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 56 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    42,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 57 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    41,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 58 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    40,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 59 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   80                      ; fp_lr_ams_fms $50
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    39,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 60 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    37,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 61 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    36,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 62 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    35,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 63 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    34,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 64 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    33,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 65 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    32,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 66 ---
        pbyte   58                      ; fp_alg_fb     $3A
        pbyte   144                     ; fp_lr_ams_fms $90
        pbyte   120,   4, 114, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    31,  19,  61,  13   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     2,   7,   6,   4   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    14,  14,  14,  14   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 67 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   128                     ; fp_lr_ams_fms $80
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  17,  37,  12   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 68 ---
        pbyte   40                      ; fp_alg_fb     $28
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     8,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   0,   7,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 69 ---
        pbyte   40                      ; fp_alg_fb     $28
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     8,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   0,   7,  10   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 70 ---
        pbyte   40                      ; fp_alg_fb     $28
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     8,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   0,   7,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 71 ---
        pbyte   51                      ; fp_alg_fb     $33
        pbyte   128                     ; fp_lr_ams_fms $80
        pbyte   116,   2, 116, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  17,  37,  12   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   151, 151, 151, 151   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   2,   2,   2   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 72 ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     7,   0,   5,   1   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     3,   7,  13,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    20,  16,  14,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     8,   5,   5,  10   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   127, 175, 159,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 73 ---
        pbyte   51                      ; fp_alg_fb     $33
        pbyte   64                      ; fp_lr_ams_fms $40
        pbyte   116,   2, 116, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  17,  37,  12   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   151, 151, 151, 151   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   2,   2,   2   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 74 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127, 127, 127, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 75 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 76 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     1,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 77 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     2,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 78 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     3,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 79 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     4,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 80 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     5,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 81 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     6,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 82 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     7,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 83 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     8,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 84 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     9,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  24,  18,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  17,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56, 184,  60,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 85 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    11,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 86 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    10,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 87 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     9,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 88 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     8,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 89 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     7,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 90 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     6,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 91 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     5,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 92 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     4,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 93 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     3,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 94 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     2,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 95 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     1,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 96 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 97 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 98 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    12,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 99 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    13,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 100 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    14,   1,   0,   1   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 101 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    15,   1,   0,  16   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 102 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   64                      ; fp_lr_ams_fms $40
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   1, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 103 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   128                     ; fp_lr_ams_fms $80
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   1,   1, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 104 ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     8,  12,   8,  12   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    13,  20,  14,  24   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    27,  31,  24,  27   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     9,  14,  11,   5   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,   8   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   101,  69,  53,   5   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- patch 105 ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    13,  20,  14,  24   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
MovingTrucks_Patches_End:

        if (MovingTrucks_Patches_End-MovingTrucks_Patches)/FmPatch_len <> PATCH_COUNT_MT
          error "Moving Trucks patch bank count mismatch"
        endif
        if (MovingTrucks_Patches_End-MovingTrucks_Patches) <> PATCH_COUNT_MT*FmPatch_len
          error "Moving Trucks patch bank size mismatch"
        endif

