; ======================================================================
; data/sound/movingtrucks_pitchtable.asm — GENERATED by
; tools/zyrinx_player.py (emit_pitchtable_asm) — DO NOT EDIT BY HAND.
; Regenerate: python3 tools/zyrinx_player.py --emit-pitchtable
;
; The exact Zyrinx "Moving Trucks" 132-entry chromatic fnum table
; (/tmp/zyrinx_re_timing_pitch.md §2.4). Z80-syntax, included INSIDE the
; phase-0 Z80 blob so Fm_NoteFromTable reads it with direct addressing.
;
; LAYOUT (sound_constants.asm PITCHTAB_*): TWO PARALLEL PAGES.
;   page 0  = A4 bytes (YM $A4 = (block<<3)|fnumHi), 132 entries
;   page 1  = A0 bytes (YM $A0 = fnum low),          132 entries
;   For note index i (0..$83):  $A4 = base[i], $A0 = base[132 + i].
;
; Index->note anchors (idx $24..$83 = a clean 6-octave chromatic run,
; block = (idx-$24)/12; idx $00..$23 are the sub-octaves, block 0, fnum>>):
;   idx $24 = C (block0, fnum1024) -> A4=$04 A0=$00
;   idx $28 = E (block0, fnum1290) -> A4=$05 A0=$0A
;   idx $2B = G (block0, fnum1534) -> A4=$05 A0=$FE
;   idx $30 = C (block1, fnum1024) -> A4=$0C A0=$00
;   idx $3C = C (block2, fnum1024) -> A4=$14 A0=$00
;   idx $48 = C (block3, fnum1024) -> A4=$1C A0=$00
; ======================================================================

MovingTrucks_PitchTable_Stream:
; --- page 0: A4 (block|fnumHi) bytes, idx $00..$83 ---
        dc.b    $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
        dc.b    $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01
        dc.b    $02, $02, $02, $02, $02, $02, $02, $02, $03, $03, $03, $03
        dc.b    $04, $04, $04, $04, $05, $05, $05, $05, $06, $06, $07, $07
        dc.b    $0C, $0C, $0C, $0C, $0D, $0D, $0D, $0D, $0E, $0E, $0F, $0F
        dc.b    $14, $14, $14, $14, $15, $15, $15, $15, $16, $16, $17, $17
        dc.b    $1C, $1C, $1C, $1C, $1D, $1D, $1D, $1D, $1E, $1E, $1F, $1F
        dc.b    $24, $24, $24, $24, $25, $25, $25, $25, $26, $26, $27, $27
        dc.b    $2C, $2C, $2C, $2C, $2D, $2D, $2D, $2D, $2E, $2E, $2F, $2F
        dc.b    $34, $34, $34, $34, $35, $35, $35, $35, $36, $36, $37, $37
        dc.b    $3C, $3C, $3C, $3C, $3D, $3D, $3D, $3D, $3E, $3E, $3F, $3F
; --- page 1: A0 (fnum low) bytes, idx $00..$83 ---
        dc.b    $80, $87, $8F, $98, $A1, $AA, $B5, $BF, $CB, $D7, $E4, $F1
        dc.b    $00, $0F, $1F, $30, $42, $55, $6A, $7F, $96, $AE, $C8, $E3
        dc.b    $00, $1E, $3E, $61, $85, $AB, $D4, $FF, $2C, $5D, $90, $C6
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
        dc.b    $00, $3D, $7D, $C2, $0A, $57, $A8, $FE, $59, $BA, $21, $8D
MovingTrucks_PitchTable_Stream_End:

