; ======================================================================
; data/sound/movingtrucks_pitchtable.asm — GENERATED by
; tools/zyrinx_player.py (emit_pitchtable_asm) — DO NOT EDIT BY HAND.
; Regenerate: python3 tools/zyrinx_player.py --emit-pitchtable
;
; The exact Zyrinx "Moving Trucks" 132-entry chromatic fnum table
; (/tmp/zyrinx_re_timing_pitch.md §2.4). Z80-syntax, included INSIDE the
; phase-0 Z80 blob so Fm_NoteFromTable reads it with direct addressing.
;
; LAYOUT (sound_constants.asm PITCHTAB_*): TWO PARALLEL PAGES.
;   page 0  = A4 bytes (YM $A4 = (block<<3)|fnumHi), 132 entries
;   page 1  = A0 bytes (YM $A0 = fnum low),          132 entries
;   For note index i (0..$83):  $A4 = base[i], $A0 = base[132 + i].
;
; Index->note anchors (idx $24..$83 = a clean 6-octave chromatic run,
; block = (idx-$24)/12; idx $00..$23 are the sub-octaves, block 0, fnum>>):
;   idx $24 = C (block0, fnum1024) -> A4=$04 A0=$00
;   idx $28 = E (block0, fnum1290) -> A4=$05 A0=$0A
;   idx $2B = G (block0, fnum1534) -> A4=$05 A0=$FE
;   idx $30 = C (block1, fnum1024) -> A4=$0C A0=$00
;   idx $3C = C (block2, fnum1024) -> A4=$14 A0=$00
;   idx $48 = C (block3, fnum1024) -> A4=$1C A0=$00
; ======================================================================

MovingTrucks_PitchTable:
; --- page 0: A4 (block|fnumHi) bytes, idx $00..$83 ---
        db      000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h, 000h
        db      001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h, 001h
        db      002h, 002h, 002h, 002h, 002h, 002h, 002h, 002h, 003h, 003h, 003h, 003h
        db      004h, 004h, 004h, 004h, 005h, 005h, 005h, 005h, 006h, 006h, 007h, 007h
        db      00Ch, 00Ch, 00Ch, 00Ch, 00Dh, 00Dh, 00Dh, 00Dh, 00Eh, 00Eh, 00Fh, 00Fh
        db      014h, 014h, 014h, 014h, 015h, 015h, 015h, 015h, 016h, 016h, 017h, 017h
        db      01Ch, 01Ch, 01Ch, 01Ch, 01Dh, 01Dh, 01Dh, 01Dh, 01Eh, 01Eh, 01Fh, 01Fh
        db      024h, 024h, 024h, 024h, 025h, 025h, 025h, 025h, 026h, 026h, 027h, 027h
        db      02Ch, 02Ch, 02Ch, 02Ch, 02Dh, 02Dh, 02Dh, 02Dh, 02Eh, 02Eh, 02Fh, 02Fh
        db      034h, 034h, 034h, 034h, 035h, 035h, 035h, 035h, 036h, 036h, 037h, 037h
        db      03Ch, 03Ch, 03Ch, 03Ch, 03Dh, 03Dh, 03Dh, 03Dh, 03Eh, 03Eh, 03Fh, 03Fh
; --- page 1: A0 (fnum low) bytes, idx $00..$83 ---
        db      080h, 087h, 08Fh, 098h, 0A1h, 0AAh, 0B5h, 0BFh, 0CBh, 0D7h, 0E4h, 0F1h
        db      000h, 00Fh, 01Fh, 030h, 042h, 055h, 06Ah, 07Fh, 096h, 0AEh, 0C8h, 0E3h
        db      000h, 01Eh, 03Eh, 061h, 085h, 0ABh, 0D4h, 0FFh, 02Ch, 05Dh, 090h, 0C6h
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
        db      000h, 03Dh, 07Dh, 0C2h, 00Ah, 057h, 0A8h, 0FEh, 059h, 0BAh, 021h, 08Dh
MovingTrucks_PitchTable_End:

