; ======================================================================
; data/sound/movingtrucks_patches.asm — GENERATED by tools/zyrinx_port.py — DO NOT EDIT.
;
; Per-song FmPatch bank for "Moving Trucks" (Zyrinx bank 1 voices,
; translated to our 26-byte FmPatch by translate_voice()). The song's
; VOICE events were remapped to DENSE local indices 0..32; the FM writer
; reads a record via Fm_PatchLoad at SND_SEQ_PATCHTAB + local_idx*26.
;
; SINGLE SOURCE / DUAL-INCLUDABLE: emitted through the `pbyte` macro (picks
; dc.b for 68k ROM vs db for the Z80 phase-0 blob), so this one file can be
; included in the ROM data area OR inline in the Z80 blob with no drift.
; The recommended placement (T5) is INLINE in the Z80 blob: the bank is
; 33 records * 26 bytes = 858 bytes, always Z80-addressable (no $8000 banking).
;
; Record: fp_alg_fb=$B0, fp_lr_ams_fms=$B4, then 6 four-byte per-op arrays
; for regs $30/$40/$50/$60/$70/$80, array index 0..3 = PHYSICAL operators
; S1,S3,S2,S4 (Zyrinx natural op order reordered via OP_REORDER=[0,2,1,3]).
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

PATCH_COUNT_MT = 33

MovingTrucks_Patches:
; --- local 0 (Zyrinx bank1 voice 14) ---
        pbyte   60                      ; fp_alg_fb     $3C
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     3,   7,   0,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   124, 127, 127, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    20,  14,  16,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    11,   6,   5,   9   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    95, 159, 175,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 1 (Zyrinx bank1 voice 164) ---
        pbyte   50                      ; fp_alg_fb     $32
        pbyte   199                     ; fp_lr_ams_fms $C7
        pbyte    52,  36,   4,   4   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   116, 126, 110, 125   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   159, 159, 148, 159   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  16,   8,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    10,   7, 122,   7   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 2 (Zyrinx bank1 voice 160) ---
        pbyte   42                      ; fp_alg_fb     $2A
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   120, 100, 110, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  18,  24,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56,  60, 184,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 3 (Zyrinx bank1 voice 0) ---
        pbyte   11                      ; fp_alg_fb     $0B
        pbyte   240                     ; fp_lr_ams_fms $F0
        pbyte   119,  72, 123, 127   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   103, 112,   0, 105   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    11,  11,   0,  12   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    16,  16,  16,  16   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     7,   7,  10,  58   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 4 (Zyrinx bank1 voice 161) ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   214                     ; fp_lr_ams_fms $D6
        pbyte     8,   8,   4,  36   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 112, 104, 112   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   149,  17,   2,   4   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     9,   3,   5,   8   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     2,  67,  83,   3   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 5 (Zyrinx bank1 voice 19) ---
        pbyte   55                      ; fp_alg_fb     $37
        pbyte   197                     ; fp_lr_ams_fms $C5
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   108,  66, 110, 108   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   134,  18,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   247, 120,   6,   9   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 6 (Zyrinx bank1 voice 21) ---
        pbyte   3                       ; fp_alg_fb     $03
        pbyte   199                     ; fp_lr_ams_fms $C7
        pbyte    40,   4,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    72,  96,  96, 126   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   159,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    14,  13,   9,   9   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   208, 208, 216, 215   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 7 (Zyrinx bank1 voice 20) ---
        pbyte   51                      ; fp_alg_fb     $33
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte    55,  53,  48,  49   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   124,  80, 127, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   223, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    20,  14,  16,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     8,   5,   5,  14   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    25,  73, 105,  11   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 8 (Zyrinx bank1 voice 3) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte   127,   0,  20,  16   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    80, 118, 127, 126   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   159,  31, 223, 159   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  29,  29,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    12,   0,   2,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     9,   6,   3,  10   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 9 (Zyrinx bank1 voice 7) ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   240                     ; fp_lr_ams_fms $F0
        pbyte     5,   9,  13,  15   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0, 110, 127, 120   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    31,  31,  31, 159   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    19,  18,   7,  19   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    63,  47,  31,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 10 (Zyrinx bank1 voice 28) ---
        pbyte   47                      ; fp_alg_fb     $2F
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     8,   4,   0,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   120, 127, 120, 126   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 11 (Zyrinx bank1 voice 30) ---
        pbyte   55                      ; fp_alg_fb     $37
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte    40,  24,  36, 108   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   123, 126, 123, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136,   8, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 12 (Zyrinx bank1 voice 27) ---
        pbyte   55                      ; fp_alg_fb     $37
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte    40,  24,  36, 108   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   124, 120, 110, 125   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136,   8, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 13 (Zyrinx bank1 voice 158) ---
        pbyte   42                      ; fp_alg_fb     $2A
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   114, 100, 110, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  18,  24,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56,  60, 184,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 14 (Zyrinx bank1 voice 174) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     8,   8,  12,  12   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   114, 110, 112,  90   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    29,  24,  31,  27   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     8,   1,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    19,  19,  20,  26   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   123,  77,  79,  63   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 15 (Zyrinx bank1 voice 156) ---
        pbyte   42                      ; fp_alg_fb     $2A
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 100, 110, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  18,  24,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56,  60, 184,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 16 (Zyrinx bank1 voice 157) ---
        pbyte   42                      ; fp_alg_fb     $2A
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   112, 100, 110, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  18,  24,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56,  60, 184,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 17 (Zyrinx bank1 voice 159) ---
        pbyte   42                      ; fp_alg_fb     $2A
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   116, 100, 110, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  18,  24,  25   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    56,  60, 184,  12   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 18 (Zyrinx bank1 voice 163) ---
        pbyte   2                       ; fp_alg_fb     $02
        pbyte   195                     ; fp_lr_ams_fms $C3
        pbyte     4,   2,   2,   4   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    70, 100, 100, 115   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    11,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    37,  34,  18,  18   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 19 (Zyrinx bank1 voice 110) ---
        pbyte   56                      ; fp_alg_fb     $38
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     8,   4,   0,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127, 127, 127, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31, 223, 223, 223   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 20 (Zyrinx bank1 voice 166) ---
        pbyte   50                      ; fp_alg_fb     $32
        pbyte   226                     ; fp_lr_ams_fms $E2
        pbyte   117,  24,  40, 100   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 110,  90, 118   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    23,  23,  23,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    19,  19,  19,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    12,  12,  12,  12   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    11,  11,  11,  11   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 21 (Zyrinx bank1 voice 167) ---
        pbyte   50                      ; fp_alg_fb     $32
        pbyte   226                     ; fp_lr_ams_fms $E2
        pbyte   119,  24,  40, 100   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 110,  90, 118   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    23,  23,  23,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    19,  19,  19,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    12,  12,  12,  12   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    11,  11,  11,  11   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 22 (Zyrinx bank1 voice 168) ---
        pbyte   50                      ; fp_alg_fb     $32
        pbyte   226                     ; fp_lr_ams_fms $E2
        pbyte   121,  24,  40, 100   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 110,  90, 118   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    23,  23,  23,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    19,  19,  19,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    12,  12,  12,  12   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    11,  11,  11,  11   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 23 (Zyrinx bank1 voice 169) ---
        pbyte   50                      ; fp_alg_fb     $32
        pbyte   226                     ; fp_lr_ams_fms $E2
        pbyte   123,  24,  40, 100   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 110,  90, 118   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    23,  23,  23,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    19,  19,  19,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    12,  12,  12,  12   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    11,  11,  11,  11   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 24 (Zyrinx bank1 voice 170) ---
        pbyte   50                      ; fp_alg_fb     $32
        pbyte   226                     ; fp_lr_ams_fms $E2
        pbyte   125,  23,  39, 106   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   110, 110,  90, 118   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    23,  23,  23,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    19,  19,  19,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    12,  12,  12,  12   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    11,  11,  11,  11   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 25 (Zyrinx bank1 voice 86) ---
        pbyte   57                      ; fp_alg_fb     $39
        pbyte   214                     ; fp_lr_ams_fms $D6
        pbyte   116, 116,  18,  84   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   122,  70, 100, 114   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   152, 212,  31, 154   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    17,  19,  19,  27   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   102,   6,   6,   6   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 26 (Zyrinx bank1 voice 162) ---
        pbyte   2                       ; fp_alg_fb     $02
        pbyte   198                     ; fp_lr_ams_fms $C6
        pbyte     4,   2,   2,   4   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    70, 100, 100, 115   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    11,  31,  31,  31   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    37,  34,  18,  18   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 27 (Zyrinx bank1 voice 113) ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   194                     ; fp_lr_ams_fms $C2
        pbyte     2,   0,   0,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127, 127, 127, 124   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte   136, 136, 136, 136   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte    47,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 28 (Zyrinx bank1 voice 171) ---
        pbyte   18                      ; fp_alg_fb     $12
        pbyte   196                     ; fp_lr_ams_fms $C4
        pbyte    15,  15,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   121,   0,   0, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  15,  24,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     8,  44, 184,  44   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 29 (Zyrinx bank1 voice 172) ---
        pbyte   18                      ; fp_alg_fb     $12
        pbyte   196                     ; fp_lr_ams_fms $C4
        pbyte    15,  15,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   124,   0,   0, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  15,  24,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     8,  44, 184,  44   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 30 (Zyrinx bank1 voice 173) ---
        pbyte   18                      ; fp_alg_fb     $12
        pbyte   196                     ; fp_lr_ams_fms $C4
        pbyte     8,   8,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127,   0,   0, 127   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  23   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,  15,  24,  19   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,  17,   0,  16   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     8,  44, 184,  44   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 31 (Zyrinx bank1 voice 177) ---
        pbyte   59                      ; fp_alg_fb     $3B
        pbyte   193                     ; fp_lr_ams_fms $C1
        pbyte   116, 116,   2, 116   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   127, 110,  90, 112   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte   145, 145, 145, 145   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte    23,  23,  23,  23   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   2,   2,   2   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte   102,   6,   6,   6   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
; --- local 32 (Zyrinx bank1 voice 108) ---
        pbyte   0                       ; fp_alg_fb     $00
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   0,   0,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_tl      $40  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_rs_ar   $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r     $70  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
MovingTrucks_Patches_End:

        if (MovingTrucks_Patches_End-MovingTrucks_Patches)/FmPatch_len <> PATCH_COUNT_MT
          error "Moving Trucks patch bank count mismatch"
        endif
        if (MovingTrucks_Patches_End-MovingTrucks_Patches) <> PATCH_COUNT_MT*FmPatch_len
          error "Moving Trucks patch bank size mismatch"
        endif

