; ======================================================================
; Song_StepTest.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_StepTest label (loader adds the base).
; ======================================================================

Song_StepTest:
    dc.b   $00, $80, $10, $01, $00, $00, $00, $00, $0D, $00, $00, $00, $00, $E1, $01, $E0
    dc.b   $6E, $01, $EE, $E8, $01, $30, $EA, $01, $04, $38, $E8, $01, $30, $EA, $01, $04
    dc.b   $30, $E8, $01, $30, $EA, $01, $04, $28, $E8, $01, $30, $EA, $01, $04, $20, $E8
    dc.b   $01, $30, $EA, $01, $04, $28, $E8, $01, $30, $EA, $01, $04, $30, $E8, $01, $30
    dc.b   $EF
Song_StepTest_End:

    align 2
