; ======================================================================
; Song_PanTest.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_PanTest label (loader adds the base).
; ======================================================================

Song_PanTest:
    dc.b   $00, $80, $10, $01, $00, $00, $00, $00, $0D, $00, $00, $00, $00, $E1, $01, $E0
    dc.b   $6E, $3B, $EE, $E4, $80, $E8, $01, $30, $E4, $40, $E8, $01, $30, $E4, $C0, $E9
    dc.b   $00, $30, $E1, $01, $E8, $01, $30, $E9, $00, $F0, $E1, $01, $E8, $01, $30, $EF
Song_PanTest_End:

    align 2
