; ======================================================================
; Song_PitchTest.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_PitchTest label (loader adds the base).
; ======================================================================

Song_PitchTest:
    dc.b   $00, $80, $10, $01, $00, $00, $00, $00, $0D, $00, $00, $00, $00, $E1, $01, $E0
    dc.b   $6E, $1E, $EE, $E8, $01, $24, $E8, $01, $28, $E8, $01, $2B, $E8, $01, $30, $E8
    dc.b   $01, $3C, $E8, $01, $48, $EF
Song_PitchTest_End:

    align 2
