; ======================================================================
; Song_TrillTest.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_TrillTest label (loader adds the base).
; ======================================================================

Song_TrillTest:
    dc.b   $00, $80, $10, $01, $00, $00, $00, $00, $0D, $00, $00, $00, $00, $E1, $01, $E0
    dc.b   $6E, $3B, $EE, $E8, $02, $30, $32, $E8, $03, $24, $28, $2B, $EF
Song_TrillTest_End:

    align 2
