; ======================================================================
; Song_Test.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_Test label (loader adds the base).
; ======================================================================

Song_Test:
    dc.b   $06, $05, $00, $00, $13, $01, $00, $20, $05, $00, $2D, $08, $00, $36, $09, $00
    dc.b   $3D, $00, $00, $E1, $00, $E0, $64, $10, $EE, $BA, $BD, $C1, $80, $C6, $80, $EF
    dc.b   $E1, $01, $E0, $50, $20, $EE, $BA, $80, $E3, $40, $18, $80, $EF, $E0, $5A, $08
    dc.b   $EE, $C6, $C1, $BD, $BA, $EF, $E0, $46, $20, $EE, $81, $80, $EF, $20, $EE, $E2
    dc.b   $01, $80, $E2, $01, $80, $EF
Song_Test_End:

    align 2
