; ======================================================================
; data/sound/song_table.asm — song id -> SongHeader pointer table.
;
; Holds the native "Moving Trucks" (B&R) port — the only song, id 1. The
; SongPatchTable + the stream-path loader infra below feed its bank-aligned
; 32KB streaming block.
;
; CONTRACT: SongTable is SONG_COUNT longwords, indexed SongTable[id-1] (id 1 is
; the first entry). Song id 0 is RESERVED for "stop music".
; ======================================================================

; SONG_MOVINGTRUCKS (Sound Phase 3 Task 8): the NATIVE "Moving Trucks" (B&R) port —
; a real sequencer playback of the song data (NOT a register replay). 6 FM channels
; (FM1..FM6, 1:1), streamed from ROM with the DAC off (SH_F_FM6_FM|SH_F_STREAM). Its
; song + per-song pitch table + FmPatch bank form ONE bank-aligned 32KB streaming
; block (asserted below). Generated by tools/zyrinx_player.py --emit-native-song.
SONG_MOVINGTRUCKS  = 1
SONG_COUNT         = 1

SongTable:
        dc.l    Song_MovingTrucks   ; id 1 — Phase 3 Task 8 native Moving Trucks (streamed)
SongTable_End:

        if (SongTable_End-SongTable)/4 <> SONG_COUNT
          error "song table length \{(SongTable_End-SongTable)/4} != SONG_COUNT"
        endif

; --- parallel per-song FM-patch-bank pointer table -------------------------
; SongPatchTable[id-1] = the 68k ROM address of the song's FM patch bank. The 68k
; Sound_PlayMusic derives its $8000-window ptr and forwards it; the Z80 loader uses
; it on the stream path (the patch bank shares the song's bank).
SongPatchTable:
        dc.l    MovingTrucks_Patches ; id 1 Song_MovingTrucks (stream path — USED)
SongPatchTable_End:

        if (SongPatchTable_End-SongPatchTable)/4 <> SONG_COUNT
          error "song-patch table length \{(SongPatchTable_End-SongPatchTable)/4} != SONG_COUNT"
        endif

        ; song ids are 1..$FE in SND_REQ_MUSIC ($FF = stop sentinel), so the real
        ; song count must stay below $FF.
        if SONG_COUNT >= $FF
          error "SONG_COUNT (\{SONG_COUNT}) must be < $FF ($FF is the stop sentinel)"
        endif

        ; Song_MovingTrucks is the only song and STREAMS from ROM (T3, SH_F_STREAM):
        ; it never passes through the fixed copy-path SND_SONG_BUF, so it needs no
        ; per-song buffer-fit / $8000-window-wrap asserts (those guarded the removed
        ; copy-path scratch songs).

        ; --- Sound Phase 3 Task 8 + F5 co-location: the Moving Trucks STREAMING block
        ; must fit in ONE 32KB bank so a single SetBank covers every sequencer ROM read
        ; (the loader holds that one bank for the whole DAC-off song). The F5 redo puts
        ; the engine lookup tables at the START of this same bank, so the block now runs
        ; MovingTrucks_Bank_Start (tables) .. MovingTrucks_Patches_End (song stream +
        ; per-song pitch table + FmPatch bank), placed contiguously after one
        ; `align $8000` in main.asm. MT reads tables AND its own stream through the SAME
        ; banked $8000 window — no swap. Assert it does NOT cross a 32KB bank boundary
        ; (top byte in the same 32KB bank as the bank start). Combined size is ~1KB
        ; tables + ~14.9KB song + 264B pitch table + 858B patches ~= 17KB << 32KB, so
        ; the align guarantees it — this catches any future growth or reordering. The
        ; table labels, the per-channel stream offsets, the header pitchtable_ptr
        ; offset, and the patch-bank window ptr are all bank-window-relative
        ; (window_base = (addr & $7FFF) | $8000), which holds iff no boundary cross.
        if (MovingTrucks_Bank_Start >> 15) <> ((MovingTrucks_Patches_End-1) >> 15)
          fatal "Moving Trucks streaming block (tables+song+pitchtable+patches, \{MovingTrucks_Patches_End-MovingTrucks_Bank_Start} bytes) crosses a 32KB bank boundary — one SetBank can't cover it. Keep MovingTrucks_Bank_Start bank-aligned (align $8000) with tables + song + pitch table + patch bank contiguous."
        endif
        ; The streaming block's whole window region must also stay below the $8000-
        ; window top (so window_base + any per-channel offset / the pitchtable offset
        ; stays a valid window address, never wrapping past $FFFF). With bank-
        ; alignment (addr & $7FFF)=0 this is automatic, but assert it against future
        ; placement changes.
        if ((MovingTrucks_Patches_End-1) & $7FFF) < (MovingTrucks_Patches_End-1 - MovingTrucks_Bank_Start)
          fatal "Moving Trucks streaming block extends past the $8000-window top — not bank-aligned? Keep `align $8000` before MovingTrucks_Bank_Start."
        endif

        align 2
