; ======================================================================
; Song_Test.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_Test label (loader adds the base).
; ======================================================================

Song_Test:
    dc.b   $00, $80, $03, $00, $00, $0E, $01, $00, $28, $06, $00, $37, $00, $00, $E1, $01
    dc.b   $E0, $5F, $34, $EE, $B5, $B5, $B6, $B8, $B8, $B6, $B5, $B3, $B1, $B1, $B3, $B5
    dc.b   $B5, $B3, $B5, $B3, $E3, $32, $68, $EF, $E1, $00, $E0, $55, $68, $EE, $99, $99
    dc.b   $99, $A0, $99, $99, $A0, $99, $EF, $E0, $30, $34, $EE, $B1, $B1, $B3, $B5, $B5
    dc.b   $B3, $B1, $B0, $AE, $AE, $B0, $B1, $B1, $B0, $B1, $B0, $E3, $2F, $68, $EF
Song_Test_End:

    align 2
