; ======================================================================
; Song_Test.asm — GENERATED by tools/song_packer.py — DO NOT EDIT BY HAND.
; Packed music song (Music format v0). Stream pointers in the header are
; 16-bit BE offsets relative to the Song_Test label (loader adds the base).
; ======================================================================

Song_Test:
    dc.b   $00, $80, $10, $03, $00, $00, $00, $00, $17, $00, $00, $01, $00, $31, $00, $00
    dc.b   $06, $00, $40, $00, $00, $00, $00, $E1, $01, $E0, $5F, $1E, $EE, $B5, $B5, $B6
    dc.b   $B8, $B8, $B6, $B5, $B3, $B1, $B1, $B3, $B5, $B5, $B3, $B5, $B3, $E3, $32, $3C
    dc.b   $EF, $E1, $00, $E0, $55, $3C, $EE, $99, $99, $99, $A0, $99, $99, $A0, $99, $EF
    dc.b   $E0, $30, $1E, $EE, $B1, $B1, $B3, $B5, $B5, $B3, $B1, $B0, $AE, $AE, $B0, $B1
    dc.b   $B1, $B0, $B1, $B0, $E3, $2F, $3C, $EF
Song_Test_End:

    align 2
