; ======================================================================
; data/sound/song_table.asm — song id -> SongHeader pointer table.
;
; Holds the bring-up test song (SONG_TEST). The Sound 1D FM-depth work
; (Phase 3) re-adds the real "Moving Trucks" port as a streaming song; the
; SongPatchTable + the stream-path loader infra below are kept ready for it.
;
; CONTRACT: SongTable is SONG_COUNT longwords, indexed SongTable[id-1] (id 1 is
; the first entry). Song id 0 is RESERVED for "stop music". SONG_TEST is the id
; of the bring-up song authored in data/sound/song_test.py.
; ======================================================================

SONG_TEST          = 1
; SONG_PITCHTEST (Sound Phase 3 Task 3): a SCRATCH one-FM-channel verification
; song emitting MEV_PITCHENV count=1 notes at known fnum-table indices so the
; controller can confirm the per-song pitch table + the ModUpdate single-note
; render. Copy-path (FM6=DAC, RAM-buffered), pitchtable_ptr=0 -> engine-default
; table. Kept ALONGSIDE SONG_TEST so DEBUG boot can switch back after verifying.
SONG_PITCHTEST     = 2
; SONG_TRILLTEST (Sound Phase 3 Task 4): a SCRATCH one-FM-channel verification song
; emitting MULTI-POINT MEV_PITCHENV notes (a count=2 whole-step trill [$30,$32] and
; a count=3 major-triad arp [$24,$28,$2B]) so the controller can confirm ModUpdate's
; .multipoint per-frame cursor cycling. Copy-path, pitchtable_ptr=0 (engine default).
; Kept ALONGSIDE SONG_TEST/SONG_PITCHTEST so DEBUG boot can switch back after verifying.
SONG_TRILLTEST     = 3
; SONG_PANTEST (Sound Phase 3 Task 6): a SCRATCH one-FM-channel verification song
; exercising MEV_PAN ($E4, write-on-change $B4) and MEV_OPBIAS ($E9, per-operator
; TL bias latched in Fm_PatchLoad). A note hard-LEFT ($B4=$80, ~1s), the same note
; hard-RIGHT ($B4=$40, ~1s), then a recentered ($B4=$C0) note with a +$30 bias on
; modulator op0 (reg $40 = $68 vs $38), looping. Copy-path (FM6=DAC, RAM-buffered),
; pitchtable_ptr=0 -> engine default. Kept ALONGSIDE the other scratch songs so DEBUG
; boot can switch back. See data/sound/song_pantest.py for the expected $B4/$40 bytes.
SONG_PANTEST       = 4
; SONG_STEPTEST (Sound Phase 3 Task 5): a SCRATCH one-FM-channel verification song
; exercising MEV_REGDELTA ($EA) VOICE-STEPPING + the RE-KEY RULE. One held note (one
; MEV_PITCHENV count=1) is keyed ONCE, then a rapid sweep of single-byte operator-S1
; TL writes (the $40 group op0: $38,$30,$28,$20,$28,$30) re-articulates the TIMBRE
; mid-note WITHOUT re-keying, paced one step per event-tick. Expected: reg $40 (FM1
; op0) sweeps through those values and EXACTLY ONE key-on (no re-attacks during the
; sweep — same-index PitchEnvs are held no-attacks per the re-key rule). Copy-path
; (FM6=DAC, RAM-buffered), pitchtable_ptr=0 -> engine default. Kept ALONGSIDE the
; other scratch songs so DEBUG boot can switch back. See data/sound/song_steptest.py.
SONG_STEPTEST      = 5
; SONG_MOVINGTRUCKS (Sound Phase 3 Task 8): the NATIVE "Moving Trucks" (B&R) port —
; a real sequencer playback of the song data (NOT a register replay). 6 FM channels
; (FM1..FM6, 1:1), streamed from ROM with the DAC off (SH_F_FM6_FM|SH_F_STREAM). Its
; song + per-song pitch table + FmPatch bank form ONE bank-aligned 32KB streaming
; block (asserted below). Generated by tools/zyrinx_player.py --emit-native-song.
SONG_MOVINGTRUCKS  = 6
SONG_COUNT         = 6

SongTable:
        dc.l    Song_Test           ; id 1 (SongTable[id-1])
        dc.l    Song_PitchTest      ; id 2 — Phase 3 Task 3 scratch pitch verification
        dc.l    Song_TrillTest      ; id 3 — Phase 3 Task 4 scratch trill/arp verification
        dc.l    Song_PanTest        ; id 4 — Phase 3 Task 6 scratch pan/op-bias verification
        dc.l    Song_StepTest       ; id 5 — Phase 3 Task 5 scratch voice-stepping verification
        dc.l    Song_MovingTrucks   ; id 6 — Phase 3 Task 8 native Moving Trucks (streamed)
SongTable_End:

        if (SongTable_End-SongTable)/4 <> SONG_COUNT
          error "song table length \{(SongTable_End-SongTable)/4} != SONG_COUNT"
        endif

; --- parallel per-song FM-patch-bank pointer table -------------------------
; SongPatchTable[id-1] = the 68k ROM address of the song's FM patch bank. The 68k
; Sound_PlayMusic derives its $8000-window ptr and forwards it; the Z80 loader uses
; it ONLY on the stream path (the patch bank shares the song's bank). The copy path
; (1C songs) IGNORES it — its patches stay inline in Z80 RAM (FmPatchInlineTable),
; so the entry is a harmless placeholder (FmPatchTable, the 68k ROM table) for
; Song_Test. (Phase 3's streaming Moving Trucks will add its own bank here.)
SongPatchTable:
        dc.l    FmPatchTable        ; id 1 Song_Test (copy path — entry unused)
        dc.l    FmPatchTable        ; id 2 Song_PitchTest (copy path — entry unused)
        dc.l    FmPatchTable        ; id 3 Song_TrillTest (copy path — entry unused)
        dc.l    FmPatchTable        ; id 4 Song_PanTest (copy path — entry unused)
        dc.l    FmPatchTable        ; id 5 Song_StepTest (copy path — entry unused)
        dc.l    MovingTrucks_Patches ; id 6 Song_MovingTrucks (stream path — USED)
SongPatchTable_End:

        if (SongPatchTable_End-SongPatchTable)/4 <> SONG_COUNT
          error "song-patch table length \{(SongPatchTable_End-SongPatchTable)/4} != SONG_COUNT"
        endif

        ; song ids are 1..$FE in SND_REQ_MUSIC ($FF = stop sentinel), so the real
        ; song count must stay below $FF.
        if SONG_COUNT >= $FF
          error "SONG_COUNT (\{SONG_COUNT}) must be < $FF ($FF is the stop sentinel)"
        endif

        ; The loader copies a FIXED SND_SONG_BUF_SIZE bytes of the packed song into
        ; Z80 RAM, so a RAM-BUFFERED (copy-path) song must fit in that buffer.
        if (Song_Test_End-Song_Test) > SND_SONG_BUF_SIZE
          fatal "Song_Test (\{Song_Test_End-Song_Test} bytes) exceeds SND_SONG_BUF_SIZE (\{SND_SONG_BUF_SIZE})"
        endif
        if (Song_PitchTest_End-Song_PitchTest) > SND_SONG_BUF_SIZE
          fatal "Song_PitchTest (\{Song_PitchTest_End-Song_PitchTest} bytes) exceeds SND_SONG_BUF_SIZE (\{SND_SONG_BUF_SIZE})"
        endif
        if (Song_TrillTest_End-Song_TrillTest) > SND_SONG_BUF_SIZE
          fatal "Song_TrillTest (\{Song_TrillTest_End-Song_TrillTest} bytes) exceeds SND_SONG_BUF_SIZE (\{SND_SONG_BUF_SIZE})"
        endif
        if (Song_PanTest_End-Song_PanTest) > SND_SONG_BUF_SIZE
          fatal "Song_PanTest (\{Song_PanTest_End-Song_PanTest} bytes) exceeds SND_SONG_BUF_SIZE (\{SND_SONG_BUF_SIZE})"
        endif
        if (Song_StepTest_End-Song_StepTest) > SND_SONG_BUF_SIZE
          fatal "Song_StepTest (\{Song_StepTest_End-Song_StepTest} bytes) exceeds SND_SONG_BUF_SIZE (\{SND_SONG_BUF_SIZE})"
        endif

        ; The loader's fixed SND_SONG_BUF_SIZE-byte `ldir` reads from the song's
        ; $8000-window ptr ((addr & $7FFF) | $8000). If that window region sits within
        ; SND_SONG_BUF_SIZE bytes of $FFFF, the copy's source ptr wraps past $FFFF into
        ; Z80 RAM ($0000) and copies garbage into the buffer tail. Forbid it: the window
        ; offset must leave room for the full copy below the $8000-window top.
        if (Song_Test & $7FFF) > ($8000 - SND_SONG_BUF_SIZE)
          fatal "Song_Test window region crosses the $8000-window top: the \{SND_SONG_BUF_SIZE}-byte load ldir would wrap past $FFFF into Z80 RAM. Move Song_Test so (addr & $7FFF) <= \{$8000 - SND_SONG_BUF_SIZE}."
        endif
        if (Song_PitchTest & $7FFF) > ($8000 - SND_SONG_BUF_SIZE)
          fatal "Song_PitchTest window region crosses the $8000-window top: the \{SND_SONG_BUF_SIZE}-byte load ldir would wrap past $FFFF into Z80 RAM. Move Song_PitchTest so (addr & $7FFF) <= \{$8000 - SND_SONG_BUF_SIZE}."
        endif
        if (Song_TrillTest & $7FFF) > ($8000 - SND_SONG_BUF_SIZE)
          fatal "Song_TrillTest window region crosses the $8000-window top: the \{SND_SONG_BUF_SIZE}-byte load ldir would wrap past $FFFF into Z80 RAM. Move Song_TrillTest so (addr & $7FFF) <= \{$8000 - SND_SONG_BUF_SIZE}."
        endif
        if (Song_PanTest & $7FFF) > ($8000 - SND_SONG_BUF_SIZE)
          fatal "Song_PanTest window region crosses the $8000-window top: the \{SND_SONG_BUF_SIZE}-byte load ldir would wrap past $FFFF into Z80 RAM. Move Song_PanTest so (addr & $7FFF) <= \{$8000 - SND_SONG_BUF_SIZE}."
        endif
        if (Song_StepTest & $7FFF) > ($8000 - SND_SONG_BUF_SIZE)
          fatal "Song_StepTest window region crosses the $8000-window top: the \{SND_SONG_BUF_SIZE}-byte load ldir would wrap past $FFFF into Z80 RAM. Move Song_StepTest so (addr & $7FFF) <= \{$8000 - SND_SONG_BUF_SIZE}."
        endif
        ; Song_MovingTrucks is NOT buffer-asserted above: it STREAMS from ROM (T3,
        ; SH_F_STREAM) and never passes through the fixed copy-path SND_SONG_BUF.

        ; --- Sound Phase 3 Task 8: the Moving Trucks STREAMING block (song stream +
        ; per-song pitch table + FmPatch bank) must fit in ONE 32KB bank so a single
        ; SetBank covers every sequencer ROM read (the loader holds that one bank for
        ; the whole DAC-off song). The block is Song_MovingTrucks .. MovingTrucks_-
        ; Patches_End, placed contiguously after one `align $8000` in main.asm.
        ; Assert it does NOT cross a 32KB bank boundary (top byte in the same 32KB
        ; bank as the start). Combined size is ~14.9KB song + 264B pitch table +
        ; 858B patches ~= 16KB << 32KB, so the align guarantees it — this catches any
        ; future growth or accidental reordering. The per-channel stream offsets, the
        ; header pitchtable_ptr offset, and the patch-bank window ptr are all
        ; bank-window-relative (window_base = (addr & $7FFF) | $8000), which holds
        ; iff no boundary cross.
        if (Song_MovingTrucks >> 15) <> ((MovingTrucks_Patches_End-1) >> 15)
          fatal "Moving Trucks streaming block (song+pitchtable+patches, \{MovingTrucks_Patches_End-Song_MovingTrucks} bytes) crosses a 32KB bank boundary — one SetBank can't cover it. Keep Song_MovingTrucks bank-aligned (align $8000) with the pitch table + patch bank contiguous."
        endif
        ; The streaming song's whole window region must also stay below the $8000-
        ; window top (so window_base + any per-channel offset / the pitchtable offset
        ; stays a valid window address, never wrapping past $FFFF). With bank-
        ; alignment (addr & $7FFF)=0 this is automatic, but assert it against future
        ; placement changes.
        if ((MovingTrucks_Patches_End-1) & $7FFF) < (MovingTrucks_Patches_End-1 - Song_MovingTrucks)
          fatal "Moving Trucks streaming block extends past the $8000-window top — not bank-aligned? Keep `align $8000` before Song_MovingTrucks."
        endif

        align 2
