; ======================================================================
; data/sound/sound_tables.asm — GENERATED by tools/gen_sound_tables.py
; DO NOT EDIT BY HAND. Regenerate: python3 tools/gen_sound_tables.py
;
; FM pitch table : per pitch index, dc.w = ($A4 value << 8) | $A0 value
;                  ($A4 = (block<<3)|(fnum>>8), $A0 = fnum&$FF).
; PSG divisor    : per pitch index, dc.w = 10-bit tone divisor.
; Log volume LUT : 256 bytes, linear vol 0..127 -> YM TL delta (log).
; Carrier mask   : 8 bytes, algo 0..7 -> 4-bit carrier-op mask
;                  (bit i = operator at reg offset +i*4 = S1,S3,S2,S4).
; A4=440Hz -> FM fnum $43B/block 4 (pitch idx 57); PSG divisor $0FE.
; ======================================================================

FmPitchTable:
    dc.w   $0284, $02AA, $02D3, $02FE, $032B, $035B, $038E, $03C5
    dc.w   $03FE, $043B, $047B, $04BF, $0508, $0554, $05A5, $05FB
    dc.w   $0656, $06B7, $071D, $0789, $07FC, $0C3B, $0C7B, $0CBF
    dc.w   $0D08, $0D54, $0DA5, $0DFB, $0E56, $0EB7, $0F1D, $0F89
    dc.w   $0FFC, $143B, $147B, $14BF, $1508, $1554, $15A5, $15FB
    dc.w   $1656, $16B7, $171D, $1789, $17FC, $1C3B, $1C7B, $1CBF
    dc.w   $1D08, $1D54, $1DA5, $1DFB, $1E56, $1EB7, $1F1D, $1F89
    dc.w   $1FFC, $243B, $247B, $24BF, $2508, $2554, $25A5, $25FB
    dc.w   $2656, $26B7, $271D, $2789, $27FC, $2C3B, $2C7B, $2CBF
    dc.w   $2D08, $2D54, $2DA5, $2DFB, $2E56, $2EB7, $2F1D, $2F89
    dc.w   $2FFC, $343B, $347B, $34BF, $3508, $3554, $35A5, $35FB
    dc.w   $3656, $36B7, $371D, $3789, $37FC, $3C3B, $3C7B
FmPitchTable_End:

        if (FmPitchTable_End-FmPitchTable)/2 <> 95
          error "FM pitch table wrong length"
        endif

PsgDivisorTable:
    dc.w   $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF
    dc.w   $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF
    dc.w   $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF
    dc.w   $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF, $03FF
    dc.w   $03FF, $03F9, $03C0, $038A, $0357, $0327, $02FA, $02CF
    dc.w   $02A7, $0281, $025D, $023B, $021B, $01FC, $01E0, $01C5
    dc.w   $01AC, $0194, $017D, $0168, $0153, $0140, $012E, $011D
    dc.w   $010D, $00FE, $00F0, $00E2, $00D6, $00CA, $00BE, $00B4
    dc.w   $00AA, $00A0, $0097, $008F, $0087, $007F, $0078, $0071
    dc.w   $006B, $0065, $005F, $005A, $0055, $0050, $004C, $0047
    dc.w   $0043, $0040, $003C, $0039, $0035, $0032, $0030, $002D
    dc.w   $002A, $0028, $0026, $0024, $0022, $0020, $001E
PsgDivisorTable_End:

        if (PsgDivisorTable_End-PsgDivisorTable)/2 <> 95
          error "PSG divisor table wrong length"
        endif

LogVolumeLut:
    dc.b   $7F, $7F, $6D, $62, $5B, $55, $50, $4C, $48, $45, $43, $40, $3E, $3C, $3A, $38
    dc.b   $36, $35, $33, $32, $30, $2F, $2E, $2D, $2C, $2B, $2A, $29, $28, $27, $26, $25
    dc.b   $24, $23, $23, $22, $21, $20, $20, $1F, $1E, $1E, $1D, $1C, $1C, $1B, $1B, $1A
    dc.b   $1A, $19, $18, $18, $17, $17, $16, $16, $15, $15, $15, $14, $14, $13, $13, $12
    dc.b   $12, $12, $11, $11, $10, $10, $10, $0F, $0F, $0F, $0E, $0E, $0D, $0D, $0D, $0C
    dc.b   $0C, $0C, $0B, $0B, $0B, $0B, $0A, $0A, $0A, $09, $09, $09, $08, $08, $08, $08
    dc.b   $07, $07, $07, $07, $06, $06, $06, $05, $05, $05, $05, $04, $04, $04, $04, $04
    dc.b   $03, $03, $03, $03, $02, $02, $02, $02, $01, $01, $01, $01, $01, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
LogVolumeLut_End:

        if (LogVolumeLut_End-LogVolumeLut) <> 256
          error "log volume LUT must be 256 bytes"
        endif

CarrierMaskTable:
    dc.b   $08, $08, $08, $08, $0C, $0E, $0E, $0F
CarrierMaskTable_End:

        if (CarrierMaskTable_End-CarrierMaskTable) <> 8
          error "carrier mask table must be 8 bytes"
        endif

        align 2
