; OJZ Act 1 level descriptor and section tables (§4 Phase 1, §2 A.3)
; Act struct defined in structs.asm. Strip data in data/generated/ojz/act1/ (gitignored).

; Per-section VRAM bases (auto-generated by tools/ojz_strip_gen.py)
    include "data/generated/ojz/act1/sec_vram_bases.asm"

; -----------------------------------------------
; OJZ Act 1 — descriptor and section table
; 9 sections (sec0–sec8) in a 3×3 grid (vertical teleport test)
; -----------------------------------------------
; Build assert: grid_w*grid_h must fit within Section_Stream_State.
; Literals below must match the grid_w/grid_h dc.w values in the descriptor below.
    if 3*3 > MAX_ACT_SECTIONS
      error "OJZ act 1 grid (3x3) exceeds MAX_ACT_SECTIONS"
    endif

OJZ_Act1_Descriptor:
    dc.l    OJZ_Act1_Sections       ; sec_grid_ptr
    dc.w    3                       ; grid_w (3 sections wide)
    dc.w    3                       ; grid_h (3 sections tall)
    dc.w    $0100                   ; start_local_x: 256px into section 0
    dc.w    $0100                   ; start_local_y: 256px into section (ground level)
    dc.b    0                       ; start_sec_x = 0
    dc.b    0                       ; start_sec_y = 0
    dc.w    SLOT_ORIGIN_L           ; cam_min_x ($200)
    dc.w    SLOT_ORIGIN_L + $1680   ; cam_max_x (approximate for 3 sections)
    dc.w    SLOT_ORIGIN_U            ; cam_min_y ($200 — no section above row 0)
    dc.w    SLOT_ORIGIN_U+SECTION_SHIFT-224 ; cam_max_y (bottom of lower slot minus screen height)
    dc.l    OJZ_Act1_BG_Layout      ; act_bg_layout (§2 A.5 T1 zone-wide BG nametable)
    dc.l    OJZ_Act1_BG_Tiles       ; act_bg_tiles  (§2 A.5 T1 shared BG tile blob)
    dc.l    ParallaxConfig_OJZ_Default ; act_parallax_config (fallback for sections with NULL config)
    align 2

; -----------------------------------------------
; Section definition table — 9 entries × $48 bytes (Sec_len)
; Grid layout (3×3):  Row 0 = Sec0,Sec1,Sec2 (unique art)
;                     Row 1 = Sec3,Sec4,Sec5 (clone Sec0 art, distinct sky tint)
;                     Row 2 = Sec6,Sec7,Sec8 (clone Sec0 art, distinct sky tint)
; -----------------------------------------------
OJZ_Act1_Sections:

OJZ_Sec0:
    dc.l    OJZ_Sec0_Blocks          ; sec_block_index (§4.7 2D)
    dc.l    OJZ_Sec0_Objects        ; sec_objects
    dc.l    OJZ_Sec0_Rings          ; sec_rings
    dc.l    0                       ; sec_plc
    dc.l    OJZ_Palette             ; sec_pal
    dc.l    ParallaxConfig_OJZ_Caves, 0    ; sec_parallax_config = T15 F4 fixture: slow-BG cave gradient (scenes/caves.asm)
    dc.l    0                       ; sec_bg_layout (NULL = use Act_act_bg_layout, T1)
    dc.l    OJZ_Sec0_TypeTable      ; sec_type_table (§4.9)
    dc.l    0, 0                    ; sec_pal_cycle, sec_sound_bank
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0                    ; sec_flags, sec_music
    dc.b    0, 0, 0, 0              ; reserved bytes
    dc.l    OJZ_Sec0_Tiles_S4LZ     ; sec_tile_art_s4lz (§2 A.3)
    dc.w    OJZ_SEC0_VRAM           ; sec_tile_art_vram
    dc.w    0                       ; pad
    align 2

OJZ_Sec1:
    dc.l    OJZ_Sec1_Blocks
    dc.l    OJZ_Sec1_Objects        ; sec_objects
    dc.l    OJZ_Sec1_Rings          ; sec_rings
    dc.l    0                       ; sec_plc
    dc.l    OJZ_Palette
    dc.l    ParallaxConfig_OJZ_Windy, 0  ; sec_parallax_config = windy variant (F3)
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec1_TypeTable      ; sec_type_table (§4.9)
    dc.l    0, 0                    ; sec_pal_cycle, sec_sound_bank
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec1_Tiles_S4LZ
    dc.w    OJZ_SEC1_VRAM
    dc.w    0
    align 2

OJZ_Sec2:
    dc.l    OJZ_Sec2_Blocks
    dc.l    OJZ_Sec2_Objects        ; sec_objects
    dc.l    OJZ_Sec2_Rings          ; sec_rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    ParallaxConfig_SkyHaze, 0      ; sec_parallax_config = parallax_combine_split demo (was on Sec0, swapped here)
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec2_TypeTable      ; sec_type_table (§4.9)
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec2_Tiles_S4LZ
    dc.w    OJZ_SEC2_VRAM
    dc.w    0
    align 2

OJZ_Sec3:
    dc.l    OJZ_Sec3_Blocks
    dc.l    OJZ_Sec3_Objects
    dc.l    OJZ_Sec3_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    ParallaxConfig_OJZ_LockedClouds, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec3_TypeTable
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec3_Tiles_S4LZ
    dc.w    OJZ_SEC3_VRAM
    dc.w    0
    align 2

OJZ_Sec4:
    dc.l    OJZ_Sec4_Blocks
    dc.l    OJZ_Sec4_Objects
    dc.l    OJZ_Sec4_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec4_TypeTable
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec4_Tiles_S4LZ
    dc.w    OJZ_SEC4_VRAM
    dc.w    0
    align 2

OJZ_Sec5:
    dc.l    OJZ_Sec5_Blocks
    dc.l    OJZ_Sec5_Objects
    dc.l    OJZ_Sec5_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec5_TypeTable
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec5_Tiles_S4LZ
    dc.w    OJZ_SEC5_VRAM
    dc.w    0
    align 2

OJZ_Sec6:
    dc.l    OJZ_Sec6_Blocks
    dc.l    OJZ_Sec6_Objects
    dc.l    OJZ_Sec6_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec6_TypeTable
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec6_Tiles_S4LZ
    dc.w    OJZ_SEC6_VRAM
    dc.w    0
    align 2

OJZ_Sec7:
    dc.l    OJZ_Sec7_Blocks
    dc.l    OJZ_Sec7_Objects
    dc.l    OJZ_Sec7_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec7_TypeTable
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec7_Tiles_S4LZ
    dc.w    OJZ_SEC7_VRAM
    dc.w    0
    align 2

OJZ_Sec8:
    dc.l    OJZ_Sec8_Blocks
    dc.l    OJZ_Sec8_Objects
    dc.l    OJZ_Sec8_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec8_TypeTable
    dc.l    0, 0
    dc.l    0                        ; sec_reserved_2C
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.l    OJZ_Sec8_Tiles_S4LZ
    dc.w    OJZ_SEC8_VRAM
    dc.w    0
    align 2

; -----------------------------------------------
; Generated block data — 16×16 blocks, S4LZ compressed (§4.7 2D)
; -----------------------------------------------
OJZ_Sec0_Blocks: BINCLUDE "data/generated/ojz/act1/sec0_blocks.bin"
    align 2
OJZ_Sec1_Blocks: BINCLUDE "data/generated/ojz/act1/sec1_blocks.bin"
    align 2
OJZ_Sec2_Blocks: BINCLUDE "data/generated/ojz/act1/sec2_blocks.bin"
    align 2
OJZ_Sec3_Blocks: BINCLUDE "data/generated/ojz/act1/sec3_blocks.bin"
    align 2
OJZ_Sec4_Blocks: BINCLUDE "data/generated/ojz/act1/sec4_blocks.bin"
    align 2
OJZ_Sec5_Blocks: BINCLUDE "data/generated/ojz/act1/sec5_blocks.bin"
    align 2
OJZ_Sec6_Blocks: BINCLUDE "data/generated/ojz/act1/sec6_blocks.bin"
    align 2
OJZ_Sec7_Blocks: BINCLUDE "data/generated/ojz/act1/sec7_blocks.bin"
    align 2
OJZ_Sec8_Blocks: BINCLUDE "data/generated/ojz/act1/sec8_blocks.bin"
    align 2

; -----------------------------------------------
; Legacy strip data — kept for migration (strip_cache.asm still compiled)
; -----------------------------------------------
OJZ_Sec0_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec0_strips.s4lz"
    align 2
OJZ_Sec0_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec0_strip_checkpoints.bin"
    align 2
OJZ_Sec1_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec1_strips.s4lz"
    align 2
OJZ_Sec1_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec1_strip_checkpoints.bin"
    align 2
OJZ_Sec2_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec2_strips.s4lz"
    align 2
OJZ_Sec2_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec2_strip_checkpoints.bin"
    align 2
OJZ_Sec3_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec3_strips.s4lz"
    align 2
OJZ_Sec3_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec3_strip_checkpoints.bin"
    align 2
OJZ_Sec4_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec4_strips.s4lz"
    align 2
OJZ_Sec4_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec4_strip_checkpoints.bin"
    align 2
OJZ_Sec5_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec5_strips.s4lz"
    align 2
OJZ_Sec5_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec5_strip_checkpoints.bin"
    align 2
OJZ_Sec6_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec6_strips.s4lz"
    align 2
OJZ_Sec6_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec6_strip_checkpoints.bin"
    align 2
OJZ_Sec7_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec7_strips.s4lz"
    align 2
OJZ_Sec7_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec7_strip_checkpoints.bin"
    align 2
OJZ_Sec8_Strips_S4LZ: BINCLUDE "data/generated/ojz/act1/sec8_strips.s4lz"
    align 2
OJZ_Sec8_Strip_Checkpoints: BINCLUDE "data/generated/ojz/act1/sec8_strip_checkpoints.bin"
    align 2

OJZ_Palette: BINCLUDE "data/generated/ojz/act1/ojz_palette.bin"
    align 2

; Shared/HUD palette (CRAM line 0) — sonic_hack convention for level rendering.
BGND_Palette: BINCLUDE "art/palettes/SonicAndTails.bin"
    align 2

; Zone-wide BG layout + shared BG tile blob (§2 A.5 T1)
OJZ_Act1_BG_Layout: BINCLUDE "data/generated/ojz/act1/zone_bg.bin"
    align 2
OJZ_Act1_BG_Tiles:  BINCLUDE "data/generated/ojz/act1/bg_tiles.bin"
    align 2

; Per-section tile blobs (§2 A.3)
OJZ_Sec0_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec0_tiles.s4lz"
    align 2
OJZ_Sec1_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec1_tiles.s4lz"
    align 2
OJZ_Sec2_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec2_tiles.s4lz"
    align 2
OJZ_Sec3_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec3_tiles.s4lz"
    align 2
OJZ_Sec4_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec4_tiles.s4lz"
    align 2
OJZ_Sec5_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec5_tiles.s4lz"
    align 2
OJZ_Sec6_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec6_tiles.s4lz"
    align 2
OJZ_Sec7_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec7_tiles.s4lz"
    align 2
OJZ_Sec8_Tiles_S4LZ: BINCLUDE "data/generated/ojz/act1/sec8_tiles.s4lz"
    align 2
