; OJZ Act 1 level descriptor and section tables (§4 Phase 1, §2 A.3)
; Act struct defined in structs.asm. Generated data in data/generated/ojz/act1/ (gitignored).

; Act-wide paged art pool (auto-generated by tools/ojz_strip_gen.py + build.sh)
; Manifest: OJZ_ACT_POOL_PAGES / OJZ_ACT_POOL_TILES + per-page SLOT/TILES equates.
; Pool: OJZ_Act_Pool_Page0..N + OJZ_Act_Pool_PageTable (dc.l page addresses).
    include "data/generated/ojz/act1/ojz_act_pool_manifest.asm"
    include "data/generated/ojz/act1/ojz_act_pool.asm"

; Per-section block dictionary lengths (auto-generated by tools/ojz_block_gen.py)
; Dict region = K raw 768-byte blocks at SecN_Blocks + BLOCK_INDEX_SIZE.
    include "data/generated/ojz/act1/sec_block_dicts.asm"

; -----------------------------------------------
; OJZ Act 1 — descriptor and section table
; 9 sections (sec0–sec8) in a 3×3 grid
; -----------------------------------------------
; Build assert: grid_w*grid_h must fit within MAX_ACT_SECTIONS.
; Literals below must match the grid_w/grid_h dc.w values in the descriptor below.
    if 3*3 > MAX_ACT_SECTIONS
      error "OJZ act 1 grid (3x3) exceeds MAX_ACT_SECTIONS"
    endif
; Build assert: the camera/player clamps (camera.asm .clamp_x/.clamp_y,
; Player_LevelBound) compute each axis extent as grid<<SECTION_SIZE_SHIFT and
; clamp in WORD width — so an axis extent must fit $FFFF (~16 sections at
; SECTION_SIZE 2048). A taller/wider act would silently WRAP the clamp (the
; camera scrolling past a wrapped bound) rather than fail. Catch it at build.
; (Literal grid below; matches the grid_w/grid_h dc.w values.)
    if (3 << SECTION_SIZE_SHIFT) > $FFFF
      error "OJZ act 1 axis extent (grid 3 << SECTION_SIZE_SHIFT) exceeds $FFFF — word-width clamp math would wrap; widen the clamp ops before growing past ~16 sections"
    endif

OJZ_Act1_Descriptor:
    dc.l    OJZ_Act1_Sections       ; sec_grid_ptr
    dc.w    3                       ; grid_w (3 sections wide)
    dc.w    3                       ; grid_h (3 sections tall)
    dc.w    $0100                   ; start_local_x: 256px into section 0
    dc.w    $0100                   ; start_local_y: 256px into section (ground level)
    dc.b    0                       ; start_sec_x = 0
    dc.b    0                       ; start_sec_y = 0
    ; (cam_min_x/cam_max_x + cam_min_y/cam_max_y removed: both clamps are
    ;  grid-derived now — level_width/height = grid << SECTION_SIZE_SHIFT —
    ;  see Act struct and .clamp_x/.clamp_y in camera.asm)
    dc.l    OJZ_Act1_BG_Layout      ; act_bg_layout (§2 A.5 T1 zone-wide BG nametable)
    dc.l    OJZ_Act1_BG_Tiles       ; act_bg_tiles  (§2 A.5 T1 shared BG tile blob)
    dc.l    ParallaxConfig_OJZ_Default ; act_parallax_config (fallback for sections with NULL config)
    dc.l    OJZ_Act_Pool_PageTable  ; act_art_pool_table (Act Art Streaming Phase 1)
    dc.w    OJZ_ACT_POOL_PAGES      ; act_art_pool_pages
    dc.b    EDGE_CLAMP              ; edge_mode (Phase 2 §10; OJZ ships CLAMP)
    dc.b    0                       ; reserved (pad)
    ; Guard: the emitted descriptor must be exactly Act_len bytes (* = end-of-data
    ; location counter). Catches any future field add/remove/reorder that drifts the
    ; data from the Act struct (a silent mismatch would mis-parse every later field).
    if (*-OJZ_Act1_Descriptor) <> Act_len
      error "OJZ Act1 descriptor is \{*-OJZ_Act1_Descriptor} bytes, Act struct is \{Act_len} — descriptor/struct drift"
    endif
    align 2

; -----------------------------------------------
; Section definition table — 9 entries × $48 bytes (Sec_len)
; Grid layout (3×3):  Row 0 = Sec0,Sec1,Sec2 (unique art)
;                     Row 1 = Sec3,Sec4,Sec5 (clone Sec0 art, distinct sky tint)
;                     Row 2 = Sec6,Sec7,Sec8 (clone Sec0 art, distinct sky tint)
; -----------------------------------------------
OJZ_Act1_Sections:

OJZ_Sec0:
    dc.l    OJZ_Sec0_Blocks          ; sec_block_index (§4.7 2D)
    dc.l    OJZ_Sec0_Objects        ; sec_objects
    dc.l    OJZ_Sec0_Rings          ; sec_rings
    dc.l    0                       ; sec_plc
    dc.l    OJZ_Palette             ; sec_pal
    dc.l    0, 0    ; sec_parallax_config = act default (was caves T15 fixture; superseded by Deep Forest BG)
    dc.l    0                       ; sec_bg_layout (NULL = use Act_act_bg_layout, T1)
    dc.l    OJZ_Sec0_TypeTable      ; sec_type_table (§4.9)
    dc.l    0, 0                    ; sec_pal_cycle, sec_sound_bank
    dc.l    OJZ_Sec0_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0                    ; sec_flags, sec_music
    dc.b    0, 0, 0, 0              ; reserved bytes
    dc.w    OJZ_SEC0_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec1:
    dc.l    OJZ_Sec1_Blocks
    dc.l    OJZ_Sec1_Objects        ; sec_objects
    dc.l    OJZ_Sec1_Rings          ; sec_rings
    dc.l    0                       ; sec_plc
    dc.l    OJZ_Palette
    dc.l    0, 0  ; sec_parallax_config = act default (was windy F3 fixture; superseded by Deep Forest BG)
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec1_TypeTable      ; sec_type_table (§4.9)
    dc.l    0, 0                    ; sec_pal_cycle, sec_sound_bank
    dc.l    OJZ_Sec1_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC1_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec2:
    dc.l    OJZ_Sec2_Blocks
    dc.l    OJZ_Sec2_Objects        ; sec_objects
    dc.l    OJZ_Sec2_Rings          ; sec_rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0      ; sec_parallax_config = act default (was sky-haze demo; superseded by Deep Forest BG)
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec2_TypeTable      ; sec_type_table (§4.9)
    dc.l    0, 0
    dc.l    OJZ_Sec2_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC2_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec3:
    dc.l    OJZ_Sec3_Blocks
    dc.l    OJZ_Sec3_Objects
    dc.l    OJZ_Sec3_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0    ; sec_parallax_config = act default (was LockedClouds fixture — locked
                    ; vscroll + screen-space bands fought the Deep Forest vertical parallax)
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec3_TypeTable
    dc.l    0, 0
    dc.l    OJZ_Sec3_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC3_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec4:
    dc.l    OJZ_Sec4_Blocks
    dc.l    OJZ_Sec4_Objects
    dc.l    OJZ_Sec4_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec4_TypeTable
    dc.l    0, 0
    dc.l    OJZ_Sec4_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC4_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec5:
    dc.l    OJZ_Sec5_Blocks
    dc.l    OJZ_Sec5_Objects
    dc.l    OJZ_Sec5_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec5_TypeTable
    dc.l    0, 0
    dc.l    OJZ_Sec5_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC5_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec6:
    dc.l    OJZ_Sec6_Blocks
    dc.l    OJZ_Sec6_Objects
    dc.l    OJZ_Sec6_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec6_TypeTable
    dc.l    0, 0
    dc.l    OJZ_Sec6_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC6_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec7:
    dc.l    OJZ_Sec7_Blocks
    dc.l    OJZ_Sec7_Objects
    dc.l    OJZ_Sec7_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec7_TypeTable
    dc.l    0, 0
    dc.l    OJZ_Sec7_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC7_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

OJZ_Sec8:
    dc.l    OJZ_Sec8_Blocks
    dc.l    OJZ_Sec8_Objects
    dc.l    OJZ_Sec8_Rings
    dc.l    0
    dc.l    OJZ_Palette
    dc.l    0, 0
    dc.l    0                       ; sec_bg_layout (NULL = T1 default)
    dc.l    OJZ_Sec8_TypeTable
    dc.l    0, 0
    dc.l    OJZ_Sec8_Blocks+BLOCK_INDEX_SIZE ; sec_block_dict (raw dict region)
    dc.l    0, 0                    ; sec_anim_blocks, sec_collision_s4lz
    dc.w    0, 0
    dc.b    0, 0, 0, 0
    dc.w    OJZ_SEC8_BLOCK_DICT_LEN ; sec_block_dict_len
    align 2

; -----------------------------------------------
; Generated block data — 16×16 blocks, S4LZ compressed (§4.7 2D)
; OJZ_Sec{N}_Blocks labels live in the generated include: identical blobs
; are stored once and duplicate sections alias via equ (content dedup).
; -----------------------------------------------
    include "data/generated/ojz/act1/sec_block_blobs.asm"

OJZ_Palette: BINCLUDE "data/generated/ojz/act1/ojz_palette.bin"
    align 2

; Shared/HUD palette (CRAM line 0) — sonic_hack convention for level rendering.
BGND_Palette: BINCLUDE "art/palettes/SonicAndTails.bin"
    align 2

; Zone-wide BG layout + shared BG tile blob (§2 A.5 T1)
OJZ_Act1_BG_Layout: BINCLUDE "data/generated/ojz/act1/zone_bg.bin"
    align 2
OJZ_Act1_BG_Tiles:  BINCLUDE "data/generated/ojz/act1/bg_tiles.bin"
    align 2

; Camera-driven BG tile animation banks (generated; TileCount=0 stub when none)
    include "data/generated/ojz/act1/bg_anim.asm"
    align 2

; Per-section tile blobs removed (Act Art Streaming Phase 1): the act-wide
; paged art pool (OJZ_Act_Pool_Page* / OJZ_Act_Pool_PageTable) is now included
; at the top of this file via ojz_act_pool.asm.
