#!/bin/bash
set -euo pipefail

# sonic4 prebuild — game content generators. Invoked by build.sh from repo root.
TOOLS="${TOOLS:-tools}"

echo "Importing Sonic & Knuckles collision shape set (fixed 252-shape vocabulary)..."
python3 "${TOOLS}/import_sk_collision.py"

echo "Generating OJZ section data..."
python3 "${TOOLS}/ojz_strip_gen.py" generate

# Editor-authored BG override (level editor art) — replaces the generated
# zone BG when games/sonic4/data/editor_bg_override.json exists.
if [[ -f games/sonic4/data/editor_bg_override.json ]]; then
    python3 "${TOOLS}/inject_editor_bg.py"
fi

# Act art pool pages → ZX0 (load-time tier). The generator emits the
# globally-deduped act art pool split into fixed-size pages of ART_POOL_PAGE_TILES
# (256) tiles = 8192 B each. Each .zx0 carries the project's 4-byte wrapper
# [u16 BE uncompressed size][u8 flags=0][u8 version=2] ahead of the raw salvador
# (modern/V2) stream — the loader peeks the size for DMA and dispatches the
# decompressor on the version byte.
#
# Size guard: a single page must not exceed one VRAM page worth of tiles
# (ART_POOL_PAGE_BYTES). The generator should never emit an oversized page; a
# page larger than this is a generator bug and would overrun the page's VRAM
# slot at load time — fail the build.
ART_POOL_PAGE_BYTES=8192      # ART_POOL_PAGE_TILES (256) * 32
# Page count comes from the generator's manifest — pages are addressed by
# NUMERIC index (act_pool_page${k}), never by glob, so ordering is correct at
# any page count (a glob puts page10 before page2) and stale leftover pages
# from a previously larger pool are never compressed or bundled.
POOL_DIR="games/sonic4/data/generated/ojz/act1"
POOL_MANIFEST="${POOL_DIR}/ojz_act_pool_manifest.asm"
POOL_PAGES=$(sed -n 's/^OJZ_ACT_POOL_PAGES = \([0-9]\+\)$/\1/p' "$POOL_MANIFEST")
if [[ -z "$POOL_PAGES" ]]; then
    echo "ERROR: could not read OJZ_ACT_POOL_PAGES from ${POOL_MANIFEST}."; exit 1
fi
echo "Compressing ${POOL_PAGES} act art pool pages with ZX0 (salvador)..."
rm -f "${POOL_DIR}"/act_pool_page*.zx0 "${POOL_DIR}"/act_pool_page*.zx0.tmp
for (( k = 0; k < POOL_PAGES; k++ )); do
    page_bin="${POOL_DIR}/act_pool_page${k}.bin"
    page_zx0="${page_bin%.bin}.zx0"
    if [[ ! -f "$page_bin" ]]; then
        echo "ERROR: ${page_bin} missing but manifest declares ${POOL_PAGES} pages."; exit 1
    fi
    size=$(stat -c%s "$page_bin")
    if (( size > ART_POOL_PAGE_BYTES )); then
        echo "ERROR: ${page_bin} is ${size} B — exceeds one page (${ART_POOL_PAGE_BYTES})."; exit 1
    fi
    "${TOOLS}/bin/salvador" "$page_bin" "${page_zx0}.tmp" > /dev/null
    printf '%b' "$(printf '\\x%02x\\x%02x\\x00\\x02' $((size >> 8)) $((size & 255)))" > "$page_zx0"
    cat "${page_zx0}.tmp" >> "$page_zx0"; rm -f "${page_zx0}.tmp"
done

# Emit the act art pool include: page BINCLUDEs followed by a long-word
# address table the loader indexes by page number. The act descriptor includes
# this file instead of BINCLUDE-ing per-section blobs.
echo "Emitting act art pool include..."
POOL_ASM="${POOL_DIR}/ojz_act_pool.asm"
{
  echo "; Auto-generated by build.sh — act art pool page BINCLUDEs + address table"
  for (( k = 0; k < POOL_PAGES; k++ )); do
    echo "OJZ_Act_Pool_Page${k}:"
    echo "        BINCLUDE \"${POOL_DIR}/act_pool_page${k}.zx0\""
    echo "        align 2"
  done
  echo "OJZ_Act_Pool_PageTable:"
  for (( k = 0; k < POOL_PAGES; k++ )); do echo "        dc.l    OJZ_Act_Pool_Page${k}"; done
} > "$POOL_ASM"

echo "Generating OJZ block data..."
python3 "${TOOLS}/ojz_block_gen.py" generate

# seam-2 stage-2d: the SFX .asm twins (sfx_NN{,_patches}.asm, sfx_table.asm,
# sfx_blob_win_tab.asm) are DELETED — sfx_bank.emp is the canonical source and
# sigil BINCLUDEs sfx_bank{,_debug}.bin + sfx_blob_win_tab{,_debug}.bin. The
# committed sfx_NN{,_patches}.bin are sfx_bank.emp's embed() sources; to reseed
# them from the S3K disasm run `sfx_transcode.py generate --emit-bin` by hand
# (now a MANUAL generator, like the Moving-Trucks / gen_sound_tables ones).
