#!/usr/bin/env python3
"""The OJZ act's section grid: ONE source, cross-checked against the engine.

WHY THIS MODULE EXISTS (2026-09-12 gap lens sweep, F2). The act's section count was
stated four times: project.json's gridWidth x gridHeight (what tools/ojz_strip_gen.py
bakes from), the engine's `GRID_W` / `GRID_H` in the act descriptor, and two literal
`NUM_SECTIONS = 9`s, in tools/ojz_block_gen.py and tools/verify_level_bin.py. A
missing section file slipped between them: the strip baker skipped it with a warning,
the local-map table came out one entry short, the block baker re-baked the missing
section from the previous bake's strips at its literal 9, and the gate checked its
own literal 9 against files that were all still on disk. Exit 0 everywhere, and the
engine read the next table's first long as section 8's local map.

THE ONE SOURCE is project.json's `gridWidth` x `gridHeight` for zones[0].acts[0] —
the file Aurora writes and the strip baker already read. Every tool that needs the
count calls `section_grid()`, and that call also REQUIRES the grid THE ENGINE COMPILES
to agree. The engine indexes the baked `OJZ_Sec_LocalMaps` table by flat id over ITS
grid, so a project.json that disagreed would bake a table the engine over- or
under-reads — the same NULL-map read, reached from the other file.

⚠ WHERE THE ENGINE'S GRID LIVES MOVED ON 2026-09-17 (S2-COMPRESSED-ACT parcel 9), and
this module both moved it and reads it. It used to be two hand-typed lines,
`const GRID_W` / `const GRID_H`, in
games/sonic4/data/levels/ojz/act1/act_descriptor.emp — a file the S2CLIP throwaway bake
cannot write, which is exactly why a clip act could never declare a grid of its own and
was capped at the shipped act's 6,144 px. The grid is now GENERATED from project.json
into games/sonic4/data/generated/ojz/act1/act_grid.emp (`emit()` below), and the
descriptor reads it (`const GRID_W = OJZ_ACT_GRID_W`).

That makes `section_grid()`'s cross-check look tautological and it is NOT, because the
two things it compares are not the same file: project.json is what the BAKE is about to
bake, and act_grid.emp is what the ENGINE last compiled. They disagree exactly when an
edit to project.json has not been re-emitted — which is the F2 staleness above, in its
new location. What the check genuinely can no longer catch is somebody hand-typing a
different grid into the descriptor, because there is no longer a number there to type.

Stdlib only and donor-free: tools/verify_level_bin.py runs on every canonical build,
on machines that have no donor checkout, and imports this.
"""

import json
import os
import re

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
PROJECT_JSON = os.path.join(ROOT, "project.json")
ACT_DESCRIPTOR = os.path.join(
    ROOT, "games", "sonic4", "data", "levels", "ojz", "act1", "act_descriptor.emp")
#: The GENERATED module the engine's act descriptor takes its grid from. `descriptor`
#: arguments below name THIS file, not ACT_DESCRIPTOR: the name is kept because every
#: caller spells it, and because what it still means — "the grid the engine compiles" —
#: did not change when the file did.
ACT_GRID_EMP = os.path.join(
    ROOT, "games", "sonic4", "data", "generated", "ojz", "act1", "act_grid.emp")

EMIT_HEADER = """\
// AUTO-GENERATED by tools/act_grid.py — DO NOT EDIT.
//
// THE ACT'S SECTION GRID, lowered from project.json's zones[0].acts[0]
// gridWidth x gridHeight. games/sonic4/data/levels/ojz/act1/act_descriptor.emp reads
// these two names (`const GRID_W = OJZ_ACT_GRID_W`) instead of hand-typing the numbers,
// so the grid the engine compiles and the grid the bakers bake from are ONE statement.
//
// Why that matters beyond tidiness, and what re-aimed R21 still catches, is written out
// in tools/act_grid.py's module docstring and in the descriptor's own `const GRID_W`
// banner. The short version: the S2CLIP throwaway bake can write this file and cannot
// write the descriptor, so a clip act can now declare its own grid.
//
// THE SECTION-TABLE ARITY IS A SEPARATE FACT, checked separately — the descriptor
// `ensure`s its composed [Sec; N] is exactly GRID_W x GRID_H rows.

module games.sonic4.ojz_act_grid_act1

"""


def emit(grid_w: int, grid_h: int, path: str = ACT_GRID_EMP) -> str:
    """Write the generated grid module. Returns the text written.

    Idempotent and byte-stable: the same grid produces the same bytes, so a re-bake
    that changes nothing leaves this file untouched in `git status`.
    """
    if int(grid_w) < 1 or int(grid_h) < 1:
        raise ActGridError(f"act grid {grid_w}x{grid_h} has a zero axis")
    text = (EMIT_HEADER
            + f"pub const OJZ_ACT_GRID_W = {int(grid_w)}\n"
            + f"pub const OJZ_ACT_GRID_H = {int(grid_h)}\n")
    old = None
    if os.path.isfile(path):
        old = open(path, "r").read()
    if old != text:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(text)
    return text


def emit_from_project(project_json: str = PROJECT_JSON,
                      path: str = ACT_GRID_EMP) -> tuple[int, int]:
    """Lower project.json's act grid into the generated module. Returns (w, h)."""
    _zone, act = project_act(project_json)
    w, h = int(act["gridWidth"]), int(act["gridHeight"])
    emit(w, h, path)
    return w, h


class ActGridError(ValueError):
    """The act grid cannot be read, or its two statements disagree."""


def project_act(project_json: str = PROJECT_JSON) -> tuple[dict, dict]:
    """(zone, act) for zones[0].acts[0] of project.json — the OJZ act the bakers bake."""
    with open(project_json, "r") as f:
        proj = json.load(f)
    zone = proj["zones"][0]
    return zone, zone["acts"][0]


def descriptor_grid(descriptor: str = ACT_GRID_EMP) -> tuple[int, int]:
    """(GRID_W, GRID_H) as the ENGINE compiles them — i.e. out of act_grid.emp.

    Parsed, not assembled: literal `pub const OJZ_ACT_GRID_W = <int>` lines. A module
    that stops declaring them that way RAISES rather than falling back to project.json,
    because a fallback here is the one-sided agreement this module exists to replace.

    The parameter is still named `descriptor` because that is what every caller spells
    and what the value still MEANS. It names act_grid.emp since parcel 9; the descriptor
    itself carries no number to read.
    """
    if not os.path.isfile(descriptor):
        raise ActGridError(f"generated act grid {descriptor} missing — cannot read the "
                           f"engine's GRID_W/GRID_H to check project.json against. "
                           f"Emit it: python3 tools/act_grid.py emit")
    text = open(descriptor, "r").read()
    got = {}
    for name in ("OJZ_ACT_GRID_W", "OJZ_ACT_GRID_H"):
        m = re.search(rf"^pub const {name} = (\d+)\s*$", text, re.M)
        if not m:
            raise ActGridError(
                f"{descriptor} no longer declares `pub const {name} = <int>` — the act "
                f"grid moved; re-derive tools/act_grid.py's reader rather than guessing")
        got[name] = int(m.group(1))
    return got["OJZ_ACT_GRID_W"], got["OJZ_ACT_GRID_H"]


def section_grid(project_json: str = PROJECT_JSON,
                 descriptor: str = ACT_GRID_EMP) -> tuple[int, int]:
    """(grid_w, grid_h) from project.json, refused unless the engine agrees."""
    _zone, act = project_act(project_json)
    w, h = int(act["gridWidth"]), int(act["gridHeight"])
    if w < 1 or h < 1:
        raise ActGridError(f"project.json act grid {w}x{h} has a zero axis")
    dw, dh = descriptor_grid(descriptor)
    if (w, h) != (dw, dh):
        raise ActGridError(
            f"project.json declares the act grid {w}x{h} but the engine's act "
            f"generated grid module ({descriptor}) declares "
            f"OJZ_ACT_GRID_W x OJZ_ACT_GRID_H = {dw}x{dh}. The "
            f"engine indexes OJZ_Sec_LocalMaps by flat id over ITS grid, so baking "
            f"{w * h} sections against a {dw * dh}-section engine ships a table it "
            f"over- or under-reads. Change both, together.")
    return w, h


def section_count(project_json: str = PROJECT_JSON,
                  descriptor: str = ACT_GRID_EMP) -> int:
    """GRID_W * GRID_H — the number of sections every per-section artifact covers."""
    w, h = section_grid(project_json, descriptor)
    return w * h


USAGE = """Usage:
    python3 tools/act_grid.py emit      # lower project.json's grid into act_grid.emp
    python3 tools/act_grid.py check     # print the grid, refusing a disagreement"""


def _mode_emit(rest):
    if rest:
        print(f"ERROR: unknown argument {rest[0]!r}")
        print(USAGE)
        return 1
    w, h = emit_from_project()
    print(f"act grid {w}x{h} -> {os.path.relpath(ACT_GRID_EMP, ROOT)}")
    return 0


def _mode_check(rest):
    if rest:
        print(f"ERROR: unknown argument {rest[0]!r}")
        print(USAGE)
        return 1
    w, h = section_grid()
    print(f"act grid {w}x{h} = {w * h} sections "
          f"(project.json == the generated act_grid.emp the engine compiles)")
    return 0


# ONE list of legal modes, and it is the dispatch table (LS-15d shape,
# tools/test_cli_dispatch_refuses.py). `emit` WRITES a tracked file
# (games/sonic4/data/generated/ojz/act1/act_grid.emp) that the engine compiles and the
# whole-ROM byte gate watches, so an unknown mode must never reach it: a fall-through into
# `emit` on a typo would rewrite the act's grid from whatever project.json happened to say.
# `check` writes nothing but must not run unasked either — it is the mode a caller reaches
# by accident, and a printed verdict nobody requested reads like a pass.
MODES = {
    "emit": _mode_emit,
    "check": _mode_check,
}


def main(argv=None):
    import sys
    args = list(sys.argv[1:] if argv is None else argv)
    handler = MODES.get(args[0] if args else None)
    if handler is None:
        print(USAGE)
        sys.exit(1)
    return handler(args[1:])


if __name__ == "__main__":
    import sys
    sys.exit(main())
