#!/usr/bin/env python3
"""bganim_vprobe_gen — the eight VERTICALLY pre-shifted phase banks for the BgAnim
vertical-axis probe band (EFFECTS-W1 item 8, the on-screen half).

WHAT THIS IS AND WHAT IT IS NOT
-------------------------------
This is NOT an authoring tool and it is NOT a second writer for the owner's background.
It generates a small, self-contained, DEBUG-tier band whose only purpose is that a ROM
can be built with a band whose `axis` is genuinely VERTICAL and that band can be watched
moving. The act's authored background (`games/sonic4/data/editor_bg_override.json`) is
NOT touched, NOT read and NOT regenerated by this file — that document carries `anims`
and `tools/forest_bg_gen.py` refuses by name to rewrite it; fitting a band into it would
mean renumbering all 4,096 of its layout words, which is the owner's call and not a
tool's. See docs/DEFERRED_WORK.md, EFFECTS-W1 item 8.

THE GEOMETRY, AND WHY EVERY NUMBER IS FORCED
--------------------------------------------
`BgAnim_Update` (engine/level/bg_anim.emp) is axis-agnostic. A band's axis lives in two
places the engine never sees: how the eight banks were pre-shifted, and the order the
band's slots sit in. For the VERTICAL arm (see the BAND_AXES block in
tools/inject_editor_bg.py, which is the emitter-side authority):

    rotation unit  = COLS * 32 bytes   ->  col_shift  = log2(COLS * 32)
    pattern period = ROWS * 8  pixels  ->  step_mask  = ROWS * 8 - 1
    slot order     = ROW-MAJOR, slot j = (j // COLS, j % COLS)
    bank k         = phase 0 rolled UP by k px within ROWS*8

Both `col_shift` and `step_mask` are consumed as a shift and an AND mask, so COLS and
ROWS*8 must each be a power of two; `units * unit_bytes == tile_count * 32` (the
invariant that keeps BgAnim_Update's piece-1 length positive) then holds by construction:
ROWS * (COLS*32) == (COLS*ROWS) * 32.

WHY 2 x 4 = 8 TILES, DERIVED RATHER THAN PICKED
-----------------------------------------------
The `ojz_bg_anim` section's ruled authoring ceiling is 12,288 B and the live act already
spends 8,238 B in the release shape (2 + 44 + 8192) plus 92 B of debug view twins. A band
costs 8 phases * tiles * 32 = 256 B per tile, so the room left over caps a second band at
15 tiles. Of the (COLS, ROWS) pairs that are both powers of two and fit under 15 tiles,
2 x 4 is the one that leaves BOTH arms of the axis comparison non-degenerate:

  * 1 x 8 and 8 x 1 are rejected: with one unit on an axis the coarse rotate is
    (step>>3) << log2(total_bytes), which is 0 mod total_bytes for every step — the
    horizontal control arm would be a rotate that never rotates, i.e. no control at all.
  * 2 x 2 (4 tiles) works but gives the vertical arm only a 16 px period.
  * 2 x 4 gives vertical: unit 64 B (2 slots), period 32 px, 4 coarse positions
                horizontal: unit 128 B (4 slots), period 16 px, 2 coarse positions
    — the two arms differ in BOTH record fields, which is what lets a witness ask
    "does it move on the axis the record declares" instead of only "does it move".

THIS FILE ALSO OWNS THE PROBE MODULE'S GEOMETRY CONSTANTS. games/sonic4/test/
bganim_vprobe.emp spells the same six numbers in its two records; tools/
test_bganim_vprobe.py reads both and fails the build's pytest lane on any disagreement,
so they are gated rather than synchronised by hand.

ART CONTRACT (asserted here, not hoped for)
-------------------------------------------
The picture must make BOTH arms discriminating, so the generator refuses art that would
make the measurement vacuous:
  * all ROWS*8 pixel rows distinct — otherwise some vertical roll is a no-op and a
    frozen band would pass the vertical predicate;
  * all COLS*8 pixel columns distinct — otherwise the HORIZONTAL control arm would be a
    no-op on the pixels, and "the control failed" would be about the art rather than
    about the axis.
Both are checked and both are loud.

Usage:
    python3 tools/bganim_vprobe_gen.py            # write the blob
    python3 tools/bganim_vprobe_gen.py --check    # verify the on-disk blob matches
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "games/sonic4/data/generated/bganim_vprobe_banks.bin"

# ── the band geometry (the .emp records mirror these; test_bganim_vprobe.py gates it) ──
COLS = 2
ROWS = 4
TILES = COLS * ROWS                     # 8
BANKS = 8                               # BGANIM_BANKS — 8 pre-shifted phases, 1 px apart
W = COLS * 8                            # 16 px
H = ROWS * 8                            # 32 px
TILE_BYTES = 32
BLOB_BYTES = BANKS * TILES * TILE_BYTES  # 2048

# Derived record fields — the single derivation, mirrored by the .emp and gated.
V_COL_SHIFT = (COLS * 32).bit_length() - 1      # log2(64)  = 6
V_STEP_MASK = H - 1                             # 31
H_COL_SHIFT = (ROWS * 32).bit_length() - 1      # log2(128) = 7
H_STEP_MASK = W - 1                             # 15

# VRAM destination: the BG region's BAND RESERVE, not the act's live tiles.
# games/sonic4/vram.toml pins bg_region at slot 1024 (byte $8000) for 448 tiles with
# `band_reserve = 128` withheld from the static importer; the shipped static blob is
# 320 tiles (bg_tiles.bin = 2 + 320*32), so slots 1024+320 = 1344 upward are reserved
# and no other writer touches them. 1344 * 32 = $A800. Aiming the probe here rather
# than at the act's live band base ($8000) keeps the owner's picture intact AND keeps
# the witness free of a confound: nothing else in the engine writes this run.
VPROBE_VRAM_DEST = (1024 + 320) * 32            # $A800


def picture():
    """The 16 x 32 4bpp phase-0 image, as `P[y][x]` colour indices 1..15.

    A chevron that points UP with a per-row brightness ramp: the ramp makes every pixel
    row distinct, the chevron's x-dependence makes every pixel column distinct, and
    together they mean a reader can tell at a glance which way it travelled. Colour 0
    is avoided throughout so the band is opaque wherever it is placed.
    """
    P = [[0] * W for _ in range(H)]
    for y in range(H):
        ramp = 1 + (y * 13) % 7                  # 1..7, period 7 — coprime with 32
        for x in range(W):
            # distance from the chevron's apex, which walks with y
            d = abs(x - (y % W))
            P[y][x] = ramp + 8 if d < 2 else ramp
    return P


def check_art(P):
    """Refuse art that would make either arm of the axis comparison vacuous."""
    rows = [tuple(r) for r in P]
    cols = [tuple(P[y][x] for y in range(H)) for x in range(W)]
    problems = []
    if len(set(rows)) != H:
        problems.append(f"only {len(set(rows))} of {H} pixel ROWS are distinct — some "
                        "vertical roll is a no-op, so a frozen band would pass the "
                        "vertical predicate")
    if len(set(cols)) != W:
        problems.append(f"only {len(set(cols))} of {W} pixel COLUMNS are distinct — the "
                        "horizontal control arm would be a no-op on the pixels, and its "
                        "failure would then be about the art rather than about the axis")
    if any(P[y][x] == 0 for y in range(H) for x in range(W)):
        problems.append("colour 0 appears — the band would be transparent in places")
    if problems:
        raise SystemExit("bganim_vprobe_gen: ART CONTRACT VIOLATED\n  - " +
                         "\n  - ".join(problems))


def tile_bytes(P, ty, tx):
    """One 8x8 4bpp Genesis tile out of `P`: 4 bytes per row, high nibble = left pixel."""
    out = bytearray()
    for dy in range(8):
        y = ty * 8 + dy
        for dx in range(0, 8, 2):
            x = tx * 8 + dx
            out.append((P[y][x] << 4) | P[y][x + 1])
    return bytes(out)


def bank(P, k):
    """Bank k: phase 0 rolled UP by k px, serialised in ROW-MAJOR slot order.

    Rolled UP (toward decreasing y) because BgAnim_Update's coarse rotate carries that
    sign: it copies `bank + shift_bytes ..` to the band base, so an increasing driver
    walks the picture toward decreasing coordinate. Bank k must move the same way as
    the coarse step or the fine and coarse halves would fight at every 8 px boundary.
    """
    Pk = [P[(y + k) % H] for y in range(H)]
    out = bytearray()
    for j in range(TILES):
        out += tile_bytes(Pk, j // COLS, j % COLS)   # ROW-major: slot j = (row, col)
    return bytes(out)


def blob():
    P = picture()
    check_art(P)
    b = b"".join(bank(P, k) for k in range(BANKS))
    assert len(b) == BLOB_BYTES, f"blob is {len(b)} B, expected {BLOB_BYTES}"
    return b


def main(argv):
    b = blob()
    if "--check" in argv:
        if not OUT.exists():
            print(f"bganim_vprobe_gen --check: {OUT} is MISSING", file=sys.stderr)
            return 1
        on_disk = OUT.read_bytes()
        if on_disk != b:
            print(f"bganim_vprobe_gen --check: {OUT} is STALE "
                  f"({len(on_disk)} B on disk, {len(b)} B generated) — "
                  f"run `python3 tools/bganim_vprobe_gen.py`", file=sys.stderr)
            return 1
        print(f"bganim_vprobe_gen --check: OK — {OUT.name} matches "
              f"({len(b)} B, {BANKS} banks x {TILES} tiles)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(b)
    print(f"bganim_vprobe_gen: wrote {OUT} ({len(b)} B) — "
          f"{COLS}x{ROWS} tiles, vertical col_shift={V_COL_SHIFT} step_mask={V_STEP_MASK}, "
          f"horizontal control col_shift={H_COL_SHIFT} step_mask={H_STEP_MASK}, "
          f"vram_dest=${VPROBE_VRAM_DEST:04X}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
