#!/usr/bin/env python3
"""Inject an editor-authored background over the generated zone BG.

Reads data/editor_bg_override.json ({"layout": [2048 words, blob-local
tile indices], "tiles": [[64 px]...]}) and rewrites
data/generated/ojz/act1/zone_bg.bin + bg_tiles.bin in the engine's
conventions (VRAM-absolute indices at BG_TILE_BASE_SLOT, 2-byte BE
byte-length tile blob header).

Run by build.sh after ojz_strip_gen.py when the override file exists.
"""
import json, struct, os, sys

BG_TILE_BASE_SLOT = 1024
# constants.asm says 512, but the sprite table ($B800) and HScroll table
# ($BC00) live in the top of the $8000-$BFFF region — real art ceiling:
BG_TILE_CAPACITY = 448
OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'generated', 'ojz', 'act1')
OVERRIDE = os.path.join(os.path.dirname(__file__), '..', 'data', 'editor_bg_override.json')

def main():
    with open(OVERRIDE) as f:
        data = json.load(f)
    layout, tiles = data['layout'], data['tiles']

    # ---- HCZ-pillar tile-band animation, table-driven (up to 4 bands).
    # Each band's phase-0 tiles occupy a contiguous slot range starting at
    # slot_base (bands packed from slot 0, in list order), column-major so
    # whole-column rotation is two wrapped DMAs. Emit one concatenated banks
    # bin + a pure-data band table (engine reads it at runtime — act data
    # assembles after engine code, so no assemble-time conditionals).
    DRIVERS = {'camera_x': 0, 'camera_y': 1, 'timer': 2}
    anims = data.get('anims')
    if anims is None and data.get('anim'):
        anims = [data['anim']]                  # legacy single-band shape
    if anims:
        assert len(anims) <= 4, 'engine supports at most BGANIM_MAX_BANDS=4 bands'
        banks = bytearray()
        bands = []
        slot_cursor = 0
        for a in anims:
            cols, rows = a['cols'], a['rows']
            n = cols * rows
            pattern_px = a['pattern_px']
            col_bytes = rows * 32
            col_shift = col_bytes.bit_length() - 1
            assert (1 << col_shift) == col_bytes, 'column bytes must be a power of 2'
            assert pattern_px == cols * 8, 'pattern width must equal cols*8'
            slot_base = a.get('slot_base', slot_cursor)
            assert slot_base == slot_cursor, 'bands must pack contiguously from slot 0'
            slot_cursor += n
            strip_off = len(banks)
            for bank in a['phases']:
                assert len(bank) == n
                for t in bank:
                    for row in range(8):
                        for col in range(4):
                            hi = t[row*8 + col*2] & 0xF
                            lo = t[row*8 + col*2 + 1] & 0xF
                            banks.append((hi << 4) | lo)
            bands.append({
                'driver': DRIVERS[a.get('driver', 'camera_x')],
                'driver_name': a.get('driver', 'camera_x'),
                'rate_shift': a.get('rate_shift', 2),
                'step_mask': pattern_px - 1,
                'col_shift': col_shift,
                'tile_count': n,
                'slot_base': slot_base,
                'bank_offsets': [strip_off + ph * n * 32 for ph in range(len(a['phases']))],
            })
        with open(os.path.join(OUT_DIR, 'bg_anim_banks.bin'), 'wb') as f:
            f.write(banks)
        with open(os.path.join(OUT_DIR, 'bg_anim.asm'), 'w') as f:
            f.write('; Auto-generated by tools/inject_editor_bg.py - DO NOT EDIT\n')
            f.write('; BG tile-band animation table (HCZ-pillar technique).\n')
            f.write('; Format documented in engine/level/bg_anim.asm.\n')
            f.write('BgAnim_Table:\n')
            f.write(f'    dc.w {len(bands)}\n')
            for b in bands:
                f.write(f'    ; band: {b["tile_count"]} tiles at BG slot {b["slot_base"]}, '
                        f'driver {b["driver_name"]}, 1px per {1 << b["rate_shift"]} units\n')
                f.write(f'    dc.w {b["driver"]}, {b["rate_shift"]}, {b["step_mask"]}, '
                        f'{b["col_shift"]}, {b["tile_count"]}, '
                        f'BG_TILE_BASE_VRAM+{b["slot_base"]*32}\n')
                for off in b['bank_offsets']:
                    f.write(f'    dc.l BgAnim_Banks+{off}\n')
            f.write('BgAnim_Banks:\n')
            f.write('    BINCLUDE "data/generated/ojz/act1/bg_anim_banks.bin"\n')
        print(f'[inject_editor_bg] anim: {len(bands)} band(s), {len(banks)} bytes of banks')
    else:
        # no animation: emit a disabled stub so the data include always resolves
        with open(os.path.join(OUT_DIR, 'bg_anim.asm'), 'w') as f:
            f.write('; Auto-generated stub - no BG animation in this build\n')
            f.write('BgAnim_Table:\n')
            f.write('    dc.w 0\n')
            f.write('BgAnim_Banks:\n')
    if len(layout) == 2048:
        layout = layout + [0]*2048          # legacy 32-row layout: pad to 64 rows
    assert len(layout) == 4096, f'layout must be 64x32 or 64x64 words, got {len(layout)}'
    assert len(tiles) <= BG_TILE_CAPACITY, f'{len(tiles)} tiles exceeds BG capacity {BG_TILE_CAPACITY}'

    # nametable: local -> VRAM-absolute indices, preserving pal/pri/flip bits
    nt = bytearray()
    for word in layout:
        if word != 0:
            idx = word & 0x7FF
            word = (word & ~0x7FF) | ((idx + BG_TILE_BASE_SLOT) & 0x7FF)
        nt += struct.pack('>H', word)
    with open(os.path.join(OUT_DIR, 'zone_bg.bin'), 'wb') as f:
        f.write(nt)

    # tile blob: BE byte-length header + raw 4bpp tiles
    blob = bytearray()
    for t in tiles:
        for row in range(8):
            for col in range(4):
                hi = t[row*8 + col*2] & 0xF
                lo = t[row*8 + col*2 + 1] & 0xF
                blob.append((hi << 4) | lo)
    with open(os.path.join(OUT_DIR, 'bg_tiles.bin'), 'wb') as f:
        f.write(struct.pack('>H', len(blob)))
        f.write(blob)
    print(f'[inject_editor_bg] wrote zone_bg.bin ({len(nt)}B) + bg_tiles.bin ({len(tiles)} tiles)')

if __name__ == '__main__':
    main()
