#!/usr/bin/env python3
"""OJZ block-format data generator.

Converts existing column-strip data (generated by ojz_strip_gen.py) into
16x16 tile blocks with embedded dual-layer collision, independently S4LZ-compressed.

Usage:
    python3 tools/ojz_block_gen.py generate
    python3 tools/ojz_block_gen.py test

Input:  data/generated/ojz/act1/sec{N}_strips_a.bin (raw strip files)
Output: data/generated/ojz/act1/sec{N}_blocks.bin (block index + compressed blocks)

Each output file contains:
  - 256 × 4 bytes = 1024-byte block index table
    (each entry is a byte offset from file start; 0 = empty/air block;
    bit 31 set = RAW DIRECT — the offset points at an uncompressed 768-byte
    block inside the dictionary region)
  - Dictionary region: K raw blocks (768*K bytes), serving double duty as
    their own storage AND as the LZ window pre-seed for every compressed
    block in the section (K swept 0..3 per section, minimum total size)
  - Concatenated S4LZ-compressed blocks (compressed with the dict window)

Also emits data/generated/ojz/act1/sec_block_dicts.asm with per-section
OJZ_SEC{N}_BLOCK_DICT_LEN constants for the act descriptor (the dict region
always starts at blob+1024; only its length varies).

Raw block layout (768 bytes = BLOCK_RAW_SIZE):
  Bytes   0–511:  512 bytes nametable (16×16 × 2 bytes, row-major)
  Bytes 512–639:  128 bytes collision plane A (16 cols × 8 rows × 1 byte, row-major)
  Bytes 640–767:  128 bytes collision plane B (copy of plane A for OJZ)

Strip binary layout consumed here (STRIP_BYTE_SIZE bytes per column):
  Bytes 0 .. STRIP_NT_BYTES-1                 : nametable words (big-endian)
  Bytes STRIP_NT_BYTES .. +STRIP_COLL_ROWS-1  : collision plane A bytes
  Bytes +STRIP_COLL_ROWS .. +2*STRIP_COLL_ROWS-1 : collision plane B bytes
  Bytes +2*STRIP_COLL_ROWS .. end             : padding
"""

import hashlib
import struct
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import s4lz

# Constants — must match constants.asm
SECTION_TILE_WIDTH = 256
SECTION_TILE_HEIGHT = 256
BLOCK_SIZE = 16
BLOCKS_PER_AXIS = SECTION_TILE_WIDTH // BLOCK_SIZE  # 16
BLOCKS_PER_SECTION = BLOCKS_PER_AXIS * BLOCKS_PER_AXIS  # 256
BLOCK_NT_SIZE = BLOCK_SIZE * BLOCK_SIZE * 2  # 512 bytes
BLOCK_COLL_COLS = BLOCK_SIZE  # 16 collision columns (1 per tile column)
BLOCK_COLL_ROWS = BLOCK_SIZE // 2  # 8 collision rows (16px cells)
BLOCK_COLL_PLANE_SIZE = BLOCK_COLL_COLS * BLOCK_COLL_ROWS  # 128 bytes per plane
BLOCK_COLL_SIZE = BLOCK_COLL_PLANE_SIZE * 2  # 256 bytes (plane A + plane B)
BLOCK_RAW_SIZE = BLOCK_NT_SIZE + BLOCK_COLL_SIZE  # 768 bytes

# Strip format (from ojz_strip_gen.py)
STRIP_TILE_HEIGHT = 256
STRIP_NT_BYTES = STRIP_TILE_HEIGHT * 2  # 512
STRIP_COLL_ROWS = STRIP_TILE_HEIGHT // 2  # 128 collision rows per plane
STRIP_COLL_OFFSET_A = STRIP_NT_BYTES          # 512: start of plane A collision
STRIP_COLL_OFFSET_B = STRIP_NT_BYTES + STRIP_COLL_ROWS  # 640: start of plane B collision
STRIP_PAD = 8
STRIP_BYTE_SIZE = STRIP_NT_BYTES + 2 * STRIP_COLL_ROWS + STRIP_PAD  # 776 bytes

BLOCK_INDEX_SIZE = BLOCKS_PER_SECTION * 4  # 1024 bytes
RAW_DIRECT_BIT = 0x80000000  # index entry bit 31: offset -> raw 768B block
MAX_DICT_BLOCKS = 3          # K sweep upper bound (sec_block_dict_len <= 3*768)

OUTPUT_DIR = os.path.join(
    os.path.dirname(__file__), "..", "data", "generated", "ojz", "act1"
)

NUM_SECTIONS = 9
SECTION_IDS = list(range(NUM_SECTIONS))


def load_raw_strips(section_idx):
    """Load raw (uncompressed) strip data for a section.

    Returns raw bytes — 128 bytes per column × 256 columns = 32768 bytes.
    """
    path = os.path.join(OUTPUT_DIR, f"sec{section_idx}_strips_a.bin")
    with open(path, "rb") as f:
        return f.read()


def parse_strips(raw_data):
    """Parse raw strip data into nametable grid + two collision grids.

    Returns:
        nametable:    2D list [row][col] of 16-bit tile words (256 rows × N cols)
        collision_a:  2D list [coll_row][col] of 8-bit collision bytes (128 rows × N cols), path A
        collision_b:  2D list [coll_row][col] of 8-bit collision bytes (128 rows × N cols), path B
    """
    num_cols = len(raw_data) // STRIP_BYTE_SIZE

    nametable = [[0] * num_cols for _ in range(STRIP_TILE_HEIGHT)]
    collision_a = [[0] * num_cols for _ in range(STRIP_COLL_ROWS)]
    collision_b = [[0] * num_cols for _ in range(STRIP_COLL_ROWS)]

    for col in range(num_cols):
        base = col * STRIP_BYTE_SIZE
        for row in range(STRIP_TILE_HEIGHT):
            word_off = base + row * 2
            nametable[row][col] = struct.unpack_from(">H", raw_data, word_off)[0]
        for cr in range(STRIP_COLL_ROWS):
            collision_a[cr][col] = raw_data[base + STRIP_COLL_OFFSET_A + cr]
            collision_b[cr][col] = raw_data[base + STRIP_COLL_OFFSET_B + cr]

    return nametable, collision_a, collision_b


def extract_block(nametable, collision_a, collision_b, block_x, block_y):
    """Extract one 16×16 block's data from the full section grids.

    Returns (nt_bytes, coll_a_bytes, coll_b_bytes):
        nt_bytes:      512 bytes — 16×16 tile words, row-major, big-endian
        coll_a_bytes:  128 bytes — 16 cols × 8 rows (path A), row-major
        coll_b_bytes:  128 bytes — 16 cols × 8 rows (path B), row-major
    """
    nt_data = bytearray(BLOCK_NT_SIZE)
    for row in range(BLOCK_SIZE):
        tile_row = block_y * BLOCK_SIZE + row
        for col in range(BLOCK_SIZE):
            tile_col = block_x * BLOCK_SIZE + col
            if tile_row < len(nametable) and tile_col < len(nametable[0]):
                word = nametable[tile_row][tile_col]
            else:
                word = 0
            offset = (row * BLOCK_SIZE + col) * 2
            struct.pack_into(">H", nt_data, offset, word)

    def extract_coll_plane(collision):
        coll_data = bytearray(BLOCK_COLL_PLANE_SIZE)
        for cr in range(BLOCK_COLL_ROWS):
            abs_coll_row = block_y * BLOCK_COLL_ROWS + cr
            for col in range(BLOCK_SIZE):
                tile_col = block_x * BLOCK_SIZE + col
                if abs_coll_row < len(collision) and tile_col < len(collision[0]):
                    byte = collision[abs_coll_row][tile_col]
                else:
                    byte = 0
                coll_data[cr * BLOCK_COLL_COLS + col] = byte
        return bytes(coll_data)

    return bytes(nt_data), extract_coll_plane(collision_a), extract_coll_plane(collision_b)


def select_dict_blocks(raw_blocks):
    """Rank non-empty blocks by 4-gram (word-pair) frequency coverage.

    Returns a list of block indices, best dictionary candidate first.
    A block's score is the sum, over its distinct 4-grams, of how many
    blocks in the section contain that gram — the block whose content is
    shared by the most other blocks scores highest.
    """
    blocks = [(i, b) for i, b in enumerate(raw_blocks) if b is not None]
    grams = {}
    gram_sets = {}
    for i, b in blocks:
        s = set(b[j:j + 4] for j in range(0, len(b) - 3, 2))
        gram_sets[i] = s
        for g in s:
            grams[g] = grams.get(g, 0) + 1
    scored = sorted(((sum(grams[g] for g in gram_sets[i]), -i) for i, _ in blocks),
                    reverse=True)
    return [-neg_i for _, neg_i in scored]


def generate_section_blocks(section_idx):
    """Generate block index + dict region + compressed blocks for one section.

    Returns (blob_bytes, dict_len, stats) where blob_bytes is
    [1024-byte index table][raw dict blocks][compressed v3 streams],
    dict_len = bytes of raw dictionary (768 * K), and stats is a dict
    with 'k' and 'total' (bytes after the index table).
    Each block expands to BLOCK_RAW_SIZE (768) bytes:
      512B nametable + 128B collision plane A + 128B collision plane B.
    """
    raw_data = load_raw_strips(section_idx)
    nametable, collision_a, collision_b = parse_strips(raw_data)

    raw_blocks = []
    for block_y in range(BLOCKS_PER_AXIS):
        for block_x in range(BLOCKS_PER_AXIS):
            nt_data, coll_a_data, coll_b_data = extract_block(
                nametable, collision_a, collision_b, block_x, block_y
            )
            raw_block = nt_data + coll_a_data + coll_b_data
            raw_blocks.append(None if all(b == 0 for b in raw_block)
                              else raw_block)

    non_empty = [i for i, b in enumerate(raw_blocks) if b is not None]
    ranking = select_dict_blocks(raw_blocks)

    # Sweep K = 0..MAX_DICT_BLOCKS dictionary blocks; pick minimum total.
    # Dict blocks are stored raw (768B each, their own storage) and every
    # other block is compressed with the dict as window pre-seed. The dict
    # is laid out best-block LAST so the highest-value content sits nearest
    # the data (smallest offsets -> most short-form matches).
    best = None  # (total, k, dict_indices, dict_bytes, streams)
    for k in range(0, min(MAX_DICT_BLOCKS, len(non_empty)) + 1):
        dict_indices = ranking[:k]
        dict_bytes = b''.join(raw_blocks[i] for i in reversed(dict_indices))
        streams = {}
        total = k * BLOCK_RAW_SIZE
        for i in non_empty:
            if i in dict_indices:
                continue
            comp = s4lz.compress(raw_blocks[i], dictionary=dict_bytes)
            streams[i] = comp
            total += len(comp) + (len(comp) % 2)
        if best is None or total < best[0]:
            best = (total, k, dict_indices, dict_bytes, streams)

    total, k, dict_indices, dict_bytes, streams = best
    dict_len = len(dict_bytes)

    # Dict region position of each dict block (reversed layout, see above)
    dict_pos = {idx: j for j, idx in enumerate(reversed(dict_indices))}

    index_table = bytearray(BLOCK_INDEX_SIZE)
    block_data = bytearray(dict_bytes)

    for i, raw in enumerate(raw_blocks):
        if raw is None:
            struct.pack_into(">I", index_table, i * 4, 0)
        elif i in dict_pos:
            offset = BLOCK_INDEX_SIZE + dict_pos[i] * BLOCK_RAW_SIZE
            struct.pack_into(">I", index_table, i * 4, RAW_DIRECT_BIT | offset)
        else:
            offset = BLOCK_INDEX_SIZE + len(block_data)
            struct.pack_into(">I", index_table, i * 4, offset)
            block_data.extend(streams[i])
            if len(block_data) % 2:
                block_data.append(0)

    stats = {"k": k, "total": total}
    return bytes(index_table) + bytes(block_data), dict_len, stats


def generate_all():
    """Generate block data for all OJZ sections."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    total_non_empty = 0
    total_blocks = 0
    dict_lens = []
    blob_owner = {}     # content hash -> first section index with that blob
    blob_lines = []     # generated include: BINCLUDE or equ alias per section
    dedup_saved = 0

    for sec_idx in SECTION_IDS:
        print(f"Section {sec_idx}...", end=" ", flush=True)
        output, dict_len, stats = generate_section_blocks(sec_idx)
        dict_lens.append(dict_len)

        index_data = output[:BLOCK_INDEX_SIZE]
        non_empty = sum(1 for i in range(BLOCKS_PER_SECTION)
                        if struct.unpack_from(">I", index_data, i * 4)[0] != 0)
        total_non_empty += non_empty
        total_blocks += BLOCKS_PER_SECTION

        out_path = os.path.join(OUTPUT_DIR, f"sec{sec_idx}_blocks.bin")
        with open(out_path, "wb") as f:
            f.write(output)

        # Content dedup: identical block blobs collapse to one BINCLUDE,
        # duplicate sections alias the owner's label (block staging is keyed
        # by section coordinates, not blob pointer, so sharing ROM is safe;
        # sec_block_dict = label + BLOCK_INDEX_SIZE also aliases correctly
        # since identical content implies identical dictionaries).
        digest = hashlib.sha256(output).hexdigest()
        owner = blob_owner.get(digest)
        if owner is None:
            blob_owner[digest] = sec_idx
            blob_lines.append(
                f"OJZ_Sec{sec_idx}_Blocks:\n"
                f"    BINCLUDE \"data/generated/ojz/act1/sec{sec_idx}_blocks.bin\"\n"
                f"    align 2")
        else:
            blob_lines.append(
                f"OJZ_Sec{sec_idx}_Blocks equ OJZ_Sec{owner}_Blocks"
                f"    ; identical to sec{owner}")
            dedup_saved += len(output)
        print(f"{len(output)} bytes (K={stats['k']} dict, "
              f"{non_empty}/{BLOCKS_PER_SECTION} non-empty blocks)"
              + (f" [deduped -> sec{owner}]" if owner is not None else ""))

    # Per-section dictionary lengths for the act descriptor (the dict region
    # always starts at blob + BLOCK_INDEX_SIZE; only the length varies).
    dicts_path = os.path.join(OUTPUT_DIR, "sec_block_dicts.asm")
    with open(dicts_path, "w") as f:
        f.write("; Per-section block dictionary lengths "
                "(auto-generated by tools/ojz_block_gen.py)\n")
        f.write("; Dict region = raw blocks at sec{N}_blocks.bin + 1024; "
                "0 = no dictionary.\n")
        for sec_idx, dlen in zip(SECTION_IDS, dict_lens):
            f.write(f"OJZ_SEC{sec_idx}_BLOCK_DICT_LEN = {dlen}\n")

    # Block blob BINCLUDEs with dedup aliases — included by the descriptor.
    blobs_path = os.path.join(OUTPUT_DIR, "sec_block_blobs.asm")
    with open(blobs_path, "w") as f:
        f.write("; Per-section block blob BINCLUDEs with content dedup "
                "(auto-generated by tools/ojz_block_gen.py)\n")
        f.write("; Identical blobs are stored once; duplicate sections "
                "alias via equ.\n")
        f.write("\n".join(blob_lines) + "\n")

    print(f"\nDone. {total_non_empty}/{total_blocks} total non-empty blocks "
          f"across {NUM_SECTIONS} sections; blob dedup saved "
          f"{dedup_saved} ROM bytes.")


# ---------------------------------------------------------------------------
# Self-tests
# ---------------------------------------------------------------------------

def test_parse_strips():
    """Verify strip parsing produces correct dimensions."""
    raw = load_raw_strips(0)
    nt, coll_a, coll_b = parse_strips(raw)
    assert len(nt) == STRIP_TILE_HEIGHT, f"Expected {STRIP_TILE_HEIGHT} rows, got {len(nt)}"
    assert len(nt[0]) == SECTION_TILE_WIDTH, f"Expected {SECTION_TILE_WIDTH} cols, got {len(nt[0])}"
    assert len(coll_a) == STRIP_COLL_ROWS, f"Expected {STRIP_COLL_ROWS} coll_a rows, got {len(coll_a)}"
    assert len(coll_a[0]) == SECTION_TILE_WIDTH
    assert len(coll_b) == STRIP_COLL_ROWS, f"Expected {STRIP_COLL_ROWS} coll_b rows, got {len(coll_b)}"
    assert len(coll_b[0]) == SECTION_TILE_WIDTH
    print("  test_parse_strips OK")


def test_extract_block():
    """Verify block extraction matches source data."""
    raw = load_raw_strips(0)
    nt, coll_a, coll_b = parse_strips(raw)

    # Block (0,0) should match the top-left 16×16 of the section
    nt_data, coll_a_data, coll_b_data = extract_block(nt, coll_a, coll_b, 0, 0)
    assert len(nt_data) == BLOCK_NT_SIZE
    assert len(coll_a_data) == BLOCK_COLL_PLANE_SIZE
    assert len(coll_b_data) == BLOCK_COLL_PLANE_SIZE

    # Check first tile word matches
    expected_word = nt[0][0]
    actual_word = struct.unpack_from(">H", nt_data, 0)[0]
    assert actual_word == expected_word, f"First word: expected 0x{expected_word:04X}, got 0x{actual_word:04X}"

    # Plane B should be identical to plane A (copy fallback for OJZ)
    assert coll_a_data == coll_b_data, "OJZ: plane B must be a copy of plane A"

    # Block (0, 15) should be entirely empty (last block row, typically air)
    nt_data_empty, coll_a_empty, coll_b_empty = extract_block(nt, coll_a, coll_b, 0, 15)
    assert all(b == 0 for b in nt_data_empty), "Block at row 15 should be all air"
    assert all(b == 0 for b in coll_a_empty), "Block coll_a at row 15 should be all zero"
    assert all(b == 0 for b in coll_b_empty), "Block coll_b at row 15 should be all zero"

    print("  test_extract_block OK")


def decode_block(blob, dict_len, block_idx):
    """Decode one block from a generated blob exactly as the runtime does.

    Returns 768 raw bytes, or None for an empty block."""
    entry = struct.unpack_from(">I", blob, block_idx * 4)[0]
    if entry == 0:
        return None
    dictionary = blob[BLOCK_INDEX_SIZE:BLOCK_INDEX_SIZE + dict_len]
    if entry & RAW_DIRECT_BIT:
        offset = entry & ~RAW_DIRECT_BIT
        assert offset >= BLOCK_INDEX_SIZE, f"raw offset {offset} inside index"
        assert offset + BLOCK_RAW_SIZE <= BLOCK_INDEX_SIZE + dict_len, (
            f"raw block at {offset} escapes the dict region")
        return blob[offset:offset + BLOCK_RAW_SIZE]
    return s4lz.decompress(blob[entry:], dictionary=dictionary)


def test_generate_roundtrip():
    """Verify EVERY block decodes back to its original raw data."""
    raw = load_raw_strips(0)
    nt, coll_a, coll_b = parse_strips(raw)

    blob, dict_len, stats = generate_section_blocks(0)
    assert dict_len % 2 == 0, "dict length must be word-even"
    assert dict_len <= MAX_DICT_BLOCKS * BLOCK_RAW_SIZE
    assert dict_len % BLOCK_RAW_SIZE == 0, "dict must be whole raw blocks"

    raw_count = 0
    for block_y in range(BLOCKS_PER_AXIS):
        for block_x in range(BLOCKS_PER_AXIS):
            nt_data, coll_a_data, coll_b_data = extract_block(
                nt, coll_a, coll_b, block_x, block_y)
            expected = nt_data + coll_a_data + coll_b_data
            idx = block_y * BLOCKS_PER_AXIS + block_x
            decoded = decode_block(blob, dict_len, idx)
            if decoded is None:
                assert all(b == 0 for b in expected), (
                    f"Block ({block_x},{block_y}) marked empty but has data")
                continue
            entry = struct.unpack_from(">I", blob, idx * 4)[0]
            if entry & RAW_DIRECT_BIT:
                raw_count += 1
            assert len(decoded) == BLOCK_RAW_SIZE, (
                f"Block ({block_x},{block_y}): {len(decoded)} bytes")
            assert decoded == expected, (
                f"Block ({block_x},{block_y}) roundtrip mismatch")

    assert raw_count == dict_len // BLOCK_RAW_SIZE, (
        f"{raw_count} raw-direct entries vs dict of "
        f"{dict_len // BLOCK_RAW_SIZE} blocks")

    # Spot-check the (0,0) block content against the source grids
    decoded = decode_block(blob, dict_len, 0)
    assert decoded is not None, "Block (0,0) should not be empty"
    assert struct.unpack_from(">H", decoded, 0)[0] == nt[0][0]
    assert struct.unpack_from(">H", decoded, (5 * BLOCK_SIZE + 3) * 2)[0] == nt[5][3]
    assert decoded[BLOCK_NT_SIZE] == coll_a[0][0]
    assert decoded[BLOCK_NT_SIZE + BLOCK_COLL_PLANE_SIZE] == coll_b[0][0]
    plane_a = decoded[BLOCK_NT_SIZE:BLOCK_NT_SIZE + BLOCK_COLL_PLANE_SIZE]
    plane_b = decoded[BLOCK_NT_SIZE + BLOCK_COLL_PLANE_SIZE:
                      BLOCK_NT_SIZE + 2 * BLOCK_COLL_PLANE_SIZE]
    assert plane_a == plane_b, "OJZ roundtrip: plane B must equal plane A"

    print(f"  test_generate_roundtrip OK (all blocks verified, K={stats['k']})")


def test_empty_blocks():
    """Verify that blocks in unused rows are null in the index."""
    output, _, _ = generate_section_blocks(0)
    index_data = output[:BLOCK_INDEX_SIZE]

    # Last block row (15) should be empty for typical OJZ data
    for block_x in range(BLOCKS_PER_AXIS):
        idx = 15 * BLOCKS_PER_AXIS + block_x
        offset = struct.unpack_from(">I", index_data, idx * 4)[0]
        assert offset == 0, f"Block ({block_x},15) should be empty, offset={offset}"

    print("  test_empty_blocks OK")


def test_block_count():
    """Verify non-empty block count is reasonable."""
    output, _, _ = generate_section_blocks(0)
    index_data = output[:BLOCK_INDEX_SIZE]
    non_empty = sum(1 for i in range(BLOCKS_PER_SECTION)
                    if struct.unpack_from(">I", index_data, i * 4)[0] != 0)

    assert non_empty <= BLOCKS_PER_SECTION, f"Expected ≤{BLOCKS_PER_SECTION} non-empty blocks, got {non_empty}"
    assert non_empty > 0, "Expected at least some non-empty blocks"
    print(f"  test_block_count OK ({non_empty} non-empty blocks)")


def run_tests():
    print("Running ojz_block_gen tests...")
    test_parse_strips()
    test_extract_block()
    test_generate_roundtrip()
    test_empty_blocks()
    test_block_count()
    print("All tests passed.")


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in ("test", "generate"):
        print("Usage: python3 tools/ojz_block_gen.py test|generate")
        sys.exit(1)
    if sys.argv[1] == "test":
        run_tests()
    elif sys.argv[1] == "generate":
        generate_all()
