#!/usr/bin/env python3
"""OJZ block-format data generator.

Converts existing column-strip data (generated by ojz_strip_gen.py) into
16x16 tile blocks with embedded collision, independently S4LZ-compressed.

Usage:
    python3 tools/ojz_block_gen.py generate
    python3 tools/ojz_block_gen.py test

Input:  data/generated/ojz/act1/sec{N}_strips_a.bin (raw strip files)
Output: data/generated/ojz/act1/sec{N}_blocks.bin (block index + compressed blocks)

Each output file contains:
  - 256 × 4 bytes = 1024-byte block index table
    (each entry is a byte offset from file start, 0 = empty/air block)
  - Concatenated S4LZ-compressed blocks
    (each block = 512 bytes nametable + 128 bytes collision = 640 bytes raw)
"""

import struct
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import s4lz

# Constants — must match constants.asm
SECTION_TILE_WIDTH = 256
SECTION_TILE_HEIGHT = 256
BLOCK_SIZE = 16
BLOCKS_PER_AXIS = SECTION_TILE_WIDTH // BLOCK_SIZE  # 16
BLOCKS_PER_SECTION = BLOCKS_PER_AXIS * BLOCKS_PER_AXIS  # 256
BLOCK_NT_SIZE = BLOCK_SIZE * BLOCK_SIZE * 2  # 512 bytes
BLOCK_COLL_COLS = BLOCK_SIZE  # 16 collision columns (1 per tile column)
BLOCK_COLL_ROWS = BLOCK_SIZE // 2  # 8 collision rows (16px cells)
BLOCK_COLL_SIZE = BLOCK_COLL_COLS * BLOCK_COLL_ROWS  # 128 bytes
BLOCK_RAW_SIZE = BLOCK_NT_SIZE + BLOCK_COLL_SIZE  # 640 bytes

# Strip format (from ojz_strip_gen.py)
STRIP_TILE_HEIGHT = 256
STRIP_NT_BYTES = STRIP_TILE_HEIGHT * 2  # 512
STRIP_COLL_ROWS = STRIP_TILE_HEIGHT // 2  # 128
STRIP_COLL_OFFSET = STRIP_NT_BYTES  # 512
STRIP_PAD = 8
STRIP_BYTE_SIZE = STRIP_NT_BYTES + STRIP_COLL_ROWS + STRIP_PAD  # 648

BLOCK_INDEX_SIZE = BLOCKS_PER_SECTION * 4  # 1024 bytes

OUTPUT_DIR = os.path.join(
    os.path.dirname(__file__), "..", "data", "generated", "ojz", "act1"
)

NUM_SECTIONS = 9
SECTION_IDS = list(range(NUM_SECTIONS))


def load_raw_strips(section_idx):
    """Load raw (uncompressed) strip data for a section.

    Returns raw bytes — 128 bytes per column × 256 columns = 32768 bytes.
    """
    path = os.path.join(OUTPUT_DIR, f"sec{section_idx}_strips_a.bin")
    with open(path, "rb") as f:
        return f.read()


def parse_strips(raw_data):
    """Parse raw strip data into nametable grid + collision grid.

    Returns:
        nametable: 2D list [row][col] of 16-bit tile words (256 cols × 48 rows)
        collision: 2D list [coll_row][col] of 8-bit collision bytes (256 cols × 24 rows)
    """
    num_cols = len(raw_data) // STRIP_BYTE_SIZE

    # Build row-major nametable
    nametable = [[0] * num_cols for _ in range(STRIP_TILE_HEIGHT)]
    collision = [[0] * num_cols for _ in range(STRIP_COLL_ROWS)]

    for col in range(num_cols):
        base = col * STRIP_BYTE_SIZE
        for row in range(STRIP_TILE_HEIGHT):
            word_off = base + row * 2
            nametable[row][col] = struct.unpack_from(">H", raw_data, word_off)[0]
        for cr in range(STRIP_COLL_ROWS):
            collision[cr][col] = raw_data[base + STRIP_COLL_OFFSET + cr]

    return nametable, collision


def extract_block(nametable, collision, block_x, block_y):
    """Extract one 16×16 block's data from the full section grids.

    Returns (nt_bytes, coll_bytes):
        nt_bytes: 512 bytes — 16×16 tile words, row-major, big-endian
        coll_bytes: 128 bytes — 16 cols × 8 rows, row-major
    """
    nt_data = bytearray(BLOCK_NT_SIZE)
    for row in range(BLOCK_SIZE):
        tile_row = block_y * BLOCK_SIZE + row
        for col in range(BLOCK_SIZE):
            tile_col = block_x * BLOCK_SIZE + col
            if tile_row < len(nametable) and tile_col < len(nametable[0]):
                word = nametable[tile_row][tile_col]
            else:
                word = 0
            offset = (row * BLOCK_SIZE + col) * 2
            struct.pack_into(">H", nt_data, offset, word)

    coll_data = bytearray(BLOCK_COLL_SIZE)
    for cr in range(BLOCK_COLL_ROWS):
        abs_coll_row = block_y * BLOCK_COLL_ROWS + cr
        for col in range(BLOCK_SIZE):
            tile_col = block_x * BLOCK_SIZE + col
            if abs_coll_row < len(collision) and tile_col < len(collision[0]):
                byte = collision[abs_coll_row][tile_col]
            else:
                byte = 0
            coll_data[cr * BLOCK_COLL_COLS + col] = byte

    return bytes(nt_data), bytes(coll_data)


def generate_section_blocks(section_idx):
    """Generate block index + compressed blocks for one section.

    Returns bytes: [1024-byte index table] + [compressed blocks...]
    """
    raw_data = load_raw_strips(section_idx)
    nametable, collision = parse_strips(raw_data)

    compressed_blocks = []
    for block_y in range(BLOCKS_PER_AXIS):
        for block_x in range(BLOCKS_PER_AXIS):
            nt_data, coll_data = extract_block(nametable, collision, block_x, block_y)
            raw_block = nt_data + coll_data
            if all(b == 0 for b in raw_block):
                compressed_blocks.append(None)
            else:
                compressed, _ = s4lz.compress(raw_block, tile_delta=False)
                compressed_blocks.append(compressed)

    index_table = bytearray(BLOCK_INDEX_SIZE)
    block_data = bytearray()

    for i, block in enumerate(compressed_blocks):
        if block is None:
            struct.pack_into(">I", index_table, i * 4, 0)
        else:
            offset = BLOCK_INDEX_SIZE + len(block_data)
            struct.pack_into(">I", index_table, i * 4, offset)
            block_data.extend(block)
            if len(block_data) % 2:
                block_data.append(0)

    return bytes(index_table) + bytes(block_data)


def generate_all():
    """Generate block data for all OJZ sections."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    total_non_empty = 0
    total_blocks = 0

    for sec_idx in SECTION_IDS:
        print(f"Section {sec_idx}...", end=" ", flush=True)
        output = generate_section_blocks(sec_idx)

        index_data = output[:BLOCK_INDEX_SIZE]
        non_empty = sum(1 for i in range(BLOCKS_PER_SECTION)
                        if struct.unpack_from(">I", index_data, i * 4)[0] != 0)
        total_non_empty += non_empty
        total_blocks += BLOCKS_PER_SECTION

        out_path = os.path.join(OUTPUT_DIR, f"sec{sec_idx}_blocks.bin")
        with open(out_path, "wb") as f:
            f.write(output)
        print(f"{len(output)} bytes ({non_empty}/{BLOCKS_PER_SECTION} non-empty blocks)")

    print(f"\nDone. {total_non_empty}/{total_blocks} total non-empty blocks across {NUM_SECTIONS} sections.")


# ---------------------------------------------------------------------------
# Self-tests
# ---------------------------------------------------------------------------

def test_parse_strips():
    """Verify strip parsing produces correct dimensions."""
    raw = load_raw_strips(0)
    nt, coll = parse_strips(raw)
    assert len(nt) == STRIP_TILE_HEIGHT, f"Expected {STRIP_TILE_HEIGHT} rows, got {len(nt)}"
    assert len(nt[0]) == SECTION_TILE_WIDTH, f"Expected {SECTION_TILE_WIDTH} cols, got {len(nt[0])}"
    assert len(coll) == STRIP_COLL_ROWS, f"Expected {STRIP_COLL_ROWS} coll rows, got {len(coll)}"
    assert len(coll[0]) == SECTION_TILE_WIDTH
    print("  test_parse_strips OK")


def test_extract_block():
    """Verify block extraction matches source data."""
    raw = load_raw_strips(0)
    nt, coll = parse_strips(raw)

    # Block (0,0) should match the top-left 16×16 of the section
    nt_data, coll_data = extract_block(nt, coll, 0, 0)
    assert len(nt_data) == BLOCK_NT_SIZE
    assert len(coll_data) == BLOCK_COLL_SIZE

    # Check first tile word matches
    expected_word = nt[0][0]
    actual_word = struct.unpack_from(">H", nt_data, 0)[0]
    assert actual_word == expected_word, f"First word: expected 0x{expected_word:04X}, got 0x{actual_word:04X}"

    # Block (0, 15) should be entirely empty (last block row, typically air)
    nt_data_empty, coll_data_empty = extract_block(nt, coll, 0, 15)
    assert all(b == 0 for b in nt_data_empty), "Block at row 15 should be all air"
    assert all(b == 0 for b in coll_data_empty), "Block collision at row 15 should be all zero"

    print("  test_extract_block OK")


def test_generate_roundtrip():
    """Verify blocks can be decompressed back to original data."""
    raw = load_raw_strips(0)
    nt, coll = parse_strips(raw)

    # Generate blocks
    output = generate_section_blocks(0)
    index_data = output[:BLOCK_INDEX_SIZE]

    # Decompress block (0,0) and verify
    block_idx = 0 * BLOCKS_PER_AXIS + 0  # block_y=0, block_x=0
    offset = struct.unpack_from(">I", index_data, block_idx * 4)[0]
    assert offset > 0, "Block (0,0) should not be empty"

    decompressed = s4lz.decompress(output[offset:])
    assert len(decompressed) == BLOCK_RAW_SIZE, f"Expected {BLOCK_RAW_SIZE}, got {len(decompressed)}"

    # First nametable word should match
    expected = nt[0][0]
    actual = struct.unpack_from(">H", decompressed, 0)[0]
    assert actual == expected, f"Roundtrip word 0: expected 0x{expected:04X}, got 0x{actual:04X}"

    # Verify a tile deeper in the block: row 5, col 3
    expected_deep = nt[5][3]
    actual_deep = struct.unpack_from(">H", decompressed, (5 * BLOCK_SIZE + 3) * 2)[0]
    assert actual_deep == expected_deep, (
        f"Roundtrip (5,3): expected 0x{expected_deep:04X}, got 0x{actual_deep:04X}"
    )

    # Verify collision: first collision row, col 0
    coll_offset = BLOCK_NT_SIZE
    expected_coll = coll[0][0]
    actual_coll = decompressed[coll_offset]
    assert actual_coll == expected_coll, f"Collision (0,0): expected {expected_coll}, got {actual_coll}"

    print("  test_generate_roundtrip OK")


def test_empty_blocks():
    """Verify that blocks in unused rows are null in the index."""
    output = generate_section_blocks(0)
    index_data = output[:BLOCK_INDEX_SIZE]

    # Last block row (15) should be empty for typical OJZ data
    for block_x in range(BLOCKS_PER_AXIS):
        idx = 15 * BLOCKS_PER_AXIS + block_x
        offset = struct.unpack_from(">I", index_data, idx * 4)[0]
        assert offset == 0, f"Block ({block_x},15) should be empty, offset={offset}"

    print("  test_empty_blocks OK")


def test_block_count():
    """Verify non-empty block count is reasonable."""
    output = generate_section_blocks(0)
    index_data = output[:BLOCK_INDEX_SIZE]
    non_empty = sum(1 for i in range(BLOCKS_PER_SECTION)
                    if struct.unpack_from(">I", index_data, i * 4)[0] != 0)

    assert non_empty <= BLOCKS_PER_SECTION, f"Expected ≤{BLOCKS_PER_SECTION} non-empty blocks, got {non_empty}"
    assert non_empty > 0, "Expected at least some non-empty blocks"
    print(f"  test_block_count OK ({non_empty} non-empty blocks)")


def run_tests():
    print("Running ojz_block_gen tests...")
    test_parse_strips()
    test_extract_block()
    test_generate_roundtrip()
    test_empty_blocks()
    test_block_count()
    print("All tests passed.")


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in ("test", "generate"):
        print("Usage: python3 tools/ojz_block_gen.py test|generate")
        sys.exit(1)
    if sys.argv[1] == "test":
        run_tests()
    elif sys.argv[1] == "generate":
        generate_all()
