#!/bin/bash
set -euo pipefail

# regenerate-level.sh — MANUAL re-bake of the OJZ generated level tree +
# collision tables. These outputs are COMMITTED artifacts the build consumes
# directly (see .gitignore, the level-gen parcel); the build never runs these
# generators, because they read TWO out-of-repo donor projects at paths that
# only exist on an authoring machine:
#
#   sonic_hack  (level layouts / Kosinski art / chunk+block maps) — override
#               with AEON_SONIC_HACK_DIR; default /home/volence/sonic_hacks/sonic_hack
#   skdisasm    (S&K collision shape vocabulary) — override with
#               AEON_SKDISASM_DIR; default ../skdisasm relative to this repo
#
# Run this by hand when the editor data or a donor project changes, then commit
# the regenerated tree (the level drift check — tools/verify_level_bin.py — and
# the whole-ROM byte gate confirm it). A missing donor / absent editor data is a
# HARD ERROR (ojz_strip_gen.generate() refuses the silent legacy-air fallback).
#
# USAGE (from the repo root):  tools/regenerate-level.sh

cd "$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
TOOLS="${TOOLS:-tools}"

# Build the vendored salvador (ZX0 packer) once if missing (build.sh does the
# same; re-bakes may run standalone).
if [[ ! -x "${TOOLS}/bin/salvador" ]]; then
    echo "Building salvador (ZX0 packer)..."
    make -C "${TOOLS}/salvador" -s
    mkdir -p "${TOOLS}/bin"
    cp "${TOOLS}/salvador/salvador" "${TOOLS}/bin/salvador"
fi

echo "Importing Sonic & Knuckles collision shape set (fixed 252-shape vocabulary)..."
python3 "${TOOLS}/import_sk_collision.py"

echo "Generating OJZ section data..."
python3 "${TOOLS}/ojz_strip_gen.py" generate

# Editor-authored BG override (level editor art) — replaces the generated
# zone BG when games/sonic4/data/editor_bg_override.json exists.
if [[ -f games/sonic4/data/editor_bg_override.json ]]; then
    python3 "${TOOLS}/inject_editor_bg.py"
fi

# Act art pool pages → ZX0 (load-time tier). The generator emits the
# globally-deduped act art pool split into fixed-size pages of ART_POOL_PAGE_TILES
# (256) tiles = 8192 B each. Each .zx0 carries the project's 4-byte wrapper
# [u16 BE uncompressed size][u8 flags=0][u8 version=2] ahead of the raw salvador
# (modern/V2) stream — the loader peeks the size for DMA and dispatches the
# decompressor on the version byte.
#
# Size guard: a single page must not exceed one VRAM page worth of tiles
# (ART_POOL_PAGE_BYTES). The generator should never emit an oversized page; a
# page larger than this is a generator bug and would overrun the page's VRAM
# slot at load time — fail the re-bake.
ART_POOL_PAGE_BYTES=8192      # ART_POOL_PAGE_TILES (256) * 32
# Page count comes from the generator's manifest — pages are addressed by
# NUMERIC index (act_pool_page${k}), never by glob, so ordering is correct at
# any page count (a glob puts page10 before page2) and stale leftover pages
# from a previously larger pool are never compressed or bundled.
POOL_DIR="games/sonic4/data/generated/ojz/act1"
POOL_MANIFEST="${POOL_DIR}/ojz_act_pool_manifest.emp"
POOL_PAGES=$(sed -n 's/^\(pub const \)\?OJZ_ACT_POOL_PAGES = \([0-9]\+\)$/\2/p' "$POOL_MANIFEST")
if [[ -z "$POOL_PAGES" ]]; then
    echo "ERROR: could not read OJZ_ACT_POOL_PAGES from ${POOL_MANIFEST}."; exit 1
fi
echo "Compressing ${POOL_PAGES} act art pool pages with ZX0 (salvador)..."
rm -f "${POOL_DIR}"/act_pool_page*.zx0 "${POOL_DIR}"/act_pool_page*.zx0.tmp
for (( k = 0; k < POOL_PAGES; k++ )); do
    page_bin="${POOL_DIR}/act_pool_page${k}.bin"
    page_zx0="${page_bin%.bin}.zx0"
    if [[ ! -f "$page_bin" ]]; then
        echo "ERROR: ${page_bin} missing but manifest declares ${POOL_PAGES} pages."; exit 1
    fi
    size=$(stat -c%s "$page_bin")
    if (( size > ART_POOL_PAGE_BYTES )); then
        echo "ERROR: ${page_bin} is ${size} B — exceeds one page (${ART_POOL_PAGE_BYTES})."; exit 1
    fi
    "${TOOLS}/bin/salvador" "$page_bin" "${page_zx0}.tmp" > /dev/null
    printf '%b' "$(printf '\\x%02x\\x%02x\\x00\\x02' $((size >> 8)) $((size & 255)))" > "$page_zx0"
    cat "${page_zx0}.tmp" >> "$page_zx0"; rm -f "${page_zx0}.tmp"
done

# Emit the act art pool as a native `.emp` section: page embeds followed by a
# longword address table the loader indexes by page number (Parcel K3 run A).
# act_descriptor.emp consumes OJZ_Act_Pool_PageTable across the link.
echo "Emitting act art pool .emp section..."
POOL_EMP="${POOL_DIR}/ojz_act_pool.emp"
{
  echo "// AUTO-GENERATED by tools/regenerate-level.sh — DO NOT EDIT."
  echo "// OJZ Act 1 act-wide paged art pool: the ZX0-compressed page embeds + a longword"
  echo "// page-address table the loader indexes by page number. Natively placed at the"
  echo "// ojz_act_pool section (Parcel K3 run A); consumed by act_descriptor.emp"
  echo "// (OJZ_Act_Pool_PageTable). Pages are even-length — no inter-page padding."
  echo "module games.sonic4.ojz_act_pool_act1 in ojz_act_pool"
  echo ""
  for (( k = 0; k < POOL_PAGES; k++ )); do
    echo "pub data OJZ_Act_Pool_Page${k} = embed(\"${POOL_DIR}/act_pool_page${k}.zx0\")"
  done
  ptrs=""
  for (( k = 0; k < POOL_PAGES; k++ )); do
    [[ -n "$ptrs" ]] && ptrs+=", "
    ptrs+="extern(\"OJZ_Act_Pool_Page${k}\")"
  done
  echo "pub data OJZ_Act_Pool_PageTable: [*u8; ${POOL_PAGES}] = [${ptrs}]"
} > "$POOL_EMP"

echo "Generating OJZ block data..."
python3 "${TOOLS}/ojz_block_gen.py" generate

echo "Re-bake complete. Verify: tools/verify_level_bin.py, then ./build.sh both shapes."
echo "The committed level tree should be byte-identical unless the editor data or"
echo "a donor project changed — review 'git status games/sonic4/data' before committing."
