#!/usr/bin/env bash
#
# seed-worktree.sh — OBSOLETE RELIC (kept as an error-checked stub).
#
# This script used to copy the whole gitignored artifact set into a fresh
# worktree because the OJZ level tree + collision tables were regenerated at
# build time from out-of-repo donors — a fresh worktree lacked them and built a
# ~131 KB wrong ROM (or failed). As of the level-gen parcel those artifacts are
# COMMITTED (games/sonic4/data/generated/, .../data/collision/*.bin), so a fresh
# worktree builds directly — no seeding. The only remaining build-time-generated
# artifacts (engine/sound/generated, engine/debug/generated) are regenerated by
# build.sh itself from in-repo inputs.
#
# It now COPIES NOTHING. It verifies the committed level tree is present and
# builds both shapes, so old "seed then build" muscle memory still works and any
# genuinely-unseeded tree fails loudly instead of silently building wrong.
#
# USAGE:  tools/seed-worktree.sh [<worktree-path>]   (default: this worktree)
set -euo pipefail

WT="${1:-$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)}"
WT="$(cd "$WT" && pwd)"
if [ ! -x "$WT/build.sh" ]; then
  echo "error: $WT does not look like an aeon worktree (no build.sh)" >&2
  exit 1
fi

echo "seed-worktree.sh is obsolete — the level tree + collision tables are committed."
echo "No files copied. Verifying the committed level tree is present in $WT ..."

missing=0
for f in \
  games/sonic4/data/generated/ojz/act1/entity_data.asm \
  games/sonic4/data/generated/ojz/act1/ojz_act_pool.asm \
  games/sonic4/data/generated/ojz/act1/sec_block_blobs.asm \
  games/sonic4/data/collision/heightmaps.bin ; do
  if [ ! -f "$WT/$f" ]; then
    echo "  MISSING: $f" >&2
    missing=1
  fi
done
if [ "$missing" != 0 ]; then
  echo "error: the committed level tree is not present — is this a real checkout of the" >&2
  echo "       level-gen (or later) history? A build here would be wrong." >&2
  exit 1
fi

echo "building reference ROMs (both shapes)..."
cd "$WT"
DEBUG=1 ./build.sh
./build.sh
echo "done: $WT builds directly (s4.bin + s4.debug.bin present); no seeding required."
