#!/usr/bin/env python3
"""test_night_settle_capture — drive the capture tool's naming, report and README path over a
SIMULATED fade, with no emulator anywhere.

WHAT THIS COVERS. Everything between "a tick's state was read" and "a file has a name and a
README row": `enrich()` (k, the verdict, the derived filename), `build_report()` and
`readme()` -- the shipped functions, not a re-implementation, which is why `run()` was split
so they could be called. The simulated series is generated by `region_fade_witness.fade_model`,
the transcription of `Palette_DoFade`'s own step rule, with CRAM lagging the buffer by one
tick exactly as `capture_settle`'s N derivation says it does.

WHAT IT CANNOT COVER, and the boundary matters because a green here is not a green run: it
never reads a register. That `Pal_Fade_Frames` is at the address the listing says, that
`emulator/read_cram` returns 16 entries a line, that the screenshot is the frame the header
claims -- those live only in a foreground run against a real Oracle, and the tool's own
SetupError refusals are what carry them. This file proves the LOGIC cannot name a mid-fade
frame settled; it does not prove the reads are right.

THE EXPECTATION IS DERIVED. The tick at which the simulated run first settles is not typed
here: it is computed from PAL_FADE_FRAMES, from the step rule's odd-count parity, from the
channel distance of the constructed palette pair, and from N. If any of those move, the
derived expectation moves with them and the test still means what it says.

WHICH MEANS THIS FILE DOES NOT PIN N, and a reader must not expect it to. Measured
2026-09-16: setting `CRAM_TO_CAPTURED_FRAME_TICKS = 0` leaves every row here GREEN, because
the expectation moves with the constant -- exactly what "derive it" buys and exactly what it
costs. The ABSOLUTE pin (`stable_ticks == 3`, and each ordering the terms are read from) is
tools/test_capture_settle.py::test_n_is_three_and_carries_its_derivation and its mutation
rows, where that same edit is red. Deriving here and pinning there is the split on purpose;
do not "fix" this file by typing a 3 into it.
"""
from __future__ import annotations

import json
import os
import re
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
AEON = os.path.dirname(HERE)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import capture_settle as cs                 # noqa: E402
import night_settle_capture as nsc          # noqa: E402
import region_fade_witness as rfw           # noqa: E402
from pathlib import Path                    # noqa: E402

#: A day/night pair whose maximum channel distance is exactly 3 -- the night recipe's largest
#: per-channel move (red -3), so the simulated fade has the real one's length.
DAY = [((i % 8) << 9) | (7 << 5) | (7 << 1) for i in range(48)]
NIGHT = [((i % 8) << 9) | (5 << 5) | (4 << 1) for i in range(48)]

FADE_ROW = {"index": 9, "x0": 3400, "x1": 4799, "y0": 0, "y1": 2047}


def facts():
    return cs.derive_engine_facts(Path(AEON))


def simulate(n_pre=6, n_post=24, arm_at=10, tick0=260, cx0=3300, fly=16):
    """A run of state rows across the fade edge, CRAM lagging the buffer by one tick.

    `arm_at` is the index of the crossing tick (k = 0), i.e. the first tick the night region
    is current and the tick whose own compose is the fade's k = 1."""
    F = rfw.src_const("engine/effects/palette.emp", "PAL_FADE_FRAMES")
    rows = []
    for i in range(arm_at + n_post):
        if i < arm_at:
            buf, pf, tgt, row = list(DAY), 0, list(DAY), 1
        else:
            buf, pf = rfw.fade_model(DAY, NIGHT, i - arm_at + 1, F)
            tgt, row = list(NIGHT), FADE_ROW["index"]
        rows.append({
            "i": i, "tick": tick0 + i, "frame": tick0 + i, "lag": 0,
            "dtick": None if i == 0 else 1,
            "centre_x": cx0 + fly * i, "centre_y": 256,
            "region": 0x100000 + row, "row": row,
            "fade_frames": pf, "fade_request": 0, "pal_active": 0b10000,
            "pal_op": 0, "pal_base_dirty": 0, "pal_cycle_script": 0x00FF1234,
            "buffer": buf, "target": tgt,
            "cram": list(rows[-1]["buffer"]) if rows else list(DAY),
            "png": f"raw-i{i:04d}.png",
        })
    return rows, arm_at


def drive(rows, arm_at, f=None):
    """Assess every row in order, exactly as run()'s loop does, then enrich."""
    f = f or facts()
    verdicts = {}
    for i in range(len(rows)):
        verdicts[i] = cs.assess(rows[:i + 1], f)
    keep, dropped = nsc.enrich(list(rows), verdicts, arm_at)
    return keep, dropped, verdicts, f


def report_of(keep, rows, arm_at, f, stopped=None):
    return nsc.build_report("s4.debug.bin", "s4.debug.lst", "0" * 32, 3400, FADE_ROW, 1, 16,
                            f, nsc.ceiling_ticks(f.fade_frames_const, f.stable_ticks, 3),
                            rows, arm_at, keep, None, stopped)


# ------------------------------------------------------------------ the ceiling

def test_the_ceiling_is_derived_from_pal_fade_frames_and_n():
    f = facts()
    cap = nsc.ceiling_ticks(f.fade_frames_const, f.stable_ticks, 3)
    assert cap == 2 * (f.fade_frames_const + f.stable_ticks + 3)
    # It must exceed the fade's own worst case (the backstop close at k = PAL_FADE_FRAMES)
    # plus the stability window, or the tool would abort on a legitimately slow fade.
    assert cap > f.fade_frames_const + f.stable_ticks + 3
    # and it must stay inside the night region at flight speed, or the camera leaves first
    fly = rfw.src_const("games/sonic4/player/player_common.emp", "PLAYER_DEBUG_FLY_SPEED")
    assert cap * fly < (FADE_ROW["x1"] - FADE_ROW["x0"]), (
        "the ceiling is longer than the night region is wide at flight speed: the camera "
        "would leave the region before the ceiling fired, and the wrong refusal would print")


# ------------------------------------------------------------------ the simulated run

def test_the_simulated_fade_settles_exactly_where_the_step_rule_and_n_put_it():
    """THE DERIVED EXPECTATION. Nothing below is a typed constant.

    Palette_DoFade steps on ODD decremented counts, so a channel distance d arrives on the
    d-th step, at compose k = 2d - 1. The crossing tick's own compose is k = 1, so the buffer
    is settled at tick index arm + (2d - 2). CRAM lags the buffer one tick, and N consecutive
    identical CRAM samples are required, so the first settled TICK is arm + (2d - 2) + N."""
    rows, arm = simulate()
    keep, _, verdicts, f = drive(rows, arm)
    d = rfw.channel_distance(DAY, NIGHT)
    buffer_settles_at = arm + (2 * d - 1) - 1
    expect_first_settled = buffer_settles_at + f.stable_ticks

    first = next(i for i in range(len(rows)) if verdicts[i].settled and i >= arm)
    assert first == expect_first_settled, (
        f"d={d}, buffer settles at tick index {buffer_settles_at}, N={f.stable_ticks}")
    assert rows[first]["fade_frames"] == 0
    # and the frames between the counter reaching 0 and the settle are NOT settled: this is
    # the whole gap the 2026-09-13 set fell into
    for i in range(buffer_settles_at, first):
        assert not verdicts[i].settled, i
        assert verdicts[i].word in ("cram", "hold"), (i, verdicts[i].word)


def test_only_settled_ticks_get_the_word_and_every_name_carries_its_state():
    rows, arm = simulate()
    keep, _, verdicts, f = drive(rows, arm)
    assert keep, "nothing was kept"
    for r in keep:
        name = r["png"]
        assert (cs.SETTLED_WORD in name) == r["settled"], name
        # every name carries the tick, the camera centre and the fade counter
        assert f"t{r['tick']:05d}" in name, name
        assert f"cx{r['centre_x']:04d}" in name, name
        assert f"pf{r['fade_frames']:02d}" in name, name
        assert f"k{r['k']:+04d}" in name, name
    assert any(r["settled"] for r in keep), "the simulated run never settled: a vacuous pass"
    assert any(not r["settled"] for r in keep), "every frame settled: a vacuous pass"


def test_the_pre_crossing_control_is_settled_on_the_DAY_palette():
    """The predicate is not night-specific and is not vacuously false: the approach frames
    ARE settled, on the day palette, and the region row in the name is what tells them
    apart from the night ones."""
    rows, arm = simulate()
    keep, _, _, _ = drive(rows, arm)
    pre = [r for r in keep if r["k"] < 0]
    assert pre and all(r["settled"] for r in pre)
    assert all("-r01-" in r["png"] for r in pre)
    assert all("-r09-" in r["png"] for r in keep if r["k"] >= 0)


def test_the_approach_tail_is_dropped_and_k_runs_from_minus_PRE():
    rows, arm = simulate()
    keep, dropped, _, _ = drive(rows, arm)
    assert min(r["k"] for r in keep) == -nsc.PRE
    assert all(r["k"] < -nsc.PRE for r in dropped)


# ------------------------------------------------------------------ the frame-272 case

def test_the_2026_09_13_frame_cannot_be_named_settled_by_this_tool():
    """THE CASE, end to end through the shipped report and README.

    The 2026-09-13 set recorded, for the frame it called `settled`: k = 5, Pal_Fade_Frames =
    11, CRAM line 1 entry 2 already on its night value. That last fact is what the human read.
    Here the same shape is injected into a simulated run -- the tracer word arrived, the other
    47 have not, the counter says 11 -- and the tool is asked for a name and a README."""
    rows, arm = simulate()
    victim = arm + 4                       # k = +4; its compose is the fade's k = 5
    mid = [w for w in rows[victim]["buffer"]]
    mid[16 + 2] = NIGHT[16 + 2]            # the tracer entry, arrived early
    rows[victim]["buffer"] = mid
    rows[victim]["cram"] = list(mid)
    rows[victim]["fade_frames"] = 11       # what that README's own table records
    assert rows[victim]["cram"][16 + 2] == NIGHT[16 + 2], "the tracer must read as night"

    keep, _, verdicts, f = drive(rows, arm)
    v = verdicts[victim]
    assert not v.settled and v.word == "fading", v
    name = next(r["png"] for r in keep if r["i"] == victim)
    assert cs.SETTLED_WORD not in name, name
    assert "-pf11-fading.png" in name, name

    rep = report_of(keep, rows, arm, f)
    row = next(t for t in rep["ticks"] if t["i"] == victim)
    assert row["settle_state"] == "fading"
    assert name not in rep["settled_frames"]
    md = nsc.readme(rep)
    assert f"`{name}`" in md
    assert "| `fading` |" in md


# ------------------------------------------------------------------ the report and README

def test_the_report_round_trips_as_json_and_carries_the_derivation():
    rows, arm = simulate()
    keep, _, _, f = drive(rows, arm)
    rep = json.loads(json.dumps(report_of(keep, rows, arm, f)))
    assert rep["settle"]["stable_ticks_required"] == f.stable_ticks
    assert rep["settle"]["pal_fade_frames_const"] == f.fade_frames_const
    assert len(rep["settle"]["derivation"]) >= 5
    assert all({"claim", "from"} == set(d) for d in rep["settle"]["derivation"])
    assert rep["settled"] is True and rep["stopped_because"] is None
    assert rep["settled_frames"], "no settled frames offered for measurement"
    # the offer is scoped to the SUBJECT: every frame offered is inside the night region
    assert all("-r%02d-" % FADE_ROW["index"] in n for n in rep["settled_frames"])
    assert rep["control_frames"] and not (
        set(rep["control_frames"]) & set(rep["settled_frames"]))
    assert all("-r%02d-" % FADE_ROW["index"] not in n for n in rep["control_frames"])
    for t in rep["ticks"]:
        for arr in ("buffer", "target", "cram"):
            assert len(t[arr]) == 48 and all(len(w) == 4 for w in t[arr])
        assert "raw_png" not in t


def test_an_unsettled_run_offers_no_frame_and_says_so_loudly():
    """The ceiling arm. The README must NOT offer a settled frame, and must say the fade did
    not settle -- an unsettled run is a finding, and the failure mode to avoid is a set that
    reads like a normal one."""
    rows, arm = simulate(n_post=6)          # cut short before the stability window closes
    keep, _, _, f = drive(rows, arm)
    night = [r for r in keep if r["row"] == FADE_ROW["index"]]
    assert night and not any(r["settled"] for r in night)
    rep = report_of(keep, rows, arm, f, stopped="the fade had not settled at the ceiling")
    assert rep["settled"] is False
    assert rep["settled_frames"] == [], (
        "a run that did not settle offered a settled frame for measurement")
    # THE SCOPING, which is the thing this arm exists to pin: the approach frames ARE settled
    # (on the day palette) and must NOT be offered as night evidence.
    assert rep["control_frames"], "the day-palette control disappeared: the predicate is now "\
        "vacuously false and every clause below proves nothing"
    md = nsc.readme(rep)
    assert "DID NOT SETTLE" in md
    assert "may be used as a settled-night reference" in md
    for n in rep["control_frames"]:
        assert f"`{n}`" in md              # listed in the table, never offered as evidence


def test_the_readme_table_restates_every_captured_tick():
    rows, arm = simulate()
    keep, _, _, f = drive(rows, arm)
    md = nsc.readme(report_of(keep, rows, arm, f))
    for r in keep:
        assert f"`{r['png']}`" in md, r["png"]
    assert md.count("| +") + md.count("| -") >= len(keep)


# ------------------------------------------------------------------ the tool's own surface

def test_the_tool_declares_every_extra_symbol_it_reads():
    """A symbol read without being declared becomes a KeyError mid-walk instead of a named
    refusal. Derived from the reads in sample_row, not from a list typed twice."""
    src = Path(HERE, "night_settle_capture.py").read_text()
    body = src.split("async def sample_row")[1].split("\ndef ")[0]
    read = set(re.findall(r'rd\(b, sym, "(\w+)"', body))
    assert read, "sample_row no longer reads any symbol by name"
    assert read <= set(nsc.EXTRA_SYMBOLS), read - set(nsc.EXTRA_SYMBOLS)


def test_check_mode_needs_no_emulator_symbol():
    """--check must be reachable without any emulator import having to succeed at call time:
    it is the half of the failure surface a headless session can exercise, and the half the
    owner should run first on a new ROM/listing pair."""
    src = Path(HERE, "night_settle_capture.py").read_text()
    body = src.split("def premise(")[1].split("\nasync def run")[0]
    for forbidden in ("BusClient", "aether_emulator", "rig.", "emulator/"):
        assert forbidden not in body, (
            f"premise() touches {forbidden!r} — --check would need an emulator, and the one "
            "thing it is for is not needing one")
    # and --check's own arm calls it and returns without ever reaching the emulator block
    arm = src.split("if args.check:")[1].split("return 0")[0]
    assert "premise(args.rom, args.lst)" in arm
    for forbidden in ("BusClient", "aether_emulator", "asyncio.run"):
        assert forbidden not in arm, forbidden


def test_the_help_text_names_every_option_and_both_exit_codes():
    src = Path(HERE, "night_settle_capture.py").read_text()
    doc = nsc.__doc__
    assert "Exit 0" in doc and "2  COULD NOT RUN" in doc
    for opt in ("--rom", "--lst", "--outdir", "--settled-frames", "--check"):
        assert f'"{opt}"' in src, opt
    # every add_argument carries a help= (the owner drives this without reading the source)
    assert src.count("ap.add_argument(") == src.count("help=")
