# GENERATED by tools/gen_vram_map.py from games/sonic4/vram.toml — do not edit.
# Build tools import budget constants from HERE (one authority),
# instead of restating them (the four-copies-of-448 incident).
# GAME identifies the emitting contract: consumers that are sonic4-only
# (the OJZ tools) assert it, so an accidental demo --py run cannot
# silently poison their budget constants once the maps diverge.
GAME = 'sonic4'
REGIONS = {
    'fg_art_pool': {'base': 0, 'tiles': 768, 'lifetime': 'act'},
    'spare_nametable': {'base': 768, 'tiles': 128, 'lifetime': 'boot'},
    'debug_preset_readout': {'base': 883, 'tiles': 2, 'lifetime': 'mode'},
    'debug_bganim_tag': {'base': 885, 'tiles': 3, 'lifetime': 'mode'},
    'debug_lab_name': {'base': 888, 'tiles': 4, 'lifetime': 'mode'},
    'debug_raster_tag': {'base': 892, 'tiles': 4, 'lifetime': 'mode'},
    'dust_puff': {'base': 896, 'tiles': 16, 'lifetime': 'act'},
    'dust_spindash': {'base': 912, 'tiles': 12, 'lifetime': 'act'},
    'ring_sparkle': {'base': 924, 'tiles': 4, 'lifetime': 'act'},
    'insta_shield': {'base': 928, 'tiles': 29, 'lifetime': 'act'},
    'tails_appendage': {'base': 928, 'tiles': 9, 'lifetime': 'act'},
    'character_window': {'base': 960, 'tiles': 29, 'lifetime': 'act'},
    'test_obj': {'base': 992, 'tiles': 8, 'lifetime': 'mode'},
    'ring_placeholder': {'base': 1000, 'tiles': 16, 'lifetime': 'act'},
    'test_marker': {'base': 1016, 'tiles': 4, 'lifetime': 'mode'},
    'bg_region': {'base': 1024, 'tiles': 376, 'lifetime': 'act'},
    'waterline_strips': {'base': 1400, 'tiles': 32, 'lifetime': 'act'},
    'spring': {'base': 1448, 'tiles': 24, 'lifetime': 'act'},
    'sprite_table': {'base': 1472, 'tiles': 20, 'lifetime': 'boot'},
    'hscroll_table': {'base': 1504, 'tiles': 28, 'lifetime': 'boot'},
    'plane_a': {'base': 1536, 'tiles': 256, 'lifetime': 'boot'},
    'plane_b': {'base': 1792, 'tiles': 256, 'lifetime': 'boot'},
    'window_plane': {'base': 1920, 'tiles': 128, 'lifetime': 'boot'},
}
POOL_TILE_CEILING = 768
BG_TILE_BASE_SLOT = 1024
BG_TILE_CAPACITY = 376
BG_BAND_RESERVE = 56
BG_STATIC_TILE_BUDGET = 320
VRAM_DEBUG_PRESET_READOUT = 883
VRAM_DEBUG_BGANIM_TAG = 885
VRAM_DEBUG_LAB_NAME = 888
VRAM_DEBUG_RASTER_TAG = 892
VRAM_DUST_PUFF = 896
VRAM_DUST_SPINDASH = 912
VRAM_RING_SPARKLE = 924
VRAM_INSTA_SHIELD = 928
VRAM_TEST_SONIC = 960
VRAM_TEST_OBJ = 992
VRAM_TEST_MARKER = 1016
VRAM_SPRING = 1448
VRAM_TAILS_APPENDAGE = 928
