# GENERATED by tools/gen_vram_map.py from games/sonic4/vram.toml — do not edit.
# Build tools import budget constants from HERE (one authority),
# instead of restating them (the four-copies-of-448 incident).
# GAME identifies the emitting contract: consumers that are sonic4-only
# (the OJZ tools) assert it, so an accidental demo --py run cannot
# silently poison their budget constants once the maps diverge.
GAME = 'sonic4'
REGIONS = {
    'fg_art_pool': {'base': 0, 'tiles': 896, 'lifetime': 'act'},
    'dust_puff': {'base': 896, 'tiles': 16, 'lifetime': 'act'},
    'dust_spindash': {'base': 912, 'tiles': 12, 'lifetime': 'act'},
    'character_window': {'base': 960, 'tiles': 32, 'lifetime': 'act'},
    'test_obj': {'base': 992, 'tiles': 8, 'lifetime': 'mode'},
    'ring_placeholder': {'base': 1000, 'tiles': 16, 'lifetime': 'act'},
    'test_marker': {'base': 1016, 'tiles': 4, 'lifetime': 'mode'},
    'bg_region': {'base': 1024, 'tiles': 448, 'lifetime': 'act'},
    'sprite_table': {'base': 1472, 'tiles': 20, 'lifetime': 'boot'},
    'tails_appendage': {'base': 1492, 'tiles': 9, 'lifetime': 'act'},
    'hscroll_table': {'base': 1504, 'tiles': 28, 'lifetime': 'boot'},
    'plane_a': {'base': 1536, 'tiles': 256, 'lifetime': 'boot'},
    'plane_b': {'base': 1792, 'tiles': 256, 'lifetime': 'boot'},
    'window_plane': {'base': 1920, 'tiles': 128, 'lifetime': 'boot'},
}
POOL_TILE_CEILING = 896
BG_TILE_BASE_SLOT = 1024
BG_TILE_CAPACITY = 448
BG_BAND_RESERVE = 128
BG_STATIC_TILE_BUDGET = 320
VRAM_DUST_PUFF = 896
VRAM_DUST_SPINDASH = 912
VRAM_TEST_SONIC = 960
VRAM_TEST_OBJ = 992
VRAM_TEST_MARKER = 1016
VRAM_TAILS_APPENDAGE = 1492
