#!/usr/bin/env python3
"""vsplit_landing_gate — the TWO-WRITER ruling for per-layer vertical depth, measured.

WHAT IS BEING ASSERTED, AND WHY IT NEEDED AN INSTRUMENT (P3 Task 11 Step 2/3).

Plane B's vertical scroll word (VSRAM entry 1) has two writers in this engine:
`Parallax_Step5_Vscroll` computes it in VBlank and `Vscroll_Write` ships it at frame top,
while a vscroll-split raster fire writes it MID-FRAME from the HBlank handler. Task 11 lowers
`layer(vsplit: SceneVSplit.At(v))` into that fire, which makes the collision AUTHORABLE for
the first time, so the parcel owes a ruling on it. The ruling has two halves and this gate is
the half that cannot be settled by a build-time `ensure`:

  * REFUSED at comptime (`scene()` in engine/level/scene_dsl.emp): a camera-tracked plane
    (`v_factor != 15`) and a per-column V-deform scene. Those two ARE build errors and are
    red-first proven in the source.
  * PRECEDENCE, for what remains legal: the VBlank writer governs screen lines 0..N and the
    mid-frame write governs N+1..223, where N is the FIRE line and the authored screen line
    is N+1. That is a claim about the rendered picture, and prose cannot hold it.

THE MEASUREMENT IS A DIFFERENTIAL BETWEEN TWO SPLIT LINES, not a picture compared with a
description. Two programs identical except for the line they fire on (112 and 140) must
produce rendered frames that:

    rows   3 .. 111   IDENTICAL   — above BOTH splits, so the VBlank writer alone governs
                                    them; a mid-frame write below has no reach upward
    rows 112 .. 139   DIFFERENT   — only fixture A has split here; the mid-frame write
                                    governs these rows in A and the VBlank base in B
    rows 140 .. 223   IDENTICAL   — both fixtures now hold the SAME absolute scroll, so the
                                    two writers' disagreement has closed again

That third band is what makes this non-vacuous. A probe that merely detected "something
changed below a line" would pass on any shift; a probe reading a constant, a stale capture, or
a post-hoc end-of-frame render passes NONE of the three, because the middle band's boundaries
are the two authored lines and nothing else in the frame moves.

THE LANDING MODEL IS THE FIRST BOUNDARY. `fire()` schedules an event authored at screen line M
on FIRE LINE M-1 (raster_dsl.emp: "Ruling 1a: the event fire must be at M-1 so its writes land
on M"), so asserting that the first differing row is exactly the AUTHORED line is asserting
N+1 landing for a VSRAM op. Carried caveat, restated rather than glossed: emulators disagree
about mid-frame VSRAM — GensKMod latches at HBlank start, Exodus/BizHawk consult continuously,
and oracle-next is the continuous reading. This project has no real hardware, so N+1 is the
standard of evidence available, not a silicon fact.

AND TRANSIENCE, the half of precedence that is about TIME rather than about rows: the same
fixture captured on two consecutive frames must be identical above the boundary. The split is
a per-frame delta over a value the VBlank writer re-asserts every frame; if it accumulated,
the top of the screen would drift.

WHAT THE GATE ACTUALLY INSTALLS IS THE LOWERED PROGRAM. Fixture A's words are generated by
`raster_cost_probe.program_words` (the wire transcription pinned to raster_dsl.emp by
tools/test_raster_wire_pin.py) and then CHECKED AGAINST THE ROM: `OJZ_TestVsram` is the shipped
image of the same program, and games/sonic4/data/effects/ojz_effects.emp pins the scene
lowering (`OJZ_VSRAM_VIA_SCENE`) word-for-word against the hand twin that emits it. So the
chain is closed — what this gate drives on the emulator is, byte for byte, what
`layer(vsplit:)` lowers to. A mismatch is reported as SETUP (exit 2), never as a verdict.

POISONS — the gate is proven able to fail before it is believed (`--poison`):

    line     install fixture A at 140, where fixture B already is, while the expectations stay
             derived from 112. The band collapses to nothing and three checks fail. This is the
             COARSE poison: it proves the band is produced by the split at all.
    offbyone install fixture A one line lower (113) and change nothing else. MEASURED: the
             band narrows to 27 rows starting at 114, so checks 1, 2 and 3 all fail and the
             reported bias is 2. This is the poison that matters — the claim under test is a
             ONE-ROW landing fact, so the gate has to be shown resolving one row, and the
             coarse poison above proves nothing about that. Both edges of the band move
             together under it, which is why all three checks respond rather than just the
             landing one.

A THIRD POISON WAS TRIED AND DISCARDED, recorded because the reasoning is a trap. Writing
$0040 instead of $0043 is the DOCUMENTED pixel-invisible shift — OJZ's trunk band repeats every
64 px, so a 64 px scroll maps plane B onto itself, which cost a session in 2026-08-14. It is
invisible only RELATIVE TO A BASE THAT IS ITSELF A MULTIPLE OF 64. This gate is a differential
between two split lines, and at its pinned camera the VBlank base is 466 (Camera_Y 144 through
OJZ_Default's v_factor 3 / v_center 512, mod the 512-px plane), so $0040 differs from the base
by 90 px and bands perfectly well. The poison passed every check, correctly. Do not reinstate
it without re-deriving the base.

Usage:
    python3 tools/vsplit_landing_gate.py [--rom s4.debug.bin] [--lst s4.debug.lst]
                                         [--poison line|offbyone]
Exit: 0 the ruling holds as measured · 1 it does not · 2 setup / could-not-measure
"""
import argparse
import asyncio
import os
import subprocess
import sys
import time
from pathlib import Path

AEON = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))  # tools/, for suite_paths
from suite_paths import add_client_path, suite_path  # noqa: E402
add_client_path()  # the Aether client, resolved from the suite root; loud if absent
sys.path.insert(0, str(AEON / "tools"))

from aether import BusClient                                    # noqa: E402
from aether_instance import assert_rust_server  # noqa: E402
from raster_cost_probe import parse_lst, program_words, stream_vsram  # noqa: E402

SERVER = str(suite_path("oracle-next", "target", "release", "oracle-aether"))
SOCK = f"/tmp/aeon_vsplit_{os.getpid()}.sock"   # short + per-process: AF_UNIX caps at 108

# The two split lines and the scroll value. 112/$0043 are OJZ_TestVsram's own — the fixture
# whose landing was measured for the first time in Parcel C1 — so fixture A IS the shipped
# program and the ROM check below can hold it to that. 140 is fixture B: far enough below to
# leave a wide middle band, comfortably inside 3..223.
LINE_A, LINE_B, OFFSET = 112, 140, 0x0043
VSRAM_PLANE_B_BYTE = 2          # VSRAM byte 2 = entry 1 = plane B, whole-plane mode
LANDING_ROW_BIAS = 1            # THIS SERVER's calibration, measured 2026-08-20 (see check 3)

SETTLE_FRAMES = 180             # boot -> gameplay (the tree-wide constant)
POST_FREEZE_FRAMES = 3
DRIVE_FRAMES = 2                # one frame for Raster_VBlank to rewind onto the poked image
CAMERA_Y = 144                  # pinned, as the HBlank sweep pins it: a moving camera would
                                # make two captures differ for a reason that is not the split
ROW_LO, ROW_HI = 3, 223         # the raster-addressable display (lines 0-2 are the primers')
CHUNK = 32                      # rows per `emulator/scanlines` call — MEASURED, not chosen:
                                # a row's `rgb` is 1922 hex chars, and at 56 rows the server
                                # does not answer with an error, it CLOSES THE BUS
                                # ([-32000] bus connection closed, oracle-aether 2026-08-20).
                                # 32 answers; the cap is somewhere in between and the failure
                                # mode above is worth knowing before blaming a capture.

SYMS = ("Raster_Buf_A", "Raster_Program", "Raster_Active_Buf", "Raster_Patch_Tab",
        "Effects_Offscreen_Entry", "Debug_Scene_Freeze", "Camera_Y", "OJZ_TestVsram")


class SetupError(Exception):
    """Something made the measurement impossible. Not a verdict — exit 2, never exit 1."""


def fixture_words(line: int, offset: int) -> list[int]:
    """The words `fx_vscroll_split(line, offset)` lowers to, through the pinned transcription.

    WORD 0 IS OVERRIDDEN, and it is not a fudge. `raster_cost_probe` emits a fixed
    `PIN_MASK = $0002` because every COST fixture it was written for carries a CRAM op, and
    its module note says the constant is a property of those fixtures. A VSRAM op dirties NO
    palette line — `raster_dsl.emp`'s `op_mask` VSRAM arm says so and ojz_effects.emp pins it
    twice (`pal_dirty_mask is {..}, not 0 — a VSRAM op must dirty no palette line`), for the
    good reason that a mask derived from a VSRAM ADDRESS would read as CRAM line 0, the
    character's, and re-assert it every frame. Setting it to 0 here is what makes the
    generated image equal the shipped one, which the ROM check in main() then proves.
    """
    w = program_words([(line, [stream_vsram(VSRAM_PLANE_B_BYTE, [offset])])])
    w[0] = 0
    return w


class Server:
    """One oracle-aether process. A fresh one per capture — every capture starts from reset."""

    def __init__(self, rom: str, sock: str = SOCK):
        self.rom, self.sock, self.proc, self.client = rom, sock, None, None

    async def __aenter__(self) -> "Server":
        if os.path.exists(self.sock):
            os.unlink(self.sock)
        self.proc = subprocess.Popen([SERVER, self.rom, "--socket", self.sock, "--no-pace"],
                                     stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        for _ in range(200):
            if os.path.exists(self.sock):
                break
            time.sleep(0.05)
        else:
            raise SetupError(f"oracle-aether never created {self.sock}")
        self.client = BusClient(self.sock, client_id="vsplit", client_name="vsplit_landing_gate")
        info = await self.client.connect()
        # The identity assertion, shared with every other gate in this lane
        # (`tools/aether_instance.py`): this gate has ALWAYS spawned oracle-aether,
        # but nothing checked that the thing which answered was it. A gate silently
        # talking to the legacy server reports a verdict measured on the wrong
        # emulator and nothing goes red.
        assert_rust_server(info)
        for m in ("emulator/scanlines", "emulator/write_memory", "emulator/read_memory"):
            if not self.client.supports(m):
                raise SetupError(f"the server does not advertise `{m}`")
        return self

    async def __aexit__(self, *exc) -> None:
        try:
            if self.client:
                await self.client.close()
        finally:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except Exception:
                self.proc.kill()


async def _c(b, method, params=None, timeout=180.0):
    """Every RPC gets a deadline — a call with none blocks the next one forever on a wedge."""
    return await asyncio.wait_for(b.call(method, params or {}), timeout=timeout)


async def read_rows(b, lo: int, hi: int) -> dict[int, str]:
    """Rendered rows lo..hi as raw rgb hex, in chunks. `source` is asserted on every reply."""
    out: dict[str, str] = {}
    line = lo
    while line <= hi:
        n = min(CHUNK, hi - line + 1)
        r = await _c(b, "emulator/scanlines", {"startLine": line, "count": n})
        if r.get("source") != "raster":
            raise SetupError(f"emulator/scanlines answered source={r.get('source')!r} "
                             f"(caveat {r.get('caveat')!r}) — a post-hoc render is rendered "
                             f"from END-OF-FRAME VDP state and cannot witness a mid-frame write")
        if r.get("mode") != "h40":
            raise SetupError(f"mode is {r.get('mode')!r}, not h40")
        got = {row["line"]: row["rgb"].upper().removeprefix("0X") for row in r["rows"]}
        if sorted(got) != list(range(line, line + n)):
            raise SetupError(f"rows returned {sorted(got)}, wanted {list(range(line, line + n))}")
        out.update(got)
        line += n
    return out


async def capture(b, sym: dict, words: list[int], extra_frames: int = 0) -> dict[int, str]:
    """Install `words` as the active raster program and read the display."""
    image = "".join(f"{w:04X}" for w in words)
    buf = sym["Raster_Buf_A"]

    await _c(b, "emulator/reset", {})
    await _c(b, "emulator/run_frames", {"frames": SETTLE_FRAMES}, timeout=300.0)
    # Freeze BEFORE the camera poke and before the install: a section crossing would build its
    # own schedule over the fixture and the failure would read as a landing.
    await _c(b, "emulator/write_memory",
             {"addr": hex(sym["Debug_Scene_Freeze"]), "value": 1, "width": 1})
    await _c(b, "emulator/write_memory",
             {"addr": hex(sym["Camera_Y"]), "value": CAMERA_Y, "width": 2})
    await _c(b, "emulator/run_frames", {"frames": POST_FREEZE_FRAMES})

    await _c(b, "emulator/write_memory", {"addr": hex(buf), "bytes": "0x" + image})
    for s, v in (("Raster_Patch_Tab", 0), ("Effects_Offscreen_Entry", 0),
                 ("Raster_Active_Buf", buf), ("Raster_Program", buf)):
        await _c(b, "emulator/write_memory", {"addr": hex(sym[s]), "value": v, "width": 4})
    await _c(b, "emulator/run_frames", {"frames": DRIVE_FRAMES + extra_frames})

    # The poke must have SURVIVED the frames it was measured over. Raster_Patch_Tab = 0 is
    # what stops Raster_BuildSchedule re-recording over it; this is the check that it worked.
    back = await _c(b, "emulator/read_memory", {"addr": hex(buf), "len": len(words) * 2})
    got = back["bytes"].upper().removeprefix("0X")
    if got != image:
        raise SetupError(f"the program was rewritten during the run\n  poked: {image}\n"
                         f"  read : {got}")
    return await read_rows(b, ROW_LO, ROW_HI)


def diff_rows(a: dict[int, str], b: dict[int, str]) -> list[int]:
    return [ln for ln in sorted(a) if a[ln] != b[ln]]


async def run(rom: str, sym: dict, poison: str | None) -> list[str]:
    fails: list[str] = []

    def check(label: str, cond: bool, detail: str) -> None:
        print(f"  {'PASS' if cond else 'FAIL'}  {label}: {detail}")
        if not cond:
            fails.append(label)

    off = OFFSET
    line_a = LINE_A
    if poison == "line":
        line_a = LINE_B
    elif poison == "offbyone":
        line_a = LINE_A + 1

    # FOUR CAPTURES, TWO FIXTURES x TWO CONSECUTIVE FRAMES. The second frame is not a
    # repetition: it is what makes the transience claim measurable WITHOUT confounding it
    # with background animation. The scene is frozen but not static — BgAnim and palette
    # cycling keep ticking — so "fixture A's rows changed between frames" is true and says
    # nothing. What accumulation would do is move A's rows AWAY FROM B's, and that is a
    # differential the animation cannot fake because it happens equally in both.
    async with Server(rom) as s:
        cap_a = await capture(s.client, sym, fixture_words(line_a, off))
    async with Server(rom) as s:
        cap_b = await capture(s.client, sym, fixture_words(LINE_B, off))
    async with Server(rom) as s:
        cap_a2 = await capture(s.client, sym, fixture_words(line_a, off), extra_frames=1)
    async with Server(rom) as s:
        cap_b2 = await capture(s.client, sym, fixture_words(LINE_B, off), extra_frames=1)

    differing = diff_rows(cap_a, cap_b)
    first = differing[0] if differing else None
    bias = None if first is None else first - LINE_A

    # (1) THE BAND'S WIDTH — the one figure no instrument calibration can move. Both
    #     boundaries carry whatever row bias the renderer has, so their DIFFERENCE is exactly
    #     the authored distance between the two splits. A landing that missed by a line at one
    #     end and not the other fails here even if the absolute rows look plausible.
    check("band width == authored split spacing", len(differing) == LINE_B - LINE_A,
          f"{len(differing)} rows differ between the fixtures; the two splits are authored "
          f"{LINE_B - LINE_A} rows apart ({LINE_A} and {LINE_B}), and the band between them is "
          f"the only place they can disagree")

    # (2) THE BAND IS CONTIGUOUS AND STARTS AT THE LANDING ROW. With (1) this pins the whole
    #     set: one run of rows, beginning `bias` below the authored line.
    want = None if bias is None else list(range(LINE_A + bias, LINE_B + bias))
    check("the disagreement is ONE contiguous band at the landing row", differing == want,
          f"rows differing = {differing[:3]}..{differing[-3:] if differing else []}; a single "
          f"run from {first} would be {want[:3] if want else None}..{want[-3:] if want else None}")

    # (3) THE LANDING MODEL, WITHIN WHAT THIS INSTRUMENT CAN RESOLVE. `fire()` schedules an
    #     event authored at screen line M on fire line M-1 so its writes land on M — the N+1
    #     model. This server renders a row ATOMICALLY AT ITS START (the documented limit: a
    #     landing resolves to +/-1 scanline and the early edge is not observable), so a write
    #     issued in line M-1's blanking is timestamped after row M has been emitted and first
    #     shows on M+1. MEASURED HERE: bias 1. On oracle (Exodus-derived, VSRAM consulted
    #     continuously) the same program measured bias 0 — first differing pixel row exactly
    #     112, docs/benchmarks/effects-p3/GATE-EVIDENCE.md. The two readings differ by exactly
    #     the instrument's own resolution, which is why this is a BAND and not an equality:
    #     the fact being defended is that the split lands on the authored line to within one
    #     row, and a fire scheduled at M instead of M-1 would read as bias 2 and fail.
    check("landing row is the authored line +/- the instrument's row resolution",
          bias in (0, 1),
          f"measured bias {bias} row(s) (first differing row {first}, authored line {LINE_A}) "
          f"— {LANDING_ROW_BIAS} is this server's calibration, 0 is oracle's")

    # (4) PRECEDENCE, TOP HALF. Every row above the split is identical between a frame that
    #     splits there and one that does not: a mid-frame write has no reach upward, so the
    #     VBlank writer owns rows 0..N outright.
    above = [ln for ln in differing if ln < LINE_A]
    check("VBlank writer governs the rows above the split", not above,
          f"{len(above)} of rows {ROW_LO}..{LINE_A - 1} differ between the two fixtures "
          f"(want 0){'' if not above else ': ' + str(above[:8])}")

    # (5) TRANSIENCE / NO ACCUMULATION. `Vscroll_Write` re-asserts the base every VBlank, so
    #     the split is a per-frame delta over a value the other writer owns. If it accumulated,
    #     the boundary would move or the rows above it would drift apart between the two
    #     fixtures. Asserted as the SAME band one frame later — animation moves both fixtures
    #     identically and cannot produce this.
    differing2 = diff_rows(cap_a2, cap_b2)
    check("the split does not accumulate frame to frame", differing2 == differing,
          f"one frame on, the fixtures disagree over {len(differing2)} rows "
          f"({differing2[:3]}..{differing2[-3:] if differing2 else []}); the same "
          f"{len(differing)} rows as the frame before means the base was re-asserted and "
          f"nothing carried over")

    drift = diff_rows(cap_a, cap_a2)
    if drift:
        print(f"  note  {len(drift)} row(s) of the SAME fixture moved between the two frames "
              f"(first {drift[0]}) — background animation, which is why check 5 is a "
              f"differential rather than a frame-to-frame equality")
    return fails


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--rom", default=str(AEON / "s4.debug.bin"))
    ap.add_argument("--lst", default=str(AEON / "s4.debug.lst"))
    ap.add_argument("--poison", choices=("line", "offbyone"), default=None)
    args = ap.parse_args()

    for p in (args.rom, args.lst, SERVER):
        if not Path(p).exists():
            print(f"SETUP: {p} does not exist")
            return 2
    try:
        syms = parse_lst(args.lst)
        sym = {}
        for n in SYMS:
            if n not in syms:
                raise SetupError(f"symbol {n} is not in {args.lst}")
            sym[n] = syms[n]

        # THE CHAIN-CLOSING CHECK. What this gate installs must be what `layer(vsplit:)`
        # lowers to. The comptime side of that chain is pinned in ojz_effects.emp (the scene
        # lowering against the hand-authored words); this is the other end — the hand-authored
        # words against the bytes in the ROM the emulator is about to run.
        rom = Path(args.rom).read_bytes()
        at = sym["OJZ_TestVsram"] & 0xFFFFFF
        want = fixture_words(LINE_A, OFFSET)
        got = [int.from_bytes(rom[at + 2 * i:at + 2 * i + 2], "big") for i in range(len(want))]
        if got != want:
            raise SetupError(
                "the generated fixture is not the shipped OJZ_TestVsram image, so this gate "
                "would be measuring a program the scene lowering does not produce.\n"
                f"        generated {[f'{w:04X}' for w in want]}\n"
                f"        in ROM    {[f'{w:04X}' for w in got]}")
        print(f"  setup  fixture A == OJZ_TestVsram @ ${at:06X} ({len(want)} words) — the "
              f"program this gate drives is the one the scene lowering emits")

        if args.poison:
            print(f"  POISON MODE: {args.poison} — the run is EXPECTED to fail")
        fails = asyncio.run(run(args.rom, sym, args.poison))
    except SetupError as e:
        print(f"SETUP: {e}")
        return 2
    except (asyncio.TimeoutError, OSError) as e:
        print(f"SETUP: {type(e).__name__}: {e}")
        return 2
    print(f"\n{'FAIL' if fails else 'PASS'}: vsplit landing/precedence "
          f"({len(fails)} failed check(s))")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
