; ======================================================================
; data/sound/sfx/sfx_b9.asm — GENERATED by tools/sfx_transcode.py
; SFX id $B9 (Sfx_B9)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_B9:
    dc.b   $C0, $00, $02, $00, $03, $01, $00, $10, $00, $22, $04, $01, $00, $18, $00, $22
    dc.b   $E0, $7A, $E1, $00, $E3, $45, $02, $FF, $E0, $77, $E1, $00, $01, $80, $E3, $43
    dc.b   $02, $FF, $04, $C0, $37, $72, $77, $49, $5C, $7F, $5C, $7F, $1F, $1F, $1F, $1F
    dc.b   $00, $00, $00, $00, $00, $00, $00, $00, $0F, $1F, $0F, $1F
Sfx_B9_End:

    align 2
