; ======================================================================
; data/sound/sfx/sfx_ab.asm — GENERATED by tools/sfx_transcode.py
; SFX id $AB (Sfx_AB)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_AB:
    dc.b   $80, $04, $01, $00, $04, $01, $00, $0A, $00, $21, $E0, $64, $E1, $00, $EC, $01
    dc.b   $01, $1A, $01, $E3, $3C, $18, $EC, $00, $00, $00, $00, $E5, $E0, $62, $E6, $18
    dc.b   $FF, $34, $C0, $00, $0C, $03, $09, $7F, $7F, $63, $7F, $9F, $8F, $8C, $D5, $00
    dc.b   $00, $00, $00, $00, $00, $00, $00, $0F, $0F, $0F, $0F
Sfx_AB_End:

    align 2
