; ======================================================================
; data/sound/sfx/sfx_3c.asm — GENERATED by tools/sfx_transcode.py
; SFX id $3C (Sfx_3C)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_3C:
    dc.b   $60, $04, $01, $00, $03, $01, $00, $0A, $00, $1C, $E0, $7A, $E1, $00, $01, $80
    dc.b   $E3, $49, $25, $E5, $E0, $79, $E3, $49, $02, $E6, $2A, $FF, $3C, $C0, $00, $44
    dc.b   $02, $02, $72, $7F, $57, $7F, $1F, $1F, $1F, $15, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $0F, $0F, $0F, $0F
Sfx_3C_End:

    align 2
