; ======================================================================
; data/sound/sfx/sfx_33_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $33: FmPatch bank (1 voice(s), 26 bytes)
; DO NOT EDIT BY HAND.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

Sfx_33_Patches_Count = 1

Sfx_33_Patches:
; --- voice 0 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte    55, 114, 119,  73   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    92, 127,  92, 127   ; fp_tl  $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar  $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r  $70  [S1,S3,S2,S4]
        pbyte    15,  31,  15,  31   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
Sfx_33_Patches_End:

        if (Sfx_33_Patches_End-Sfx_33_Patches)/FmPatch_len <> Sfx_33_Patches_Count
          error "SFX $33 patch bank count mismatch"
        endif
        if (Sfx_33_Patches_End-Sfx_33_Patches) <> Sfx_33_Patches_Count*FmPatch_len
          error "SFX $33 patch bank size mismatch"
        endif

