; ======================================================================
; data/sound/sfx/sfx_35.asm — GENERATED by tools/sfx_transcode.py
; SFX id $35 (Sfx_35)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_35:
    dc.b   $C0, $04, $01, $00, $04, $01, $00, $0A, $00, $18, $E0, $64, $E1, $00, $E3, $23
    dc.b   $07, $A1, $E5, $E0, $63, $E6, $2F, $FF, $30, $C0, $30, $30, $30, $30, $14, $14
    dc.b   $3C, $00, $9E, $DC, $D8, $DC, $0E, $04, $0A, $05, $08, $08, $08, $08, $BF, $BF
    dc.b   $BF, $BF
Sfx_35_End:

    align 2
