; ======================================================================
; data/sound/sfx/sfx_b6.asm — GENERATED by tools/sfx_transcode.py
; SFX id $B6 (Sfx_B6)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_B6:
    dc.b   $80, $00, $02, $00, $04, $01, $00, $10, $00, $2A, $08, $02, $00, $1B, $00, $00
    dc.b   $E0, $79, $EC, $01, $01, $C5, $1A, $E3, $4C, $0F, $FF, $E0, $50, $EB, $1D, $01
    dc.b   $80, $EC, $01, $02, $05, $FF, $E3, $5E, $4F, $FF, $3D, $C0, $09, $00, $03, $00
    dc.b   $09, $12, $04, $0E, $1F, $1F, $1F, $1F, $10, $0C, $0C, $0C, $0B, $10, $1F, $05
    dc.b   $1F, $4F, $2F, $2F
Sfx_B6_End:

    align 2
