; ======================================================================
; data/sound/sfx/sfx_b9.asm — GENERATED by tools/sfx_transcode.py
; SFX id $B9 (Sfx_B9)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_B9:
    dc.b   $C0, $00, $02, $00, $03, $01, $00, $10, $00, $1E, $04, $01, $00, $16, $00, $1E
    dc.b   $E0, $7A, $E3, $45, $02, $FF, $E0, $77, $01, $80, $E3, $43, $02, $FF, $04, $C0
    dc.b   $37, $77, $72, $49, $23, $23, $00, $00, $1F, $1F, $1F, $1F, $07, $07, $0A, $0D
    dc.b   $00, $00, $0B, $0B, $1F, $1F, $0F, $0F
Sfx_B9_End:

    align 2
