; ======================================================================
; data/sound/sfx/sfx_3c.asm — GENERATED by tools/sfx_transcode.py
; SFX id $3C (Sfx_3C)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_3C:
    dc.b   $60, $04, $01, $00, $03, $01, $00, $0A, $00, $24, $E0, $7A, $01, $80, $EC, $03
    dc.b   $01, $09, $FF, $E3, $55, $25, $EC, $00, $01, $00, $00, $E5, $E0, $79, $E3, $55
    dc.b   $02, $E6, $2A, $FF, $3C, $C0, $00, $02, $44, $02, $0D, $28, $00, $00, $1F, $1F
    dc.b   $1F, $15, $00, $00, $1F, $00, $00, $00, $00, $00, $0F, $0F, $0F, $0F
Sfx_3C_End:

    align 2
