; ======================================================================
; data/sound/sfx/sfx_ab.asm — GENERATED by tools/sfx_transcode.py
; SFX id $AB (Sfx_AB)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_AB:
    dc.b   $80, $04, $01, $00, $04, $01, $00, $0A, $00, $20, $E0, $64, $F0, $EC, $01, $01
    dc.b   $1A, $01, $E3, $3C, $18, $EC, $00, $00, $00, $00, $E5, $E0, $62, $E6, $18, $FF
    dc.b   $34, $C0, $00, $03, $0C, $09, $00, $1C, $00, $00, $9F, $8C, $8F, $D5, $00, $00
    dc.b   $00, $00, $00, $00, $00, $00, $0F, $0F, $0F, $0F
Sfx_AB_End:

    align 2
