; ======================================================================
; data/sound/sfx/sfx_b9_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $B9: FmPatch bank (1 voice(s), 32 bytes)
; DO NOT EDIT BY HAND.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

Sfx_B9_Patches_Count = 1

Sfx_B9_Patches:
; --- voice 0 ---
        pbyte   4                       ; fp_alg_fb     $04
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte    55, 119, 114,  73   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    35,  35,  13,  13   ; fp_tl  $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar  $50  [S1,S3,S2,S4]
        pbyte     7,   7,  10,  13   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,  11,  11   ; fp_d2r  $70  [S1,S3,S2,S4]
        pbyte    31,  31,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_ssg_eg  $90  [S1,S3,S2,S4]
        pbyte     0,   0                ; fp_reserved (pad to 32)
Sfx_B9_Patches_End:

        if (Sfx_B9_Patches_End-Sfx_B9_Patches)/FmPatch_len <> Sfx_B9_Patches_Count
          error "SFX $B9 patch bank count mismatch"
        endif
        if (Sfx_B9_Patches_End-Sfx_B9_Patches) <> Sfx_B9_Patches_Count*FmPatch_len
          error "SFX $B9 patch bank size mismatch"
        endif

