; ======================================================================
; data/sound/sfx/sfx_34.asm — GENERATED by tools/sfx_transcode.py
; SFX id $34 (Sfx_34)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_34:
    dc.b   $20, $00, $01, $00, $04, $01, $00, $0A, $00, $1A, $E0, $7A, $E1, $00, $E4, $80
    dc.b   $E3, $34, $05, $E3, $37, $05, $E3, $3C, $1B, $FF, $04, $C0, $37, $72, $77, $49
    dc.b   $5C, $7F, $5C, $7F, $1F, $1F, $1F, $1F, $00, $00, $00, $00, $00, $00, $00, $00
    dc.b   $0F, $1F, $0F, $1F
Sfx_34_End:

    align 2
