; ======================================================================
; data/sound/sfx/sfx_ab_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $AB: FmPatch bank (1 voice(s), 32 bytes)
; DO NOT EDIT BY HAND.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

Sfx_AB_Patches_Count = 1

Sfx_AB_Patches:
; --- voice 0 ---
        pbyte   52                      ; fp_alg_fb     $34
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,   3,  12,   9   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     0,  28,   0,   0   ; fp_tl  $40  [S1,S3,S2,S4]
        pbyte   159, 140, 143, 213   ; fp_rs_ar  $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r  $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_ssg_eg  $90  [S1,S3,S2,S4]
        pbyte     0,   0                ; fp_reserved (pad to 32)
Sfx_AB_Patches_End:

        if (Sfx_AB_Patches_End-Sfx_AB_Patches)/FmPatch_len <> Sfx_AB_Patches_Count
          error "SFX $AB patch bank count mismatch"
        endif
        if (Sfx_AB_Patches_End-Sfx_AB_Patches) <> Sfx_AB_Patches_Count*FmPatch_len
          error "SFX $AB patch bank size mismatch"
        endif

