; ======================================================================
; data/sound/sfx/sfx_35_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $35: FmPatch bank (1 voice(s), 32 bytes)
; DO NOT EDIT BY HAND.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

Sfx_35_Patches_Count = 1

Sfx_35_Patches:
; --- voice 0 ---
        pbyte   48                      ; fp_alg_fb     $30
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte    48,  48,  48,  48   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte    20,  20,  60,   0   ; fp_tl  $40  [S1,S3,S2,S4]
        pbyte   158, 220, 216, 220   ; fp_rs_ar  $50  [S1,S3,S2,S4]
        pbyte    14,   4,  10,   5   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     8,   8,   8,   8   ; fp_d2r  $70  [S1,S3,S2,S4]
        pbyte   191, 191, 191, 191   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_ssg_eg  $90  [S1,S3,S2,S4]
        pbyte     0,   0                ; fp_reserved (pad to 32)
Sfx_35_Patches_End:

        if (Sfx_35_Patches_End-Sfx_35_Patches)/FmPatch_len <> Sfx_35_Patches_Count
          error "SFX $35 patch bank count mismatch"
        endif
        if (Sfx_35_Patches_End-Sfx_35_Patches) <> Sfx_35_Patches_Count*FmPatch_len
          error "SFX $35 patch bank size mismatch"
        endif

