; ======================================================================
; data/sound/sfx/sfx_62.asm — GENERATED by tools/sfx_transcode.py
; SFX id $62 (Sfx_62)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_62:
    dc.b   $40, $00, $01, $00, $06, $02, $00, $0A, $00, $00, $E0, $50, $E3, $35, $05, $E3
    dc.b   $3A, $15, $FF
Sfx_62_End:

    align 2
