; ======================================================================
; data/sound/sfx/sfx_b9.asm — GENERATED by tools/sfx_transcode.py
; SFX id $B9 (Sfx_B9)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_B9:
    dc.b   $C0, $00, $02, $00, $03, $01, $00, $10, $00, $1A, $04, $01, $00, $14, $00, $1A
    dc.b   $E3, $45, $02, $FF, $01, $80, $E3, $43, $02, $FF, $04, $C0, $37, $77, $72, $49
    dc.b   $23, $23, $0D, $0D, $1F, $1F, $1F, $1F, $07, $07, $0A, $0D, $00, $00, $0B, $0B
    dc.b   $1F, $1F, $0F, $0F
Sfx_B9_End:

    align 2
