; ======================================================================
; data/sound/sfx/sfx_34.asm — GENERATED by tools/sfx_transcode.py
; SFX id $34 (Sfx_34)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_34:
    dc.b   $20, $00, $01, $00, $04, $01, $00, $0A, $00, $18, $E0, $7A, $E4, $80, $E3, $40
    dc.b   $05, $E3, $43, $05, $E3, $48, $1B, $FF, $04, $C0, $37, $77, $72, $49, $23, $23
    dc.b   $00, $00, $1F, $1F, $1F, $1F, $07, $07, $0A, $0D, $00, $00, $0B, $0B, $1F, $1F
    dc.b   $0F, $0F
Sfx_34_End:

    align 2
