; ======================================================================
; data/sound/sfx/sfx_3c_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $3C: FmPatch bank (1 voice(s), 26 bytes)
; DO NOT EDIT BY HAND.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

Sfx_3C_Patches_Count = 1

Sfx_3C_Patches:
; --- voice 0 ---
        pbyte   60                      ; fp_alg_fb     $3C
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     0,  68,   2,   2   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte   114, 127,  87, 127   ; fp_tl  $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  21   ; fp_rs_ar  $50  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_d2r  $70  [S1,S3,S2,S4]
        pbyte    15,  15,  15,  15   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
Sfx_3C_Patches_End:

        if (Sfx_3C_Patches_End-Sfx_3C_Patches)/FmPatch_len <> Sfx_3C_Patches_Count
          error "SFX $3C patch bank count mismatch"
        endif
        if (Sfx_3C_Patches_End-Sfx_3C_Patches) <> Sfx_3C_Patches_Count*FmPatch_len
          error "SFX $3C patch bank size mismatch"
        endif

