; ======================================================================
; data/sound/sfx/sfx_b6_patches.asm — GENERATED by tools/sfx_transcode.py
; SFX $B6: FmPatch bank (1 voice(s), 32 bytes)
; DO NOT EDIT BY HAND.
; ======================================================================

        ifndef pbyte_defined
pbyte_defined = 1
pbyte   macro                           ; emit data byte(s); CPU-correct directive
        if MOMCPUNAME="Z80"
        db      ALLARGS                  ; Z80 phase-0 blob context
        else
        dc.b    ALLARGS                  ; 68k ROM context
        endif
        endm
        endif

Sfx_B6_Patches_Count = 1

Sfx_B6_Patches:
; --- voice 0 ---
        pbyte   61                      ; fp_alg_fb     $3D
        pbyte   192                     ; fp_lr_ams_fms $C0
        pbyte     9,   0,   3,   0   ; fp_dt_mul  $30  [S1,S3,S2,S4]
        pbyte     9,  24,  10,  20   ; fp_tl  $40  [S1,S3,S2,S4]
        pbyte    31,  31,  31,  31   ; fp_rs_ar  $50  [S1,S3,S2,S4]
        pbyte    16,  12,  12,  12   ; fp_am_d1r  $60  [S1,S3,S2,S4]
        pbyte    11,  16,  31,   5   ; fp_d2r  $70  [S1,S3,S2,S4]
        pbyte    31,  79,  47,  47   ; fp_d1l_rr  $80  [S1,S3,S2,S4]
        pbyte     0,   0,   0,   0   ; fp_ssg_eg  $90  [S1,S3,S2,S4]
        pbyte     0,   0                ; fp_reserved (pad to 32)
Sfx_B6_Patches_End:

        if (Sfx_B6_Patches_End-Sfx_B6_Patches)/FmPatch_len <> Sfx_B6_Patches_Count
          error "SFX $B6 patch bank count mismatch"
        endif
        if (Sfx_B6_Patches_End-Sfx_B6_Patches) <> Sfx_B6_Patches_Count*FmPatch_len
          error "SFX $B6 patch bank size mismatch"
        endif

