; ======================================================================
; data/sound/sfx/sfx_36.asm — GENERATED by tools/sfx_transcode.py
; SFX id $36 (Sfx_36)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_36:
    dc.b   $60, $04, $02, $00, $07, $02, $00, $10, $00, $00, $06, $02, $00, $23, $00, $00
    dc.b   $E0, $50, $E3, $22, $01, $01, $80, $A3, $01, $80, $E5, $E3, $22, $01, $01, $80
    dc.b   $E6, $0B, $FF, $E0, $50, $01, $80, $E3, $20, $01, $01, $80, $A1, $01, $80, $E5
    dc.b   $E3, $20, $01, $01, $80, $E6, $0B, $FF
Sfx_36_End:

    align 2
