; ======================================================================
; data/sound/sfx/sfx_b6.asm — GENERATED by tools/sfx_transcode.py
; SFX id $B6 (Sfx_B6)
; Layout: SfxHeader(4) + per-channel records(6 each) + streams + FmPatch bank
; DO NOT EDIT BY HAND.
; ======================================================================

Sfx_B6:
    dc.b   $80, $00, $02, $00, $04, $01, $00, $10, $00, $2C, $08, $02, $00, $1D, $00, $00
    dc.b   $E0, $79, $E1, $00, $EC, $01, $01, $C5, $1A, $E3, $4C, $0F, $FF, $E0, $50, $EB
    dc.b   $1D, $01, $80, $EC, $01, $02, $05, $FF, $E3, $5E, $4F, $FF, $3D, $C0, $09, $03
    dc.b   $00, $00, $76, $7B, $6D, $71, $1F, $1F, $1F, $1F, $00, $00, $00, $00, $00, $00
    dc.b   $00, $00, $2F, $4F, $2F, $1F
Sfx_B6_End:

    align 2
